### ISSUE TITLE
Request error

### ISSUE THREAD

**Issue by dfcarpenter** [CargoSense/ex_aws#105]
I have a feeling it's a stupid configuration issue on my part but I just can't figure out how to get a request out.
``` 
** (FunctionClauseError) no function clause matching in ExAws.Dynamo.Request.url/1
    (ex_aws) lib/ex_aws/dynamo/request.ex:22: ExAws.Dynamo.Request.url(%{access_key_id: "REMOVED", debug_requests: true, host: "dynamodb.us-west-2.amazonaws.com", http_client: HTTPoison, json_codec: Poison, scheme: "http://", secret_access_key: "REMOVED"})
    (ex_aws) lib/ex_aws/dynamo/request.ex:13: ExAws.Dynamo.Request.request/3
```

config: 

```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "us-west-2",
  http_client: HTTPoison,
  dynamodb: [
    scheme: "http://",
    host: "dynamodb.us-west-2.amazonaws.com"
  ],
  debug_requests: true
```

**Comment by benwilson512** [comment]
region should go inside the dynamodb configuration block. You also probably want the https scheme.

**Comment by dfcarpenter** [comment]
So I finally got it configured but I had to go into the _build/dev/lib/ex_aws/ebin and modify the ex_aws.app file directly for my requests to work. I am in the us-west-2 region but I was unable to connect and I noticed the value in the region area was stuck on us-east-1 and was not changing no matter the settings I had in config.exs (and I tried adding the same settings in dev.exs)

    {dynamodb,
              [{scheme,<<"https://">>},
               {host,{<<"$region">>,<<"dynamodb.$region.amazonaws.com">>}},
               {region,<<"us-west-2">>},
               {port,80}]},

**Comment by benwilson512** [comment]
Have you tried this in the latest release? I pretty recently worked through using different regions with someone and it worked without issue.
