### ISSUE TITLE
S3 Timeouts

### ISSUE THREAD

**Issue by dmitriid** [CargoSense/ex_aws#111]
I'm getting timeouts when trying to upload to S3. Most likely something wrong with how I do things :)

The credentials are for the user which has ` AmazonS3FullAccess` and `AdministratorAccess`. The bucket is located in `US Standard`.

```elixir
#config/config.exs

use Mix.Config

config :slax, :ex_aws,
   access_key_id: [{:system, "acess"}, :instance_role],
   secret_access_key: [{:system, "secret"}, :instance_role],
   region: "us-west-1" ## timeouts with or without it, doesn't matter
```

```elixir
defmodule Slax do
  use ExAws.S3.Client, otp_app: :slax

  def go(path) do
    contents = File.read(path)

    name = "#{ZBase32.encode(Path.basename(path))}#{Path.extname(path)}"

    {:ok, stat} = File.stat(path)
    size = stat.size |> Integer.to_string

    put_object("media.dmitriid.com", name, contents, [{:content_type, "image/png"}, {:content_length, size}])

  end
end
```

```
ex(1)> Slax.go("/.../a.png")
** (exit) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %Slax{config: %{access_key_id: [{:system, "access"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.HTTPoison, json_codec: Poison, region: "us-west-1", scheme: "https://", secret_access_key: [{:system, "secret"}, :instance_role]}, service: :s3}}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:564: GenServer.call/3
    (ex_aws) lib/ex_aws/config.ex:59: ExAws.Config.retrieve_runtime_value/2
    (elixir) lib/stream.ex:454: anonymous fn/4 in Stream.map/2
    (elixir) lib/enum.ex:2744: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:1247: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:790: Enum.find/3
    (ex_aws) lib/ex_aws/config.ex:45: anonymous fn/3 in ExAws.Config.retrieve_runtime_config/1
    (stdlib) lists.erl:1262: :lists.foldl/3
iex(1)>
10:11:57.412 [error] GenServer ExAws.Config.AuthCache terminating
** (CaseClauseError) no case clause matching: {:error, %{__exception__: true, id: nil, reason: :connect_timeout}}
    (ex_aws) lib/ex_aws/instance_meta.ex:5: ExAws.InstanceMeta.request/2
    (ex_aws) lib/ex_aws/instance_meta.ex:15: ExAws.InstanceMeta.security_credentials/1
    (ex_aws) lib/ex_aws/config/auth_cache.ex:37: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws) lib/ex_aws/config/auth_cache.ex:27: ExAws.Config.AuthCache.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:refresh_config, %Slax{config: %{access_key_id: [{:system, "access"}, :instance_role], host: %{"ap-northeast-1" => "s3-ap-northeast-1.amazonaws.com", "ap-southeast-1" => "s3-ap-southeast-1.amazonaws.com", "ap-southeast-2" => "s3-ap-southeast-2.amazonaws.com", "eu-central-1" => "s3-eu-central-1.amazonaws.com", "eu-west-1" => "s3-eu-west-1.amazonaws.com", "sa-east-1" => "s3-sa-east-1.amazonaws.com", "us-east-1" => "s3.amazonaws.com", "us-west-1" => "s3-us-west-1.amazonaws.com", "us-west-2" => "s3-us-west-2.amazonaws.com"}, http_client: ExAws.Request.HTTPoison, json_codec: Poison, region: "us-west-1", scheme: "https://", secret_access_key: [{:system, "secret"}, :instance_role]}, service: :s3}}
State: ExAws.Config.AuthCache
```

**Comment by benwilson512** [comment]
Hey!

Have you added `:ex_aws` to your applications list in your mix.exs file? The error here indicates that the config cache genserver isn't up and running, which means the ExAws application hasn't been started.

**Comment by dmitriid** [comment]
Yes, here's my mix.exs:

```elixir
defmodule Slax.Mixfile do
  use Mix.Project

  def project do
    [app: :slax,
     version: "0.0.1",
     elixir: "~> 1.2",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  def application do
    [applications: [:logger, :ex_aws, :httpoison]]
  end

  defp deps do
    [
      ex_aws:    "~> 0.4.10",
      poison:    "~> 1.2",
      httpoison: "~> 0.7",
      zbase32: "~> 1.0.0"
    ]
  end
end
```

I'm running it with `iex -S mix`

I feel like there's something really minor and stupid, can't figure out what it is :)

**Comment by benwilson512** [comment]
Ah well for one thing in your config.exs you spelled your environment variable "acess" is that the actual environment variable in your config? If ExAws gets nil back from the System.get_env effort it tries to hit the AWS instance meta-data service which won't exist locally.

**Comment by dmitriid** [comment]
Yes, the "acess" and "secret" are The correct AWS access and secret ID. In the trace that I get in the console I see that these are picked up correctly from the environment

**Comment by benwilson512** [comment]
Ah sorry that confused me because access is spelled incorrectly so I thought it was a typo problem.

I will try to reproduce locally.

**Comment by boydm** [comment]
I've been having the same error, with the same callstack. I changed the config to look like this:

config :project, :ex_aws,
   access_key_id: "access_key",
   secret_access_key: "secret_key"

and now it works. So the S3 client doesn't like the recommended configuration in the documentation.

**Comment by benwilson512** [comment]
We definitely don't want the documentation to be wrong. I will look at it this weekend.

**Comment by dmitriid** [comment]
Perfect! Thank you!

I'll get back to hacking over the weekend as well :)

**Comment by JustMikey** [comment]
The configuration from the docs works for me. I think the reason for the timeouts might be that you did not namespace the `region` option with `s3` as in

```
config :slax, :ex_aws,
   access_key_id: [{:system, "acess"}, :instance_role],
   secret_access_key: [{:system, "secret"}, :instance_role],
   s3: [region: "us-west-1"]
```

So if it's not present, it will use `us-east-1` by default which is not your region I believe and if you put the way you did (without namespacing with `s3`), it would probably just be ignored and `us-east-1` would be used anyway.

**Comment by dmitriid** [comment]
Yes, you should specify the keys directly. It turns out that "US Standard" is actually `us-east-1` (see [here](http://docs.aws.amazon.com/general/latest/gr/rande.html)). So the config should be:

```
config :slax, :ex_aws,
   access_key_id: "access_key",
   secret_access_key: "secret_key",
   region: "us-east-1"
```

**Comment by JustMikey** [comment]
I guess it can be closed then

**Comment by madshargreave** [comment]
I am getting the same error using the following config

```
config :resend, :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "us-east-1"
```

Thing is, I also use the Arc library which builds upon ExAws (uses its configuration), and it works fine

**Comment by benwilson512** [comment]
I'm a bit confused about what the `:resend` part of the config is. If you're trying to do the global :ex_aws config it should be `config :ex_aws, etc`

**Comment by madshargreave** [comment]
It's the name of the application, removing it makes no difference

**Comment by benwilson512** [comment]
I mean, it may not have solved your problem but I assure you it makes a difference. What code are you running that times out? I need to look at how arc uses ExAws, it seems like it doesn't use config the same way precisely.

**Comment by madshargreave** [comment]
Yeah my bad, it didn't make a difference in the case of Arc

I am trying to store an object 
```
ExAws.S3.put_object!(@bucket, "some_key", "some_data")
```

**Comment by benwilson512** [comment]
Ok. Yeah so maybe ARC uses the `:ex_aws` config key under your application's name, not sure. `ExAws.S3` function calls will use the top level `config :ex_aws` stuff. If you do `ExAws.S3.new` can you post the config that comes out?. MAKE SURE TO REMOVE YOUR SECRET KEY!!! it will be in there.

**Comment by madshargreave** [comment]
I get 

```
{:error, %{__exception__: true, id: nil, reason: :ehostdown}}
```

**Comment by benwilson512** [comment]
`ExAws.S3.new` gives you that error? That doesn't make any sense. Are you sure you've got your environment variables set correctly? The only time config even does an http request is if it's trying to use the instance role, which it only falls back on if the environment variables return nil.

**Comment by madshargreave** [comment]
My apologies, it turned out my env variables was being sourced in iex where I was debugging.

It works correctly now that the env variables are being loaded correctly

Thanks for the help

**Comment by benwilson512** [comment]
No worries!

**Comment by VJOfficial** [comment]
@boydm 's solution works. thanks man.

**Comment by mkompanets** [comment]
Wanted to mention that this version of configuration worked for me:

```
config :ex_aws, 
  access_key_id: ["KEY_ID", :instance_role], 
  secret_access_key: ["SECRET_KEY", :instance_role]

```
