### ISSUE TITLE
Headers with more than 1 contiguous space character sign incorrectly

### ISSUE THREAD

**Issue by asonge** [CargoSense/ex_aws#113]
If I have a filename (for instance, in content-disposition) or header of some kind with more than 1 contiguous space, the signing doesn't match AWS's signing.

I'm not 100% confident of this, and will try to reproduce more detailed test cases later.

**Comment by benwilson512** [comment]
Could you give an example function call w/ arguments that give you the error?

**Comment by asonge** [comment]
```
S3.put_object(bucket, key, content, [content_disposition: "Something  with two spaces.txt"])
```

**Comment by benwilson512** [comment]
Finally looked into this (I suck) and it literally wants us to deduplicate spaces in the headers. I've heard some chatter that allowing consecutive spaces is deprecated anyway. I'll add a thing in to deduplicate anyway.
