### ISSUE TITLE
Direct file uploads to S3 from browser 

### ISSUE THREAD

**Issue by lpil** [CargoSense/ex_aws#114]
Hello!

I wish use presigned url to allow users to upload files directly to S3 from the browser. Can this library be used to do this?

I see [this](http://hexdocs.pm/ex_aws/ExAws.S3.Client.html#c:presigned_url/4) function exists, but with the minimal documentation and examples it's unclear if this is what is required for this task.

Cheers,
Louis

**Comment by benwilson512** [comment]
hey!

I'll be sure to work on the documentation. Yes that function should be sufficient. It will generate a complete url, and pasting that url in your browser does indeed start a download.

**Comment by lpil** [comment]
I'm after direct uploads to S3, not downloads. :)

**Comment by benwilson512** [comment]
My bad. I can't say I've looked into how that would work, but I will. I don't believe what we have will currently support this, but I have no idea how that'd work in either case.

**Comment by lpil** [comment]
Good to know. We could add a note to that function making it clearer that this is for downloads, perhaps.

I think with Elixir this is less of a vital feature since we can handle slow image upload requests in another thread so it doesn't block :)

**Comment by nicholaswyoung** [comment]
@benwilson512 I see `ExAws.S3.presigned_url/4` on `master`. Is this the only currently available method for generating presigned URLs?

**Comment by ericmj** [comment]
@lpil You can upload with a presigned URL. The signed URL will have the exact same permissions as the AWS user signing the URL, so if the user has permissions to upload files then the URL can be used to upload files.

**Comment by boydm** [comment]
I'm also trying to use ExAws.S3.presigned_url/4 to upload a file from the browser. Is there a way to add query parameters (partNum and uploadId are required) to both the query and the signature? Looking through the code, I don't see a way to get additional query parameters inserted.

If there isn't a way, then I would like to see an option added to the incoming config.

**Comment by benwilson512** [comment]
It would indeed appear that `presign_url` needs a bit of work to enable that. I'll try to look at it later this week. Please feel free to do a PR if you want to dive in!

**Comment by andshape** [comment]
This is also something i am interested in. I saw that @bryanjos got it working somehow using an older version of ex_aws (https://github.com/bryanjos/aws_auth/issues/21).
I've tried playing around with ExAws.S3.presigned_url/5 (when looking at the docs I couldn't see a version with four parameters https://hexdocs.pm/ex_aws/1.0.0-beta1/ExAws.S3.html#presigned_url/5). 
First parameter is a config. I assumed I could provide it with ExAws.Config.Defaults.get(:s3) like :
`ExAws.Config.Defaults.get(:s3) |> ExAws.S3.presigned_url(:post, "foo", "bar", [])`
But this doesn't work as the default config has map of all S3 hosts whereas "url_to_sign" (see https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/s3.ex) which is called by ExAws.S3.presigned_url/5 expects host to be a single string (like e.g. "us-east-1" I would assume). Is there a place where I can see an example of what the config map required by ExAws.S3.presigned_url/5 should look like?

**Comment by andshape** [comment]
Guessing as to the value of config I've tried the following
```
myconfig = %{scheme: "https://", host: "us-east-1"}
options = [expires_in: 99999, virtual_host: true] 
ExAws.S3.presigned_url(myconfig, :post, "my-bucket", "bar", options)
```

I get the following error: 
```
** (ArgumentError) argument error
    (crypto) :crypto.sha256_mac_nif(["AWS4", nil], "20160818", 32)
    (crypto) crypto.erl:1055: :crypto.sha256_mac/3
    (ex_aws) lib/ex_aws/auth.ex:96: ExAws.Auth.signing_key/3
    (ex_aws) lib/ex_aws/auth.ex:53: ExAws.Auth.signature/7
    (ex_aws) lib/ex_aws/auth.ex:32: ExAws.Auth.presigned_url/6
    (ex_aws) lib/ex_aws/s3.ex:785: ExAws.S3.presigned_url/5

```

I am probably missing some parameter in myconfig.

**Comment by benwilson512** [comment]
```elixir
ExAws.Config.new(:s3)
|> ExAws.S3.presigned_url("bucket", "path)
```

That should work ^

**Comment by boydm** [comment]
Submitted a pull request to add the optional query params to presigned_url. I am now successfully uploading multipart files directly from the browser using the resulting signed url.

**Comment by benwilson512** [comment]
This seems like its fixed.

**Comment by MikeAndrianov** [comment]
`presigned_url` needs http method as a second argument, so here is working solution: 
`ExAws.Config.new(:s3) |> ExAws.S3.presigned_url(:put, "bucket", "filename")`

**Comment by abitdodgy** [comment]
Is it possible to pass acl policy to the `presigned_url` function? I can't see a way. I want to give the uploaded file a "public-read" acl, for example.

**Comment by JonRowe** [comment]
I'm getting a signature mismatch when I try this, does anyone have a working snippet that produces a `curl`able url?

**Comment by DJTouchette** [comment]
+1 to the signature mismatch
