### ISSUE TITLE
Moving to newer version of ExDocs?

### ISSUE THREAD

**Issue by JustMikey** [CargoSense/ex_aws#118]
There is a newer version of `ex_docs` available and I believe there is only one breaking change from the version `0.7` used here (the changelog can be found [here](https://github.com/elixir-lang/ex_doc/blob/master/CHANGELOG.md)) so I wonder if we could bump the version of it?

**Comment by benwilson512** [comment]
Done: http://hexdocs.pm/ex_aws/0.4.16/

**Comment by JustMikey** [comment]
The link doesn't seem to work, it leads to the 404 page and there seems to be only 0.4.15 and 0.4.17 old-style versions on the hexdocs. It's either me being foolish and not understanding something or something went wrong there.

**Comment by benwilson512** [comment]
Ah sorry there was a bug in the 0.4.16 release so I pulled it right after
pushing. In any case all future releases are on the new doc UI

**Comment by JustMikey** [comment]
Oh okay, I apologize for bothering, thank you :)
