### ISSUE TITLE
Adding changelog?

### ISSUE THREAD

**Issue by JustMikey** [CargoSense/ex_aws#119]
I think it may make sense to add a changelog to the repository since the API is, as far as I understand, still a subject for a change (at least for S3) so it would be possible to track the changes, expecially the breaking ones

**Comment by benwilson512** [comment]
I've so far been using the Releases page to track changes, although I've gotten a bit lax about it with the last couple which have just been minor bug fixes. I'll make sure to do so with the latest release.
