### ISSUE TITLE
Bang version for delete_multiple_objects?

### ISSUE THREAD

**Issue by JustMikey** [CargoSense/ex_aws#121]
I wonder if there is some special reason for not having a bang version of the `delete_multiple_objects` function?

**Comment by benwilson512** [comment]
Hey there, apologies on the hideously long delay in responding. I'm working on a solution that avoids the crazy amount of duplicate functions required to handle the `!` functions and the config optional functions. You can read more about it here: https://github.com/CargoSense/ex_aws/issues/137

I'll not be adding additional functions until that's been done.
