### ISSUE TITLE
decoding nested data into a struct that contains a keyword list

### ISSUE THREAD

**Issue by thehosepipe** [CargoSense/ex_aws#125]
I am trying to decode nested structure that looks like the following

```
%{"batch_id" => %{"S" => "Batch_1"}, 
    "documents" => %{"M" => %{
          "doc1" => %{"S" => "a document"},
          "doc2" => %{"S" => "another document"}
 }}}
```

using a structure Batch defined as 
`defstruct batch_id: nil, documents: nil`

and `ExAws.Dynamo.Decoder.decode(as: Batch)`

will successfully create a structure for the first level, but unsurprisingly documents contains a map of its inner contents.

having spent a few hours reading through the code and unit tests I still can't work out how to define the batch such that the decoder knows to decode the inner documents into a keyword list. It looks like it should be possible but how to do it beats me.

Is this possible without adding custom logic into ExAws.Dynamo.Decodable? Just by defining the Batch struct differently to show what the inner list should be made of? If so any hints how?

Thanks

**Comment by benwilson512** [comment]
You need to define a custom implementation of the Decodeer protocol for your struct. There's no way that ExAws can know every possible internal representation, that's precisely what protocols are built for.

Here's an example from the tests: https://github.com/CargoSense/ex_aws/blob/master/test/support/user.ex#L5

**Comment by thehosepipe** [comment]
Thanks, appreciate the quick response!
