### ISSUE TITLE
What to do when the S3 bucket region is not us-east-1?

### ISSUE THREAD

**Issue by sashaafm** [CargoSense/ex_aws#126]
Certain operations do not work on regions other than us-east-1 (because of the need of a different authorization I think). What's the process to use these buckets when they're not in the us-east-1 region?

Example: DELETE Bucket

```{:http_error, 400,
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'</Message><Region>eu-central-1</Region><RequestId>43259BDCD14FBC31</RequestId><HostId>D9mDLmUKfBumxlU7ipYVsTPZcl1iToon4HFlm2/ASeBG8tmKfQg5K0yq7HK0e9xtCLLp4pgYPzo=</HostId></Error>"}}```

**Comment by benwilson512** [comment]
Can you gist your configuration? See this issue for a similar situation: https://github.com/CargoSense/ex_aws/issues/103#issuecomment-169356670

**Comment by sashaafm** [comment]
@benwilson512 I was actually doing what that issue says:

`config :ex_aws, :s3,
  scheme: "https://",
  host: "s3.amazonaws.com",
  region: "eu-central-1"`

**Comment by benwilson512** [comment]
Ah yeah that isn't the correct host for eu-central-1, per http://docs.aws.amazon.com/general/latest/gr/rande.html

Use `s3.eu-central-1.amazonaws.com`

**Comment by sashaafm** [comment]
Oh ok. Sorry, but I find AWS documentation so confusing. 

Also isn't there any way to get a bucket's region without getting auth for that region? :(

**Comment by debajit** [comment]
I still see this issue with ExAws 2.0.2 and ExAwsS3 2.0.0. I don't think this issue is resolved.


# Steps to Reproduce

- Create a bucket in the Frankfurt (eu-central-1) region
- Add some objects to the bucket
- Try to list the bucket contents by doing a 

  ```
  ExAws.S3.list_objects("my-bucket-name") |> ExAws.request!
  ```

# Expected Result

I should see the contents of the bucket

# Actual Results

The following error is seen:

```
** (ExAws.Error) ExAws Request Error!

{:error, {:http_error, 400, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'</Message><Region>eu-central-1</Region>

...

{"Server", "AmazonS3"}], status_code: 400}}}
```

**Comment by benwilson512** [comment]
Please use the forums, slack, or IRC for help.
