### ISSUE TITLE
ExAws.Kinesis.create_stream/1 Poison Error

### ISSUE THREAD

**Issue by pulltab** [CargoSense/ex_aws#128]
When creating a new stream on kinesis the following error is encountered:

```
ExAws.Kinesis.create_stream("my_stream")
** (Poison.SyntaxError) Unexpected end of input
    (poison) lib/poison/parser.ex:54: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (ex_aws) lib/ex_aws/kinesis/request.ex:20: ExAws.Kinesis.Request.parse/2
```

**Comment by benwilson512** [comment]
ah yeah create_stream returns an empty body which isn't valid JSON. I feel like it used to return something different. In any case, your stream should indeed be created, just a matter of parsing the return result correctly. Will fix.

**Comment by pulltab** [comment]
Awesome, thanks!
