### ISSUE TITLE
Support awscli configuration files in '.aws' folder

### ISSUE THREAD

**Issue by TattdCodeMonkey** [CargoSense/ex_aws#132]
# Proposal

The `awscli` uses the `~/.aws` folder to store configuration files. One of those being a `credentials` file that can have default and profiles sections. The file follows an ini type format:

```
[default]
aws_access_key_id = <access_key>
aws_secret_access_key = <super_secret_thing>

[bob]
aws_access_key_id = <access_key>
aws_secret_access_key = <super_secret_thing>
```

To support this in `ExAws` we could introduce a new config tuple similar to the `{:system, "KEY"}` that is currently supported. This could support the default or named profiles. Something like the following could be supported:

```elixir
#loads config values from the "default" section
config :ex_aws,
  access_key_id: [{:shared, "aws_access_key_id"}, :instance_role],
  secret_access_key: [{:shared, "aws_secret_access_key"}, :instance_role]
```
and 
```elixir
#loads from the named section
config :ex_aws,
  access_key_id: [{:shared, "bob", "aws_access_key_id"}, :instance_role],
  secret_access_key: [{:shared, "bob", "aws_secret_access_key"}, :instance_role]
```

## Implementation Details

- To read the config file we would add an optional dependency on [ConfigParser](https://hex.pm/packages/configparser_ex) and return nil if the module is not loaded at runtime.
- ~~We would also need to load the path to the file in a cross-platform friendly way. Check for `~/.aws/credentials` on OSX, Linux, Unix and `C:\Users\<USERNAME>\.aws\credentials` on Windows~~
- use `System.user_home |> Path.join(".aws") |> Path.join("credentials")` and check `File.exists?`

## Questions
- What should the atom be for this type? `:shared`, `:awscli` or something else?
- What should the format of the config object be? `.aws` has `credentials` and `config` files. So it could be something like: `{:awscli, <file>, <section>, <key>}` where file and section both have defaults?

Thoughts, comments, concerns?

**Comment by benwilson512** [comment]
Apologies for the delay. My primary concern here is the need to add an extra dependency. I wonder if there's a way to make the dependency nicely optional so that it's only used if you specify `{:shared` or something. I suppose if I simply marked it as an optional dependency, and then had just remote function calls to those modules inside my Config stuff I would be good to go.

**Comment by TattdCodeMonkey** [comment]
The way I tested it, was with an optional dependency. Then I did a
`Code.ensure_loaded?` call before using it. If it's not loaded give a
warning and return nil.

I have a rough implementation put together that works. And it's pretty
simple.

**Comment by TattdCodeMonkey** [comment]
This can be done with a separate module, going to go that route instead. It will allow the functionality to exists, but not add the complexity to `ExAws` directly.
