### ISSUE TITLE
Proposal: Pure / Impure breakup

### ISSUE THREAD

**Issue by benwilson512** [CargoSense/ex_aws#137]
Right now we have a problem. There are 2 orthogonal concerns that effect every function. For every function we want one version that returns an `{:ok, result} | {:error, reason}` tuple, and one version denoted with a `!` that raises on error and otherwise just returns the result. Also for every function we want the option to use a default configuration, and the option to specify a particular configuration.

This means that every function gets basically 4 variants. Using `S3.list_objects` as an example we have

```elixir
S3.list_objects("my-bucket") #=> {:ok, []}
S3.list_objects!("my-bucket") #=> []
S3.Impl.list_objects(config_overrides, "my-bucket") #=> {:ok, []}
S3.Impl.list_objects!(config_overrides, "my-bucket") #=> []
```

In addition to being just kinda sucky, these functions I think reflect a deeper problem. There's really 2 things going on here. There's the request building logic that maps a input into an AWS request, and then there are 4 modes of making that request. The current approach conflates these, and so we are forced to do these 4 modes for every request building function.

My current client approach basically tries to create an object out of a module. It ties a bunch of data (the configuration on that module) to a bunch of behaviour.

Here's the proposed alternative:
```elixir
S3.list_objects("my-bucket") |> ExAws.request #=> {:ok, []}
S3.list_objects("my-bucket") |> ExAws.request! #=> []
S3.list_objects("my-bucket") |> ExAws.request(config) #=> {:ok, []}
S3.list_objects("my-bucket") |> ExAws.request!(config) #=> []
```

I'm splitting up the pure mapping of input to some request struct from the actual impure mechanics of executing that a request on that struct. This will dramatically simplify the code. I only need one function to generate the data, and then 4 functions can serve to enable the 4 modes of making a request for EVERY request data struct.

Downsides: This introduces an extra function call that people need to add anywhere they currently have just one function call.

Upsides: By separating the pure from the impure it makes it wildly easier to use in all of the other use cases.

- No need to call the `Impl` modules in order to pass custom config in.
- You can put a function between the `list_objects` call and the `request` call to do any transformation of the data inside. This right now requires creating a whole new client module and overriding the `request` function.
- Gone is all the silly meta-programming required to generate the 4 versions of every function.
- It's a lot easier to see how we might batch requests, because an ordinary call like `list_objects` is just a datastructure. We can combine those together inside a Batch structure and then execute that.

Thoughts? @bruce @ericmj @adamkittelson

**Comment by benwilson512** [comment]
I should add that this makes it way easier to do stuff like have a `MyS3` module that always does some particular transformation on the data or configuration. Right now in order to use a `MyS3` module I have to meta-program in all of the functions. With this proposal you could just take a much more functional approach:

```elixir
defmodule MyS3 do
  def request(action_struct, config \\ custom_default_config()) do
    action_struct
    |> transform
    |> ExAws.request
  end
end

S3.list_objects("my-bucket") |> MyS3.request
```
No metaprogramming required, and it's also a lot more flexible.

**Comment by benwilson512** [comment]
Right so I looked through the docs again and we have
```
String and Binary type attributes must have lengths greater than zero
```

I think the right call here is to just make sure that empty strings like null are simply stripped out entirely from what's sent.

**Comment by ericmj** [comment]
This seems like a good approach, it's data structure driven which I strongly like.

Singular requests will be easy but I can imagine that it gets a bit more tricky when you need to make multiple requests and when when subsequent requests depends on previous ones, take `ExAws.S3.Client.stream_objects!/1` as an example. Do you have any ideas for solving this?

From where would `ExAws.request` pull the config by default now that we don't have a module that defines a default config?

**Comment by benwilson512** [comment]
Thanks for your feedback.

## Configuration

There are a few cases of configuration we need to worry about. The first is general configuration that is already placed on `:ex_aws` itself. This will naturally be what a bare `ExAws.request` uses. There is also request that is placed under a given service like

```
config :ex_aws, :s3,
  region: "us-west-1"
```

This too will simply be used by the default `ExAws`.

For people who had made custom modules that `use ExAws.S3.Client` or similar, the migration path is fairly easy there too. If they made a `MyS3` they just basically do

```
defmodule MyApp.MyS3 do
  def config_root, do: #whatever they had as their previous custom config

  def request(operation, config \\ config_root()) do
    ExAws.request(operation, config)
  end
end
```

## Streaming

This is a bit of a tougher question. Conceptually there are basically 3 parts to a streaming function. We'll use `list_objects` from S3 as the example. First you need the ordinary `list_objects` call. Then you need the configuration, and finally you need code which bundles those two together inside of an enumerable. Because the exact method of pagination varies by service and even by operation, I highly doubt that the enumerable bundling code can be generic.

Fortunately, we can still provide a pretty generic interface I think. Let me know what you think of this.

```elixir
"my-bucket"
|> S3.list_objects
|> ExAws.stream!
```

As part of the datastructure we return from an ordinary `S3.list_objects` function call we include something a key like `%{stream_builder: &anon_function/2}`. This anonymous function takes the operation struct as an argument, and also a config as an argument, and returns an enumerable.

The `ExAws.stream!` function is basically just
```elixir
def stream!(op, config \\ default_config())
def stream!(%{stream_builder: nil}, config), do: raise ArgumentError, "Operation #{foo} is not configured for streaming"
def stream!(%{stream_builder: fun} = op, config) do
  fun.(op, config)
end
```

I rather like this approach. Once again it keeps a nice separation of concerns between building the data required for an operation and how we want to consume the result. It also means we don't have yet another axis in our table up there for `stream` vs non stream functions.

Thoughts?

**Comment by benwilson512** [comment]
Thinking about this more, I may want to go as far as to have the `stream!` function pass a third argument to `fun` which would be the function to call to make an individual request. in `ExAws` it would just be `&request!/2` but for anyone looking to wrap a `stream!` call I want to give them the ability to use any wrapped `request!` function they've also made.

**Comment by benwilson512** [comment]
An update:

I've started implementing this in https://github.com/CargoSense/ex_aws/pull/165 and it's going very well.

I've defined a protocol: 

```elixir
defprotocol ExAws.Operation do
  def perform(operation, config)

  def stream!(operation, config)
end
```

Each function `S3.list_objects`, `Dynamo.create_table`, etc returns a struct for which there is an implementation of the `ExAws.Operation` protocol. These implementations basically resemble the Request modules that existed before, however many services are able to return common structs, which has simplified the number of places in which similar request logic must exist.

It also lets individual functions return something different if they want to be handled in a particular way. A good example is how `S3.delete_all_objects` works: https://github.com/CargoSense/ex_aws/pull/165/files#diff-886111751a5229ad66e5ae3aef100f66R73

**Comment by sashaafm** [comment]
Hey Ben! I like your proposed changes, delaying the configuration and choosing the mode at the last step seems to be a good idea. I can see it also being better for future changes or maintenance duties through a clearer separation of data building and request logic as distinctive phases of the whole operation.

> Here's the proposed alternative:
> 
> S3.list_objects("my-bucket") |> ExAws.request #=> {:ok, []}
> S3.list_objects("my-bucket") |> ExAws.request! #=> []
> S3.list_objects("my-bucket") |> ExAws.request(config) #=> {:ok, []}
> S3.list_objects("my-bucket") |> ExAws.request!(config) #=> []

Like in this example you provided it's easier to reason about and makes for a simpler interface in comparison to this:

> S3.list_objects("my-bucket") #=> {:ok, []}
> S3.list_objects!("my-bucket") #=> []
> S3.Impl.list_objects(config_overrides, "my-bucket") #=> {:ok, []}
> S3.Impl.list_objects!(config_overrides, "my-bucket") #=> []

I also find it better in the new alternative since it maps the actual API more closely and I believe that's one of the goals of a good API wrapper is to provide shortcuts to consume the actual API. Then if the user wants to transform that data somehow then that's the responsibility of another layer.

**Comment by sashaafm** [comment]
> Thinking about this more, I may want to go as far as to have the stream! function pass a third argument to fun which would be the function to call to make an individual request. in ExAws it would just be &request!/2 but for anyone looking to wrap a stream! call I want to give them the ability to use any wrapped request! function they've also made.

Can this new argument receive custom functions from the users then? Would it be useful in any way?
