### ISSUE TITLE
SQS The request signature we calculated does not match the signature you provided. windows/mac

### ISSUE THREAD

**Issue by nathanjohnson320** [CargoSense/ex_aws#138]
I'm using the same access/secret on my windows/mac/linux boxes and when I run it on linux any SQS commands execute properly but for some reason when I run on mac/windows I get the below error:

SignatureDoesNotMatch:The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method.

Is there a package that I need to install in order to get this to work on windows/mac?

**Comment by benwilson512** [comment]
If you do `ExAws.SQS.new` in `iex -S mix` does the config key look correct for you on windows? Make sure not to paste it here as it will have your secret key.

**Comment by nathanjohnson320** [comment]
Yes the access and secret keys are correct, do you think it could be an issue with the datetime? I know in the past I've had issues with time differences causing signature issues.

iex(3)> datetime = :calendar.universal_time
{{2016, 4, 11}, {16, 49, 13}}

**Comment by benwilson512** [comment]
Yeah if your system time is off that can cause it. The overall strategy for debugging stuff like this is roughly as follows. The request back from amazon will tell you what signature it expected you to send, as well as the canonical request you should have generated.
I would open your `deps/ex_aws/lib/ex_aws/auth.ex` and add an IO.inspect on https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/auth.ex#L85. Then `mix deps.compile ex_aws` and run the request again.

Compare the canonical request that AWS says you should have with the one that got inspected. You should be able to post both here unless the data itself is private in some way.

**Comment by nathanjohnson320** [comment]
These are the two responses

Expected: POST\n/https%3A//sqs.us-east-1.amazonaws.com/450254563905/test-queue\n\ncontent-type:application/x-www-form-urlencoded\nhost:sqs.us-east-1.amazonaws.com\nx-amz-date:20160411T170932Z\n\ncontent-type;host;x-amz-date\naae129685736031dee0cee7dbbe5319f51ba0ab336c3d32f8dddec55cd0072a0

Actual:      POST\n/https%3A/sqs.us-east-1.amazonaws.com/450254563905/test-queue\n\ncontent-type:application/x-www-form-urlencoded\nhost:sqs.us-east-1.amazonaws.com\nx-amz-date:20160411T170932Z\n\ncontent-type;host;x-amz-date\naae129685736031dee0cee7dbbe5319f51ba0ab336c3d32f8dddec55cd0072a0

It looks like there is an extra slash in front of the sqs for some reason

**Comment by benwilson512** [comment]
The actual one has `http:/sqs` with just one slash.

**Comment by nathanjohnson320** [comment]
Ah I know what the issue is, I'm putting the full URL into the queue_name parameter and that's why it's blowing up because it's looking for a non-url.

Thanks for helping out this is a really great package btw :+1:

**Comment by benwilson512** [comment]
Thanks! Glad we could get it sorted :)
