### ISSUE TITLE
Session Tokens as environment variable

### ISSUE THREAD

**Issue by nogates** [CargoSense/ex_aws#140]
Hello,

First, Thanks for creating and maintaining this project :-)

One of the alternatives that AWS offers to access it services is using SessionTokens. As you know, this type of authentication requires an extra header with the a temporal security token (https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/auth.ex#L36-L38). This is already implemented when the information is retrieved from the `instance_role` https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/config.ex#L57-L61, but it does not work when the tokens are present in the env.

In order to make this work, I guess it would be enough to add the `security_token` as part of the common config fields on https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/config.ex#L10, so it can be loaded as any other config option, but I wanted to check with you first before submitting a PR

related: http://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html

Thanks

**Comment by benwilson512** [comment]
Aren't these tokens only valid for 12 hours? If so, what good are they when used in a way that doesn't have a repeatable update process?

**Comment by nogates** [comment]
Hi @benwilson512. Thanks for replying so fast. I can think in several situations when you could use tokens that expire in less than 12 hours (for example, tailing a kinesis stream for debugging purposes), but I am actually using them in development. I could, of course, use different ways to do this, but I think that having a config option suits better and can be really usefull

**Comment by benwilson512** [comment]
Aight sounds good. Feel free to make a PR :) Your overall approach sounds good, we'll hash out details on the PR itself.

**Comment by benwilson512** [comment]
Completed
