### ISSUE TITLE
Amazon Signature V2

### ISSUE THREAD

**Issue by KaySackey** [CargoSense/ex_aws#143]
I apologize if this is documented somewhere, and I simply couldn't find it (I looked into https://github.com/cargosense/ex_aws/blob/master/lib/ex_aws/config/defaults.ex and generally searched the auth of the repository first).

Is there a way to sign requests via AWS signature v2? Most third party implementations of S3 don't support V4 yet. Riak CS, Ceph, Cloudian ... none of them support V4.

**Comment by benwilson512** [comment]
ExAws does not support V2 signing. All AWS services support V4 now so there wasn't much point. I would be open to a PR which added V2 support, but I am not planning on adding it myself.
