### ISSUE TITLE
Kinesis Firehose

### ISSUE THREAD

**Issue by cwc** [CargoSense/ex_aws#145]
The Firehose API appears to be separate from the Kinesis API. Is anyone working on an implementation? If not, I'm prepared to take it on myself, and would appreciate any insight, tips, potential gotchas, etc.

**Comment by cwc** [comment]
Got some work done here, would appreciate any comments:
https://github.com/CargoSense/ex_aws/compare/master...cwc:firehose

**Comment by benwilson512** [comment]
I'm impressed, please open a full PR.

**Comment by benwilson512** [comment]
Gonna close this in favor of the PR.
