### ISSUE TITLE
[error] ExAws: HTTP ERROR: :timeout

### ISSUE THREAD

**Issue by dlisage** [CargoSense/ex_aws#147]
I am getting this error `[error] ExAws: HTTP ERROR: :timeout` when I upload big image (> 1M). How do I fix the issue?

**Comment by rcoppolo** [comment]
I was running into the same issue. Increasing the timeout seemed to help (the default is 30 seconds[0]).

```
# my config.exe (in a phoenix project)
config :ex_aws, :httpoison_opts,
  recv_timeout: 60_000,
  hackney: [recv_timeout: 60_000, pool: false]
```

[0] https://github.com/CargoSense/ex_aws/blob/1b35baec9d992555510a3abf7ffd134a8837e7d1/lib/ex_aws/request/httpoison.ex#L24

**Comment by benwilson512** [comment]
Indeed, if your connection speed is not particularly fast and you're uploading a large file, there may be a need to increase the timeout.

For very large files, a multi part upload is going to be necessary.
