### ISSUE TITLE
ehostunreach error

### ISSUE THREAD

**Issue by beydogan** [CargoSense/ex_aws#149]
I'm getting the following error when I'm trying use this library with *arc_ecto* to upload files to s3.

```
 (CaseClauseError) no case clause matching: {:error, %{__exception__: true, id: nil, reason: :ehostunreach}}
            (ex_aws) lib/ex_aws/instance_meta.ex:5: ExAws.InstanceMeta.request/2
            (ex_aws) lib/ex_aws/instance_meta.ex:15: ExAws.InstanceMeta.security_credentials/1
            (ex_aws) lib/ex_aws/config/auth_cache.ex:37: ExAws.Config.AuthCache.refresh_config/2
            (ex_aws) lib/ex_aws/config/auth_cache.ex:27: ExAws.Config.AuthCache.handle_call/3
            (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
```

Its trying to send a request to `http://169.254.169.254`

But that IP is not reachable.

```
➜  ~ curl http://169.254.169.254/latest/meta-data/
curl: (7) Failed to connect to 169.254.169.254 port 80: No route to host
```

How can I solve this?

**Comment by benwilson512** [comment]
This is happening because the default credential retrieval config includes an attempt to retrieve config from the AWS instance IP if the secret key and so on isn't available from environment variables.

What this means in your case is that your environment variables aren't setup correctly. Do you see your keys when you do

```elixir
System.get_env("AWS_ACCESS_KEY_ID")
System.get_env("AWS_SECRET_ACCESS_KEY")
```

**Comment by hopewise** [comment]
I got the same error, yes I get correct values when:

    System.get_env("AWS_ACCESS_KEY_ID")
    System.get_env("AWS_SECRET_ACCESS_KEY")

I am trying to call store at:

> defmodule App.LocationController do
>   use ExAws.Dynamo.Client
>   alias ExAws.Dynamo
> 
>   def config_root do
>       Application.get_all_env(:ex_aws)
>   end
> 
>   def store do
> 
>     location = %App.Location{lot: 1.57, lang: 1.234, user_id: 23, time: 123847463882}
>     # Save the user
>     Dynamo.put_item("Locations", location)
> 
>   end
> 
> 
> end
> 
>

**Comment by adrifmonte** [comment]
Follow these steps:

http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

You may also need to export them as system environment variables.

**Comment by benwilson512** [comment]
@adrifmonte I'm unclear why you're commenting here some 18 months later.

**Comment by adrifmonte** [comment]
@benwilson512 I just added some useful resources in case someone faces the same issue, like me.

**Comment by somoza** [comment]
> 

In addition to this:

```
export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
export AWS_DEFAULT_REGION=us-west-2
```
