### ISSUE TITLE
put_bucket_* functions have no local return according to dialyzer

### ISSUE THREAD

**Issue by KronicDeth** [CargoSense/ex_aws#158]
`mix dialyze` (using https://github.com/fishcakez/dialyze) on a module that has called `use ExAws.Client, otp_app: :my_app`

```
defmodule MyApp.S3 do
  use ExAws.Client, otp_app: :my_app
end
```

warns that all the `put_bucket_*` function have no local return.  This usually means that dialyzer thinks the function will cause an exception due to the incoming types not matching the allowed patterns. 

```
lib/my_app/s3.ex:2: The inferred type for the 4th argument of post_object_restore/4 ([{atom(),_}]) is not a supertype of pos_integer(), which is expected type for this argument in the callback of the 'Elixir.ExAws.S3.Client' behaviour

lib/my_app/s3.ex:2: Function put_bucket_lifecycle/2 has no local return

lib/my_app/s3.ex:2: Function put_bucket_logging/2 has no local return

lib/my_app/s3.ex:2: Function put_bucket_notification/2 has no local return

lib/my_app/s3.ex:2: Function put_bucket_replication/2 has no local return

lib/my_app/s3.ex:2: Function put_bucket_request_payment/2 has no local return

lib/my_app/s3.ex:2: Function put_bucket_tagging/2 has no local return

lib/my_app/s3.ex:2: Function put_bucket_versioning/2 has no local return

lib/my_app/s3.ex:2: Function put_bucket_website/2 has no local return
```

For my past experience fixing these errors in my own code it could be that `The inferred type for the 4th argument of post_object_restore/4 ([{atom(),_}]) is not a supertype of pos_integer(), which is expected type for this argument in the callback of the 'Elixir.ExAws.S3.Client' behaviour` is causing dialyzer to think all the other functions will fail because `post_object_restore/4` will fail.

I care, because it impacts having a clean `mix dialyze` output, which I want because `mix dialyze` has exit status `0` when there are no warnings, so I can use in CI then to check for errors.

My current work-around is to suppress dialyzer (see http://erlang.org/doc/man/dialyzer.html "Requesting or Suppressing Warnings in Source Files") on all those functions:

```
defmodule MyApp.S3 do
  use ExAws.Client, otp_app: :my_app

  @dialyzer {:no_return,
             put_bucket_lifecycle: 2,
             put_bucket_logging: 2,
             put_bucket_notification: 2,
             put_bucket_replication: 2,
             put_bucket_request_payment: 2,
             put_bucket_tagging: 2,
             put_bucket_versioning: 2,
             put_bucket_website: 2
            }
  @dialyzer {:no_behaviours, post_object_restore: 4}
end
```

Any fix for these errors, should fix the type specs and or function, not just suppress the errors.  I just show my work-around here for anyone else that needs a clean `mix dialyze` output before a PR is ready.

**Comment by benwilson512** [comment]
Interesting thank you, I will definitely take a look into this :)

**Comment by benwilson512** [comment]
Hey there, This is gonna get simplified a lot in the upcoming #165 because there's a lot less meta-programming and it'll be a lot simpler to follow the code path. I'll check this again after that's merged in.

**Comment by benwilson512** [comment]
That branch fixes this.
