### ISSUE TITLE
How to put_object in S3 and set the permission 

### ISSUE THREAD

**Issue by badoet** [CargoSense/ex_aws#162]
I want to set the permission for Everyone for open/download when i put the object for S3.
Is there a way to do this currently?

thank you

**Comment by ericmj** [comment]
Yes. If you follow the typespecs for options down from https://hexdocs.pm/ex_aws/ExAws.S3.Client.html#c:put_object/3 you will find `acl: :public_read`. Pass that to the `put_object` function.

**Comment by benwilson512** [comment]
Also consider setting a policy on the bucket itself, which can have rules that apply to all keys in the bucket.
