### ISSUE TITLE
how to capture ex aws error

### ISSUE THREAD

**Issue by badoet** [CargoSense/ex_aws#170]
im using ExAws.S3.Client to put_object to my S3 bucket in bulk.
but sometime i realize the file is not generated.
i foresee that there is an error in the process that i did not catch that is causing this.

Im trying to catch all errors during the uploading process and log it so i can just manually process the error files later. 
So i tested with shutting my internet connection during the batch upload execution and i cant catch the error in my try catch block.
my error log print this: 
[error] ExAws: HTTP ERROR: :timeout
[error] ExAws: HTTP ERROR: :nxdomain

but i did not capture this on my try catch.
help?

**Comment by badoet** [comment]
ah i realize it will automatically retry for 10 times before giving up and throw error

**Comment by benwilson512** [comment]
Yup yeah as you're seeing this is just log output from one attempt. Do note that if you use `put_object` you will get a `{:error, reason}` tuple as a result and so you won't need to use `try`.
