### ISSUE TITLE
ExAws.S3.put_object with a plus sign in the object name results in invalid signature

### ISSUE THREAD

**Issue by kommen** [CargoSense/ex_aws#176]
When uploading objects with `ExAws.S3.put_object` which have a + sign in the object name, the put fails with an `SignatureDoesNotMatch` error.

Easily reproducible with `ExAws.S3.put_object("test-bucket", "tes+t.tar.gz", "foobar")`

**Comment by benwilson512** [comment]
hm I swear I dealt with this before but I can confirm this is an issue. Will push a fix later today.

**Comment by benwilson512** [comment]
This is super confusing. In the canonical request ExAws generates
```
/test-bucket/tes%2Bt.tar.gz
```
which is the correct % encoding for `+`

AWS however wants
```
/test-bucket/tes%20t.tar.gz
```
which is usually what you do for spaces.

**Comment by javiercr** [comment]
We have had the same problem with this filename:
`Marbled Stripe  - lagoon.jpg`
(notice the double space before the dash).

**Comment by javiercr** [comment]
Ok, actually our scenario seems more similar to #113

**Comment by kommen** [comment]
@benwilson512 thanks!

**Comment by benwilson512** [comment]
@javiercr your issue should be fixed in master as well.

I'll be doing a beta1 release here shortly that will fix this issue.

If you aren't on the beta already, please see the top of the readme to be aware of the changes.

THanks!
