### ISSUE TITLE
Default HTTP library security concerns.

### ISSUE THREAD

**Issue by heri16** [CargoSense/ex_aws#179]
The TLS implementation used to access AWS endpoints need to verify that the certificates are valid on the domain. Check out this talk during ElixirConf.eu 2016

https://youtu.be/r0DuAse9tK8

**Comment by benwilson512** [comment]
Can you elaborate? ExAws hands off to hackney, httpoison, httpotion or really any other HTTP library you like to make the actual HTTP requests.

**Comment by heri16** [comment]
Hackney does verification of valid certificate identity, and so does httpoison because it is based on hackney. Httpotion does not verify valid certificate identity that means that any certificate presented by the server is accepted, even if it is the wrong domain, which opens up to man-in-the-middle attacks. My apologies I was testing with httpotion. We will switch http library since there seems to is no way around this when ExAWS hands off to httpotion. Maybe the README should come with a warning.

Also, eveasdropping attacks are very common these days by foreign government institutions against popular services like AWS API endpoints, so maybe there can be a suggestion in the ExAWS README to configure and limit the ciphers in the underlying http library (allow only the strong ones actually used by AWS endpoints to prevent downgrade attacks). A simple config.exs example would suffice. The problem is I am not sure how custom config can be specified that applies only when ExAWS is calling httpoison or hackney.

**Comment by benwilson512** [comment]
The HTTP library is completely configurable. Moreover you can always wrap any library you choose including Hackney or HTTPoison. https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/request/http_client.ex Goes through an example.

If you have an example of how to use these or any other http library safely I would be happy to change the defaults. I just want to emphasize that I wrote ExAws in such a way that the choice of HTTP library is entirely configurable.

**Comment by heri16** [comment]
Referring to http://coderstocks.blogspot.co.id/2016/01/sqs-throughput-over-https-with-elixir.html

Is this line expected to work?
`config :ex_aws, :httpoison_opts`

**Comment by benwilson512** [comment]
It does, although again that isn't your only option. You can create your own module with a `def request` function that goes on to call any http library with any configuration you like.

**Comment by benwilson512** [comment]
https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/request/httpoison.ex#L34 shows how it works. It isn't anything special. That module is a particular adapter I wrote to use HTTPoison but one could be created in anyone's project to integrate with any HTTP library.

If you have a recommended route for me to take I'm happy to do so. I would also recommend addressing the HTTP libraries themselves with your concerns.

**Comment by heri16** [comment]
I have addressed my concerns to hackney, but of course because every server in the Internet is different, at best they can only provide defaults that work for most servers according to SSL Labs. https://github.com/benoitc/hackney/issues/329

Defaults can never be secure. Our goal here is to ensure the ex_aws tunes the right parameters to work securely for AWS API endpoints, because unlike the rest of the Internet, AWS API endpoints already use the latest ciphersuites. 

I will do some testing with  and report back.

**Comment by benwilson512** [comment]
Sounds good, I'm gonna close this for now because there isn't much here yet by way of actionable problems or solutions. Feel free to re-open when you have additional data. I look forward to what you come up with!
