### ISSUE TITLE
How to deal with responses?

### ISSUE THREAD

**Issue by heri16** [CargoSense/ex_aws#180]
For the use-case of list_buckets, how can we handle to response to extract the list of buckets?

**Comment by heri16** [comment]
Do we call functions in ExAws.S3.Parsers directly?
What about for ExAws.SQS.Parsers? Seems to be missing.

**Comment by sashaafm** [comment]
Hello @heri16, parsing responses is not ex_aws responsibility I believe. S3 uses JSON if I'm not mistaken, for that you can use the Poison library for JSON parsing. For XML parsing I've used Friendly which is okayish.

**Comment by heri16** [comment]
The README mentions that Poison and SweetXML are dependencies. Means that
these libraries, is used internally inside ex_aws to do parsing. Otherwise
they should not be dependencies. Am I mistaken?

**Comment by benwilson512** [comment]
Hey there!

At the moment there are only a few functions that have built in parsing of responses. There are plenty of others that could use a parser, but one has not been written yet. Some responses it doesn't make sense to automatically parse. For example `get_object` is just about returning whatever blob is at the given S3 key.

Any service that returns JSON (DynamoDB, Kinesis, etc) is automatically parsed.

For list_buckets specifically it should automatically be parsed if you have sweet_xml listed as a dependency. Is that not happening for you? What version of ExAws are you using?

**Comment by kenny-evitt** [comment]
@benwilson512 I just ran into this issue. The docs are still unclear that `:sweet_xml` is a strict dependency for `ExAws.S3.list_objects`. Are you all open to some changes to the README and the `ExAws` module docs more explicitly mentioning this?

Or is there some way to use an alternate parser? Is the AWS S3 list objects request *definitely* XML too?
