### ISSUE TITLE
Set timeout for individual services or requests.

### ISSUE THREAD

**Issue by heri16** [CargoSense/ex_aws#182]
Services like SQS require a long timeout for long polling.

Neither of the below will work:
``` elixir
ExAws.SQS.receive_message("frestive-cps-sync-rene-3001", wait_time_seconds: 20) |> ExAws.request(httpoison_opts: [recv_timeout: 30_000])
```

``` elixir
config :ex_aws,
  region: "ap-southeast-1",
  sqs: [
      httpoison_opts: [
        recv_timeout: 30_000
      ]
    ]
```

**Comment by heri16** [comment]
Is there a way to set this only for SQS receive_message request without affecting other services like list_queues and list_buckets?

**Comment by benwilson512** [comment]
Hey there. There is not a good way to do this at the moment, and I do see why it would be valuable for SQS. Let me take a look here and see fi there's a good way to make this happen easily.

**Comment by heri16** [comment]
Thanks! ^_^

**Comment by benwilson512** [comment]
You can now
```
ExAws.SQS.receive_message("frestive-cps-sync-rene-3001", wait_time_seconds: 20) |> ExAws.request(http_opts: [recv_timeout: 30_000])
```
