### ISSUE TITLE
Generate multiple S3 pre-signed download url with one request

### ISSUE THREAD

**Issue by lpil** [CargoSense/ex_aws#183]
I wish to be able to generate multiple pre-signed S3 download urls with one API request. Is there a mechanism for doing this with this library?

edit: Now I look it seems that this function might not hit the API at all. Is this correct?

**Comment by ericmj** [comment]
That's correct. URLs are created locally, they will have the same permissions as the AWS account singing them.

**Comment by lpil** [comment]
Great. Thank you.
