### ISSUE TITLE
Support for SES

### ISSUE THREAD

**Issue by taylorbrooks** [CargoSense/ex_aws#184]
I would love to see support for SES.

I'm mainly opening this as a placeholder, in case anyone else is planning on contributing to it.

Otherwise, I'll start cracking on a client according to [CONTRIBUTING.md](https://github.com/CargoSense/ex_aws/blob/master/CONTRIBUTING.md).

**Comment by benwilson512** [comment]
Hey there!

Apologies on the late reply. I need to update Contributing.MD in light of the major changes that have happened with the 1.0 beta. For now I would recommend looking at one of the existing service implementations if you'd like to contribute.

SES Support would be awesome, I've been meaning to start on it but haven't yet. Gonna close this for now, but please feel free to open a PR.
