### ISSUE TITLE
DynamoDb HTTP ERROR

### ISSUE THREAD

**Issue by gwincr11** [CargoSense/ex_aws#190]
Hello,

Thanks for this great library, I am trying to set it up with DynamoDb. I already have a table and I am trying to configure a Phoenix app to query it. I am pretty new to Elixir/Phoenix and I am sure this is likely a noob issue :).

When I execute my query:
```elixir
alias ExAws.Dynamo
query = Dynamo.query("some table",
KeyConditionExpression: "id = :id AND start_time = :time",
ExpressionAttributeValues: %{":id" => %{"N" => 7}, ":time" => %{"N" => 1464922247}})
ExAws.request query
```

I am getting an error:
```
[warn] ExAws: HTTP ERROR: {:noproc, {:gen_server, :call, [:hackney_manager, {:new_request, #PID<0.262.0>, #Reference<0.0.4.146>, {:client, :undefined, {:metrics_ng, :metrics_dummy}, :hackney_tcp_transport, 'dynamodb.us-east-1.amazonaws.com', 80, "dynamodb.us-east-1.amazonaws.com", [recv_timeout: 30000, recv_timeout: 30000], nil, nil, nil, true, :hackney_pool, 30000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, ...}}, :infinity]}}
```

I have this in my dev.exs file:
```
config :ex_aws,
  access_key_id: "A...",
  secret_access_key: "i+...",
  region: "us-east-1"

config :ex_aws, :dynamodb,
  scheme: "https://",
  region: "us-east-1"
```

Any help is appreciated.

Cory

**Comment by benwilson512** [comment]
Hey there!

You need to add `:httpoison` to your list of applications in your mix.exs file. HTTPoison relies on `:hackney`, which starts a pool of processed used to make HTTP requests. If you try to make a request without that application already started, you get that error.

I do believe the applications list is mentioned in the readme.

Feel free to create an issue for any further issues you run into!

**Comment by gwincr11** [comment]
Thanks that worked! Sorry I missed that in the docs.
