### ISSUE TITLE
Stream large file uploads?

### ISSUE THREAD

**Issue by madshargreave** [CargoSense/ex_aws#191]
Hi

I have a backup script that `pg_dumps` my database every hour and uploads it the S3. Problem is that I am now running into memory problems as my DB approaches 150MB in size. The Elixir/erlang process crashes and complains about not being able to allocate enough memory.

Is there a way to stream the backup to S3, instead of keeping the who DB string in-memory?

```
def start do
    backup = %BackupRequest{}

    backup
    |> dump_database
    |> upload_to_s3
  end

  defp dump_database(%BackupRequest{} = backup) do
    command = "pg_dump"
    args = [@database]
    {data, 0} = System.cmd command, args
    %{backup | data: data, status: "dumped"}
  end

  defp upload_to_s3(%BackupRequest{data: data} = backup) do
    key = get_s3_key
    ExAws.S3.put_object!(@bucket, key, data)
  end
```

**Comment by benwilson512** [comment]
Hey!

The way to do this is to do a multi-part upload. You'll want to read a chunk of the file, upload that one part via https://hexdocs.pm/ex_aws/1.0.0-beta1/ExAws.S3.html#upload_part/6 and so forth.

I'm actually right in the middle of building some utilities to manage that for you, so you'll just have a single function to call. I should be able to push out something today, so stay tuned!

**Comment by madshargreave** [comment]
Wow awesome, exciting! 

Much appreciated

**Comment by madshargreave** [comment]
In the meantime, I've tried to do something like below (streaming the output of pg_dump directly to S3), but I run into trouble as S3 wants each chunk to be a minimum of 5mb of size. Any suggestions on how to break up the stream into 5mb chunks?

```
    Logger.info "*** Dumping database ***"
    command = "pg_dump"
    args = [@database]
    key  = get_s3_key

    {:ok, %{body: body}} = ExAws.S3.initiate_multipart_upload(@bucket, key)
    upload_id = Regex.run(~r/<UploadId>(.*?)<\/UploadId>/, body) |> List.last

    opts = [out: :stream]
    proc = %Proc{out: outstream} = Porcelain.spawn(command, args, opts)


    parts =
      outstream
      |> Stream.with_index(1)
      |> Enum.map(fn {chunk, index} ->
        IO.inspect "#{index} Uploading chunk..."
        {:ok, result}  = ExAws.S3.upload_part(@bucket, key, upload_id, index, chunk)
        {_, etag} = result[:headers] |> Enum.find(fn {header, value} -> header == "ETag" end)
        IO.inspect etag

        {index, etag}
      end)

    ExAws.S3.complete_multipart_upload(@bucket, key, upload_id, parts)
```

**Comment by benwilson512** [comment]
Ah that's slightly harder. I can tell you that the initial upload support will be built around files themselves. What that means in your case is that you should write the pg_dump to a temporary file, and then use http://erlang.org/doc/man/file.html#pread-3 to get chunks out of the file. That's what the uploader will use internally.

**Comment by benwilson512** [comment]
This has been handled by https://hexdocs.pm/ex_aws/1.0.0-rc.1/ExAws.S3.html#upload/4

**Comment by ludwikbukowski** [comment]
if you spawn concurrent processes that upload the parts it still allocates whole memory... Can we make it configurable so that parts are uploaded sequentially ?

**Comment by ericmj** [comment]
Set `max_conconcurrency: 1`. https://hexdocs.pm/ex_aws_s3/ExAws.S3.html#upload/4

**Comment by ludwikbukowski** [comment]
great, thank you.
