### ISSUE TITLE
S3 upload ExAws: HTTP ERROR: :closed

### ISSUE THREAD

**Issue by jakubrohleder** [CargoSense/ex_aws#194]
I'm using this library for coping photos from one server to S3. After few uploads i keep receiving error: `[error] ExAws: HTTP ERROR: :closed`. What is the reason of this error?

**Comment by benwilson512** [comment]
Hey! Can you talk about what you're doing a little more?

- HTTP library?
- What size are these files?
- Once this happening does it happen every time or just sometimes?

Thanks!

**Comment by jakubrohleder** [comment]
@benwilson512 thanks for the quick answer, I rethinked my solution and found probable source of an error - my file names had been base64 encoded, what led to characters unpermitted by AWS. 

After changing to base16 everything works fine.
