### ISSUE TITLE
Module HTTPoison not available

### ISSUE THREAD

**Issue by choiway** [CargoSense/ex_aws#197]
I'm running 1.0.0-beta1 and trying to use sqs but I keep getting the following error:

`== Compilation error on file lib/test_app.ex ==
** (UndefinedFunctionError) function HTTPoison.request/5 is undefined (module HTTPoison is not available)`

Does HTTPoison need to be installed? The Readme suggests that you do not need to have HTTPoison installed. After I install HTTPoison, I get the follow warning:

` [warn]  ExAws: HTTP ERROR: {:noproc, {:gen_server, :call, [:hackney_manager, {:new_request, #PID<0.126.0>, ...`

I have hackney and HTTPoison included in `applications` as well.

**Comment by benwilson512** [comment]
Hey!

The readme on github reflects the current state of the master branch which uses hackney and not httpoison. The 1.0.0-beta1 release still uses httpoison by default. https://hexdocs.pm/ex_aws/1.0.0-beta1/ExAws.html contains the documentation and instructions for the 1.0.0-beta1 release.

I will be doing a beta2 release soon.

**Comment by choiway** [comment]
Thanks for the quick feedback, Ben! I reverted back to Httpoison but I'm still getting the following error: 

`11:36:15.828 [warn]  ExAws: HTTP ERROR: {:noproc, {:gen_server, :call, [:hackney_manager,...`

In my mix.exs I have applications configured like so:

`  def application do
    [applications: [:ex_aws, :httpoison, :poison]]
  end`

And here's the command I'm trying to run:

`ExAws.SQS.list_queues() |> ExAws.request`

I feel like I'm missing something obvious here. Thanks again for the help!

**Comment by benwilson512** [comment]
Did you add `:httpoison` to your applications list in the mix.exs file?

**Comment by choiway** [comment]
I think so. It looks like this: 

`def application do [applications: [:ex_aws, :httpoison, :poison]] end`

**Comment by benwilson512** [comment]
Are you in some kind of custom mix task or other scenario where your application may not be started?

**Comment by benwilson512** [comment]
Can you put this code up somewhere and include the command you're running?

**Comment by choiway** [comment]
I put it here: 
https://github.com/choiway/test-sqs

This is the piece of code I'm trying to run: 
https://github.com/choiway/test-sqs/blob/master/lib/test_sqs.ex

**Comment by benwilson512** [comment]
Oh, why are you trying to run that in a module body at compile time?

**Comment by choiway** [comment]
ummmm....because I don't know any better? I'm trying to figure out how it works so I thought, I guess incorrectly, that I could run that command like that.

**Comment by benwilson512** [comment]
Module bodies are run at compile time as part of the module complication process. Your application and its dependencies have not been started at that point.

You may want to work through the mix getting started guides: http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html

**Comment by choiway** [comment]
I see...Thanks for your help and patience!

**Comment by simonh1000** [comment]
I have a similar issue, using HTTPoison as part of an umbrella app, where HTTPoison is used in a child app. I have 
```
def application do
    [applications: [:logger, :httpoison]]
  end
```
in the child, but `** (HTTPoison.Error) {:noproc, {:gen_server, :call, [:hackney_manager, {:new_request, #PID<0.569.0>, #Reference<0.0.3.2463>, {:client, :undefined, {:metrics_ng, :metrics_dummy}, :hackney_tcp_transport, 'dev-epace.....`
