### ISSUE TITLE
Problem retrieving structure from DynamoDB

### ISSUE THREAD

**Issue by fremontmj** [CargoSense/ex_aws#201]
I'm using v1.0.0-beta1, as retrieved using hex.pm.  I'm trying to (nearly exactly) replicate the example given in the docs.  I have:

defmodule User do
  @derive [ExAws.Dynamo.Encodable]
  defstruct [:facebookID, :email, :name, :age, :admin]
end

I have a table with facebookID as the key.

In iex -S mix <my project> I do this:

user = %User{email: "bubba@foo.com", name: "Bubba", age: 23, admin: false, facebookID: "1234567"}
alias ExAws.Dynamo
Dynamo.put_item("DEV-players", user) |> ExAws.request!
Dynamo.get_item("DEV-players", %{facebookID: user.facebookID}) |> ExAws.request! |> Dynamo.Decoder.decode(as: User)

this returns:
%User{admin: nil, age: nil, email: nil, facebookID: nil, name: nil}

 Dynamo.get_item("DEV-players", %{facebookID: user.facebookID}) |> ExAws.request!       returns
%{"Item" => %{"admin" => %{"BOOL" => false}, "age" => %{"N" => "23"},
    "email" => %{"S" => "bubba@foo.com"}, "facebookID" => %{"S" => "1234567"},
    "name" => %{"S" => "Bubba"}}}

I seem to be doing something wrong, but I can't see it!

Thanks much!

**Comment by schummjm** [comment]
I'm having the same issue.  Were you able to solve?

**Comment by fremontmj** [comment]
I got distracted by some other tasks I’m doing, so I haven’t.  I expect to get back to it in a few weeks, and if you haven’t already solved it, I’ll try again!

**Comment by benwilson512** [comment]
So this is an issue with the documentation. Notice how the outermost key of
```elixir
%{"Item" => %{"admin" => %{"BOOL" => false}, "age" => %{"N" => "23"},
"email" => %{"S" => "bubba@foo.com"}, "facebookID" => %{"S" => "1234567"},
"name" => %{"S" => "Bubba"}}}
```
is "Item" ? If you get its value and decode it as a user, you're fine IE:

```elixir
Dynamo.get_item("DEV-players", %{facebookID: user.facebookID})
|> ExAws.request!
|> Map.fetch!("Item")
|> Dynamo.Decoder.decode(as: User)
```

Previously `get_item!` would do this for you, but in the switch to the beta that capability was lost.

I think I'm gonna just make the `Decoder.decode` function automatically  pull out values from `"item"` maps.

**Comment by benwilson512** [comment]
Hm unfortunately that approach won't work because if you pass in a struct that has an `:"Item"` key in it then decoder won't know the difference.

**Comment by fremontmj** [comment]
Thanks!

**Comment by benwilson512** [comment]
I think the best bet here is to have a `Dynamo.decode_item` helper function. This will be able to pattern match on `%{"item"` and pull it out. The flow would then be:
```
Dynamo.get_item("DEV-players", %{facebookID: user.facebookID})
|> ExAws.request!
|> Dynamo.decode_item(as: User)
```

**Comment by benwilson512** [comment]
This now exists in master.
