### ISSUE TITLE
Dynamo.batch_write_item generates invalid DeleteItem syntax

### ISSUE THREAD

**Issue by kyleaa** [CargoSense/ex_aws#209]
Using Dynamo.batch_write_item to attempt to delete items generates a request item in the format `%{"DeleteRequest" => %{"Key" => %{"S" => "api_key1"}}}`. This errors with the following message:
```
{:error, {:http_error, 400, "{\"__type\":\"com.amazon.coral.service#SerializationException\",\"Message\":\"Expected null\"}"}}
```

Per the [API docs ](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html) this should be formatted as 
`%{"DeleteRequest" => %{"Key" => %{ "name_of_key" => %{"S" => "api_key1"}}}}`. We also need to be able to supply all key values in the event of a composite primary key.

**Comment by benwilson512** [comment]
Fixed in master.
