### ISSUE TITLE
Signature calculation error for non standard port

### ISSUE THREAD

**Issue by krishnasrinivas** [CargoSense/ex_aws#213]
These are the headers sent by ex_aws for an S3 server listening on port 9000:
(here using `nc` instead of S3 server to show the header dump)
```
$ nc -l 9000
GET / HTTP/1.1
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=SXO8VW2OFKKP2OG7AC85/20160909/us-east-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=c346a88db16082f1bc6a937045c09f3501fafb4c21407f47e09b925fc8cdd758
User-Agent: hackney/1.6.1
x-amz-date: 20160909T075815Z
Host: 127.0.0.1:9000
content-length: 0
```

Note that `Host` header includes port 9000

but for the signature calculation on the client side, this is the canonical request it uses to calculate signature:

in auth.ex I do:
```
    request = build_canonical_request(http_method, url, headers, body)                 
    IO.puts(request)        
```

canonical request:
```
GET
/

content-length:0
host:127.0.0.1
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20160909T075849Z

content-length;host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Note that `host:127.0.0.1` does not include the port here causing signature mismatch.

This was found during debugging this issue; https://github.com/minio/minio/issues/2632

**Comment by benwilson512** [comment]
Hey!

Can you you try against master?

**Comment by krishnasrinivas** [comment]
works now, thanks.

**Comment by benwilson512** [comment]
Awesome, i'll push a release soon!
