### ISSUE TITLE
MaxNumberOfMessages does not work

### ISSUE THREAD

**Issue by dobryakov** [CargoSense/ex_aws#221]
```
ExAws.SQS.receive_message(queue_name, attribute_names: :all, max_number_of_messages: 5, wait_time_seconds: 20) |> ExAws.request

[debug] Request URL: "https://sqs.us-east-1.amazonaws.com/development--XaxXGlwnXkW5AOf2tX4Jg-postman"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=SOMETHING/20160920/us-east-1/sqs/aws4_request,SignedHeaders=content-type;host;x-amz-date,Signature=SOMETHING"}, {"host", "sqs.us-east-1.amazonaws.com"}, {"x-amz-date", "20160920T145810Z"}, {"content-type", "application/x-www-form-urlencoded"}]
[debug] Request BODY: "Action=ReceiveMessage&AttributeName.1=All&MaxNumberOfMessages=5&WaitTimeSeconds=20"

`<?xml version=\"1.0\"?><ReceiveMessageResponse xmlns=\"http://queue.amazonaws.com/doc/2012-11-05/\"><ReceiveMessageResult><Message><Body>test body 2</Body><MD5OfBody>65670561ce7ea8c4c951b26b9abe0caf</MD5OfBody><ReceiptHandle>AQEBbyqJQnc08P8BlBI/ufpBTPxELQMrwOlwUEOODBUxBQ+qyXV/7qh2HfphQiUvKxj48rwwQ/T1QfQhDpArV6RwKfVZZWNd4estU5098x5oOIJsHouS/zPxOBxmP8emxlQ/jHduDnA60QLrXeu9CVjeKe119GSjFxVLZO8TX0Y5xb0id04HEp+LRV7KarcsA34tu+JLN6G1J39tGKG5gIaHwuyM8gStfE5AvKIvJBMoRrWsnD+j0oz1tghc+h+kIEKPU0BoLx9arSaXUKBQNtPksLIPksGT7Ko1BE/Wtba4SNnTxvUht0xjTxlo5LH9Brx5W232d4DJq2qP6XWKfJWMmByMSH7O1BSr5eA0azlFajWRRelG9bt7vyZ1dgml6rj07VkttjCOaYKTqU6BjW2KzeDfmt4NIjLUVAsySTcsJVY=</ReceiptHandle><Attribute><Name>SenderId</Name><Value>221792628809</Value></Attribute><Attribute><Name>ApproximateFirstReceiveTimestamp</Name><Value>1474377792795</Value></Attribute><Attribute><Name>ApproximateReceiveCount</Name><Value>6</Value></Attribute><Attribute><Name>SentTimestamp</Name><Value>1474377792795</Value></Attribute><MessageId>8080ac63-45f3-41b3-9f88-b908d71f4312</MessageId></Message></ReceiveMessageResult><ResponseMetadata><RequestId>a3748d5a-9117-5ec3-8cf5-dd01c1d5c450</RequestId></ResponseMetadata></ReceiveMessageResponse>`
```

Why I have received only one message, while there are at least 3 messages in the queue?

**Comment by dobryakov** [comment]
![p0ayzuz 1](https://cloud.githubusercontent.com/assets/973470/18676772/6c65391a-7f5f-11e6-82db-bd8987d68ec4.png)

**Comment by benwilson512** [comment]
Well, keep in mind that SQS is an eventually consistent system. Messages may not show up immediately after placing them in the queue. Can you check now?

**Comment by dobryakov** [comment]
I left them alone for 1 hour, and have checked now. Issue is still present: I have received only ONE message :(
Then I send second request, I have got another message, but still only one.
Have you any idea?

**Comment by benwilson512** [comment]
I don't yet no. The SQS documentation http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html has the example

```
http://sqs.us-east-1.amazonaws.com/123456789012/testQueue/
?Action=ReceiveMessage
&MaxNumberOfMessages=5
&VisibilityTimeout=15
&AttributeName=All;
&Version=2012-11-05
&Expires=2014-04-18T22%3A52%3A43PST
&AUTHPARAMS
```

This matches what was output from the debug requests logs. Will look into it more later today.

**Comment by benwilson512** [comment]
@scohen you're using SQS a fair bit, have you run into this?

**Comment by benwilson512** [comment]
judging by the debug output I'm not convinced this is an ExAws issue, and more of just part of the quirks associated with SQS

**Comment by scohen** [comment]
@benwilson512 Yes, but my tests are preliminary. 
I enqueue ten messages, and it looks like they succeed (I get back message ids). When I request ten messages back, I consistently get two (and only two) back.

**Comment by scohen** [comment]
@benwilson512  From the AWS docs:

>The maximum number of messages to return. Amazon SQS never returns more messages than this value but may return fewer. Values can be from 1 to 10. Default is 1.
>
> All of the messages are not necessarily returned.

**Comment by benwilson512** [comment]
Yeah the more I look around it seems like this is normal SQS behaviour. See: https://forums.aws.amazon.com/message.jspa?messageID=220494

**Comment by scohen** [comment]
Agreed; 

I was able to receive all the messages by repeatedly calling `receive_message`.  The number of messages returned varied between 1 and 3, despite 10  being in the queue. 

This isn't a bug in `ex_aws`, but normal SQS behavior.

**Comment by benwilson512** [comment]
Awesome.

**Comment by Himanshu8859** [comment]
try increasing the **WaitTimeSeconds** to 20 sec,it will resolve your issue.
