### ISSUE TITLE
Could we make retry options configurable?

### ISSUE THREAD

**Issue by ajvondrak** [CargoSense/ex_aws#224]
I'm using [Bypass](https://github.com/PSPDFKit-labs/bypass) in my test suite to intercept AWS calls:

```elixir
# config/test.exs

use Mix.Config

config :ex_aws, sqs: %{
  scheme: "http://",
  host: "127.0.0.1",
  region: "us-east-1",
  port: 1234
}

# a test might look like

defmodule Test do
  use ExUnit.Case, async: true

  setup do
    port = Application.fetch_env!(:ex_aws, :sqs).port
    bypass = Bypass.open(port: port)
    {:ok, bypass: bypass}
  end

  test "when AWS is down", %{bypass: bypass} do
    Bypass.expect bypass, fn conn -> Plug.Conn.resp(conn, 500, "down") end

    assert_raise ExAws.Error, fn ->
      ExAws.SQS.list_queues |> ExAws.request!
    end
  end
end
```

But this test takes a long time to run due to all the retries with exponential backoff, which are hard-coded into `ExAws`: https://github.com/CargoSense/ex_aws/blob/11dcf1d45abd99c53e7665c67b4c7dcaae0392d8/lib/ex_aws/request.ex#L3-L5

If only for speeding up test suites, could we make the retry options configurable? It might also be useful for people who want to tweak the defaults.

**Comment by benwilson512** [comment]
Sounds good, any chance you're interested in making a PR to that effect?

**Comment by ajvondrak** [comment]
Sure, doesn't seem like too much work. Lemme see what I can do!
