### ISSUE TITLE
How do I list objects in a nested folder in S3?

### ISSUE THREAD

**Issue by sabondano** [CargoSense/ex_aws#229]
I tried with listed_objects by using a bucket_name that included the nested folder and then using the prefix option as well but no cigar. Wondering if this is possible? If yes, how? Thank you,

**Comment by sabondano** [comment]
If you happen to be wondering this is how you can do this:
`ExAws.S3.list_objects("bucket_name", [{:prefix, "folder_name"}]) |> ExAws.request!`

**Comment by benwilson512** [comment]
FYI this is equivalent to the more idiomatic syntax:
```elixir
ExAws.S3.list_objects("bucket_name", [prefix: "folder_name"]) |> ExAws.request!
```

**Comment by sabondano** [comment]
Cool, thank you Ben. You're the man!
