### ISSUE TITLE
how to create a folder in the bucket?

### ISSUE THREAD

**Issue by mvalitov** [CargoSense/ex_aws#231]
I know that it is possible when the file is loaded to pass the path to the specified folder, and this folder will be created. 
`ExAws.S3.put_object("post", "/thumbs/sample.jpeg", my_file) |> ExAws.request!`
But i can create a folder in the bucket, without downloading the file?

**Comment by benwilson512** [comment]
Folders are just objects that end in `/`, since S3 doesn't really have real folders. http://docs.aws.amazon.com/AmazonS3/latest/UG/FolderOperations.html

```
ExAws.S3.put_object("post", "/thumbs/", "") |> ExAws.request!
```
