### ISSUE TITLE
custom request headers / persistent connections

### ISSUE THREAD

**Issue by adamkittelson** [CargoSense/ex_aws#234]
This may just be me missing something obvious, but how do I add a request header to the requests being sent by ExAws.request/2?

Specifically I'm trying to use hackney connection pools so I can re-use dynamodb and sqs connections to reduce latency, and I'm trying to figure out how to add `{"Connection", "keep-alive"}` to the request headers.

If there's not a way to do that should there be? (Or should asking AWS to keep a connection open be exposed via an option or something which would add the header?)

Thanks!
Adam

**Comment by benwilson512** [comment]
This link documents how to make a custom HTTP client: https://hexdocs.pm/ex_aws/1.0.0-beta1/ExAws.Request.HttpClient.html

You would want to do that and add whatever headers you like. From there you just configure ExAws to use that client.
