### ISSUE TITLE
head_object and head_bucket throw exception if the bucket or object does not exist

### ISSUE THREAD

**Issue by thehosepipe** [CargoSense/ex_aws#239]
Under the pre 1.0.0 version if a bucket or object does not exist the call returned {:error, {:http_error, 404,....
Now we get a case clause error. It seems to be ok for get_object but not for the two head_ calls. These fail with the following case clause error

```
** (FunctionClauseError) no function clause matching in ExAws.Request.client_error/2
    (ex_aws) lib/ex_aws/request.ex:52: ExAws.Request.client_error(%{headers: [{"x-amz-request-id", "8E8A50C29D66DE86"}, {"x-amz-id-2", "tIAlm1AxeqL++VpgUnKILoOv2/Nyx9/8CFxEvKjoWeieKEDQbv/kxy/VtuU1YPIPLYp+fdymcQA="}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Tue, 04 Oct 2016 20:28:50 GMT"}, {"Server", "AmazonS3"}], status_code: 404}, Poison)
    (ex_aws) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/s3.ex:44: ExAws.Operation.ExAws.Operation.S3.perform/2
 ```

**Comment by benwilson512** [comment]
What version are you on specifically? It'll be in your `mix.lock` file.

**Comment by thehosepipe** [comment]
"ex_aws": {:hex, :ex_aws, "1.0.0-rc.1", "1fc21b65686892fe24ea0ff699e347c30ab538f69f9ed15b6cb488cc6e1900d9", [:mix], [{:gen_stage, "~> 0.5.0", [hex: :gen_stage, optional: false]}, {:hackney, "~> 1.5", [hex: :hackney, optional: true]}, {:jsx, "~> 2.8", [hex: :jsx, optional: true]}, {:poison, "~> 1.2 or ~> 2.0", [hex: :poison, optional: true]}, {:sweet_xml, "~> 0.5", [hex: :sweet_xml, optional: true]}]}

**Comment by benwilson512** [comment]
fixed on master.

**Comment by thehosepipe** [comment]
Quick! I'll try it out here. Thanks

**Comment by thehosepipe** [comment]
Perfect!
