### ISSUE TITLE
Correct usage of EC2 filters 

### ISSUE THREAD

**Issue by thehosepipe** [CargoSense/ex_aws#241]
Im trying to use filters such as describe_instances_filters. Cant find an example anywhere and I have tried what I think should be correct from the documents...

ExAws.EC2.describe_instances([max_results: 5, filter_1: [tag: "atagvalue"] ] ) 

Have I misread the documentation? How should this be done?
Thanks

**Comment by benwilson512** [comment]
That looks correct based on the typespecs. I didn't actually write that bit though so maybe @sashaafm can weigh in?

@sashaafm is there a reason why we need the `_1` suffix on `filter_1` ?

**Comment by thehosepipe** [comment]
It looks as though the filters might be fundamentally wrong, but I'm not sure. The filter_1 is so that the querystring for AWS ends up as &Filter.1.Name=...&Filter.1.Value=...

This is a working query for example
`%ExAws.Operation.RestQuery{http_method: :get, params: %{"Action" => "DescribeInstances", "Filter.1.Name" => "private-dns-name", "Filter.1.Value.1" => _your_DNS_, "Version" => "2015-10-01"}, path: "/", service: :ec2} `

But looking into the codebase I cant see how the filters in the array get turned into those Name and Value pairs

**Comment by benwilson512** [comment]
yeah I agree. The EC2 API is massive and this just seems to be an oversight. @sashaafm any chance you've got some bandwidth to tackle this? If not I'll try to take a look at it later this week.

**Comment by benwilson512** [comment]
By way of update: This project is at this point a product of not just my own efforts but the efforts of many collaborators. I do not have the time to be 100% involved in every aspect of this enormous API. Particularly in situations like these where I am not the original author of the API in question, I am going to defer to the original author or new contributors who want to make improvements.

Specifically in this case that's @sashaafm.

**Comment by thehosepipe** [comment]
Not a problem. For now I have a workaround, furthermore I hope to find time to have a go at this myself. Some ideas but little time.

**Comment by sashaafm** [comment]
Hello @thehosepipe and @benwilson512 yes I wrote both the EC2 and RDS API implementations. I'm going to try to have a look at this during the weekend (I'll try to allocate an hour or two). I was pretty sure everything was working as I tried to test every single function with the various input possibilites (and I also heavily used both services in the past), but like Ben said it might have been an oversight, the EC2 API is truly huge.

**Comment by kyleaa** [comment]
I ran into this issue with `describe_tags` - the filter implementation is broken. I'm going to post a PR for that one and get some feedback, then I think all of the `describe_%` filter params likely need the same treatment.

**Comment by kyleaa** [comment]
ps this is the syntax you can currently use to do a tag/value filter as in the original example:

`ExAws.EC2.describe_instances([{:"Filter.1.Name", "tag-value"}, {:"Filter.1.Value.1", "atagvalue"}, {:"Filter.2.Name", "tag-key"}, {:"Filter.2.Value.1","tagname"}])`

**Comment by benwilson512** [comment]
Fixed in master.
