### ISSUE TITLE
Helper to verify SNS message

### ISSUE THREAD

**Issue by tlvenn** [CargoSense/ex_aws#248]
Hi,

I was wondering if an helper to verify SNS message would be within the scope of the library ? Hopefully it is :)

Doc: http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.verify.signature.html

**Comment by benwilson512** [comment]
That sounds like an excellent addition. Are you interested in contributing this functionality?

**Comment by tlvenn** [comment]
Sure thing, I might need some guidance but will definitely give it a shot

**Comment by tlvenn** [comment]
From an API perspective, where should that verify function live within the lib, any preference to its signature and name ?

**Comment by tlvenn** [comment]
A PR is now ready for review :)
