### ISSUE TITLE
Dynamo Key requests with Ranges

### ISSUE THREAD

**Issue by benwilson512** [CargoSense/ex_aws#25]
Dynamo queries that take a primary key need to support more than one, because you can have primary keys based on hashes and ranges.

**Comment by benwilson512** [comment]
Actually on second thought, can't we do this already? @jschoch doesn't the following work?
```elixir
Dynamo.create_table("Users", [email: :hash, age: :range], [email: :string, age: :number], 1, 1)
Dynamo.get_item("Users", [email: "foo@bar.com", age: 123])
```
Primary key spec is `@type primary_key :: [{atom, binary}] | %{atom => binary}` which allows for more than one key.

**Comment by jschoch** [comment]
yes, this appears to be working now
