### ISSUE TITLE
Elixir lists being encoded to DynamoDB sets

### ISSUE THREAD

**Issue by adamkittelson** [CargoSense/ex_aws#252]
In the example at https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/dynamo/encodable.ex#L99-L143 It shows that it determines what to encode a list to based on the values of the items in the list, e.g. `[%{"N" => 1},%{"N" => 2}] #=> %{"NS" => [1,2]}`. The problem with this behavior is because it is a set that means the values have to be unique, so while this works for `[1,2]` you'll get an error like `{"ValidationException", "Input collection contains duplicates"}` if you have a list of `{"N" => 1},%{"N" => 1}] #=> %{"NS" => [1,1]}`.

I'm not sure that there's a safe way to automate converting an elixir list to a dynamo set type as even if a particular list doesn't have duplicates that doesn't mean it should not be allowed to have duplicates, so my knee-jerk is that the safe play is to just always encode elixir lists with dynamo's generic "L" type.

Adam

**Comment by benwilson512** [comment]
Hey, this is a good point. Quite possibly we could also match on `%MapSet{}` and if they're all integers for example actually use the NS type.

Fortunately the dynamodb encoder protocol would also allow someone who wanted fine grained control over their data types to specify what they wanted.

**Comment by benwilson512** [comment]
How problematic would this change be for people already using Dynamo? If we start encoding lists of numbers as lists instead of sets is that gonna break anything?

**Comment by adamkittelson** [comment]
I'm not sure if it'd be a problem or not, I'm fairly new to dynamo. We don't have any top level lists, they're all nested in dynamo maps which I'm pretty sure changing sets to lists that are nested in a map would be fine since those maps don't have explicit schemas anyway.

I'm leaning heavily toward not using dynamo's maps anymore anyway, too many funky edge cases compared to just serializing to JSON (e.g. no null values, no empty list / map values etc). All kinds of surprising behavior, as opposed to json where the only gotcha seems to be the lack of support for integer map keys.

**Comment by benwilson512** [comment]
Hey are you able to do a PR to this effect?

**Comment by benwilson512** [comment]
This has been fixed on master. It does not include mapset support yet.

**Comment by adamkittelson** [comment]
Thanks @benwilson512, sorry I didn't get back to you yesterday, was on a plane.

We ended up just abandoning Dynamo's Map / List types in our project in favor of just serializing to JSON (fewer gotchas, no need to worry about empty lists/maps etc, only gotcha with json is no integer keys) so I didn't have a fork for this fix lying around or anything.

Adam

**Comment by benwilson512** [comment]
No worries, it was easy enough to implement.

**Comment by thehosepipe** [comment]
'How problematic would this change be for people already using Dynamo'

Late response but only just upgraded. By losing Set support we have lost the ability to do 'cheap throughput' set actions like ADD.

even if we use an encoder to override and create the table as a set then update actions like the following still try to add items as a list

    ExAws.Dynamo.update_item(
      :Table, 
      [{:batch_id, page.batch_id}, {:project_id, page.project_id}],
      expression_attribute_names: %{"#pg" => "initial_pages"},
      expression_attribute_values: %{pgval: [page.page_id]},
      update_expression: "ADD #pg  :pgval"
    )

will try and make initial_pages a list

%ExAws.Operation.JSON{before_request: nil,
 data: %{"ExpressionAttributeNames" => %{"#pg" => "initial_pages"},
   "ExpressionAttributeValues" => %{":pgval" => %{"L" => [%{"N" => "1"}]}},
   "Key" => %{"batch_id" => %{"S" => "219488-2017.04.03_22.13.55"},
     "project_id" => %{"S" => "testcompany.testprofile1"}},
   "TableName" => :Table, "UpdateExpression" => "ADD #pg  :pgval"},
 headers: [{"x-amz-target", "DynamoDB_20120810.UpdateItem"},
  {"content-type", "application/x-amz-json-1.0"}], http_method: :post,
 parser: #Function<1.126917903/1 in ExAws.Operation.JSON.new/2>, path: "/",
 service: :dynamodb, stream_builder: nil}

**Comment by benwilson512** [comment]
@thehosepipe You may need to pass a struct to `:expression_attribute_values` with which you have a custom encoder protocol set. Otherwise it has no way of knowing you should use a set.

**Comment by thehosepipe** [comment]
Ok I will do it this way. thanks
