### ISSUE TITLE
support for auto-converting DyanmoDB UpdateItem attributes into an UpdateExpression

### ISSUE THREAD

**Issue by asgoel** [CargoSense/ex_aws#256]
Not sure if this is something you consider to be outside the scope of ex_aws, but was wondering if there is any interest in making it easier to call `update_item` without having to construct the `update_expression` yourself (i.e. use what you know about the Struct and it's properties). It's pretty annoying to have to construct update expressions everywhere, and would be cool to have something similar. So something like this:

```elixir
item = %Item{id: 123, name: "Steve", birthday: "June 3, 1980"}
attribute_updates = %{id: {1234, :set},  name: {"John", :set}, birthday: {nil, :remove}}
Dynamo.update_item(item, attribute_updates: attribute_updates)
```

The last call would automatically construct an `update_expression` and use `expression_attribute_names/values` properly.

Thoughts?

**Comment by benwilson512** [comment]
At the moment I'm 👎 on this. I think it's  useful functionality, but there's a LOT of functionality that could really be used for DynamoDB. I think DynamoDB could honestly use its own library that gave its some nicer Elixir friendly APIs.

**Comment by jwinter** [comment]
Just went thru writing an update_item call and was surprised there wasn't more support, since `put_item` seems to at least do the encoding automatically.
