### ISSUE TITLE
ACL option is not working on upload method

### ISSUE THREAD

**Issue by devmarco** [CargoSense/ex_aws#263]
I tried to upload a image using ex_aws, and it is working well. But when I try to pass the option **_acl**_ equal **_public_read**_, the upload goes successful but without this option. Because when I try to access the uploaded image on the browser, it is not working because I didn't have permission what means that the image was not uploaded with public credentials.

To reproduce:

```
file.path
  |> S3.Upload.stream_file()
  |> S3.upload("bucket", path, [acl: :public_read])
  |> ExAws.request()
```

**Comment by devmarco** [comment]
@benwilson512 Any update about this issue?

**Comment by benwilson512** [comment]
Hey, I have been unable to reproduce this issue.

I created a random file full of 10mb data. I then ran:
```
"myFile"
|> S3.Upload.stream_file
|> ExAws.S3.upload(bucket, "foo", acl: :public_read)
|> ExAws.request!
```

I was then able to access the file, and on the AWS S3 console it had the public read access enabled. Other files in that bucket are not accessible.
