### ISSUE TITLE
[SNS] create_platform_application does not work

### ISSUE THREAD

**Issue by jnicklas** [CargoSense/ex_aws#264]
SNS requires the attributes map to be sent, see http://docs.aws.amazon.com/sns/latest/api/API_CreatePlatformApplication.html

Relevant section:

> Attributes , Attributes.entry.N.key (key), Attributesentry.N.value (value)
> For a list of attributes, see SetPlatformApplicationAttributes
> 
> Type: String to String map
> 
> Required: Yes

ExAws does not currently send this, so the API call fails like this:

```
{:error,
 {:http_error, 400,
  %{code: "ValidationError", detail: "",
    message: "1 validation error detected: Value null at 'attributes' failed to satisfy constraint: Member must not be null",
    request_id: "cf35f6dd-2c86-5722-bfec-a65c562138c6", type: "Sender"}}}
```

**Comment by benwilson512** [comment]
Fixed in Master
