### ISSUE TITLE
[SNS] Implement missing API calls

### ISSUE THREAD

**Issue by jnicklas** [CargoSense/ex_aws#267]
Sticking to the main ones which seem obviously useful as opposed to listing all the esoteric ones :)
- [x] [DeletePlatformApplication](http://docs.aws.amazon.com/sns/latest/api/API_DeletePlatformApplication.html)
- [x] [ListPlatformApplications](http://docs.aws.amazon.com/sns/latest/api/API_ListPlatformApplications.html)
- [x] [GetEndpointAttributes](http://docs.aws.amazon.com/sns/latest/api/API_GetEndpointAttributes.html)
- [x] [SetEndpointAttributes](http://docs.aws.amazon.com/sns/latest/api/API_SetEndpointAttributes.html)
- [x] [GetSubscriptionAttributes](http://docs.aws.amazon.com/sns/latest/api/API_GetSubscriptionAttributes.html)
- [x] [SetSubscriptionAttributes](http://docs.aws.amazon.com/sns/latest/api/API_SetSubscriptionAttributes.html)
- [x] [Unsubscribe](http://docs.aws.amazon.com/sns/latest/api/API_Unsubscribe.html)
- [x] [GetPlatformApplicationAttributes ](http://docs.aws.amazon.com/sns/latest/api/API_GetPlatformApplicationAttributes.html)

**Comment by asgoel** [comment]
@jnicklas mind if I help out with this? using SNS mobile push pretty heavily in an app I'm building and need some of the un-implemented ones.

**Comment by jnicklas** [comment]
That would be great! I haven't had time to implement these yet.

**Comment by jnicklas** [comment]
That would be really great! Please do!

tisdag 25 oktober 2016 skrev Ashu Goel <notifications@github.com>:

**Comment by asgoel** [comment]
Completed with #274. @jnicklas feel free to close.

**Comment by jnicklas** [comment]
@asgoel thank you ❤️

**Comment by benwilson512** [comment]
Thanks folks!
