### ISSUE TITLE
Add "Content-MD5" header for `S3.put_object/3` 

### ISSUE THREAD

**Issue by wli0503** [CargoSense/ex_aws#268]
I was trying to follow the [Amazon S3's guide](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) on the ObjectPUT API. Since I had some integrity requirements that I need to fulfill while uploading files to AWS, I decided to use the `Content-MD5` field in header to make sure that the upload was not corrupted. 

However, when I checked through the list of allowed headers in `ExAws.S3.Utils`. I figured out that `:content_MD5` was not included in the list.  It would be great if that's added to the list of allowed headers.

**Comment by benwilson512** [comment]
This does indeed appear to be an oversight. On it.

**Comment by benwilson512** [comment]
Fixed in Master, apologies on the delay.

**Comment by wli0503** [comment]
@benwilson512 Got it. Thank you so much!
