### ISSUE TITLE
decode lists from a non-stream scan or query and/or other lists

### ISSUE THREAD

**Issue by jschoch** [CargoSense/ex_aws#27]
https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/dynamo/decoder.ex#L8

i think you mean 

```elixir
items |> Stream.map(&decode(&1,as: struct_module))
```

regardless, you have any thoughts on the "correct" way to pipe results from a scan?

also this is a good case for scan!, i saw your notes from stream_scan, but scan could still use this.  It would require Decoder knows about "Item" vs "Items"

```elixir
#my vote
Dynamo.scan!(@t_name) |> Dynamo.Decoder.decode(as: Foo)

# vs

Dynamo.scan!(@t_name)["Items"] |> Dynamo.Decoder.decode(as: Foo)

# vs.
{:ok, stuff} = Dynamo.scan(@t_name)
Dynamo.Decoder...
```

**Comment by benwilson512** [comment]
Good catch on the `as: struct_module` thing.

I definitely agree that scan! query! and so on are in order, I plan on doing ! versions of the regular API functions here shortly.

As for decoding, I think the easiest route is simply:

```elixir
Dynamo.scan!("Users")
|> Enum.map(&Dynamo.Decoder.decode(as: User)
```

Whether scan! ought to simply unwrap from {:ok, result} to result or whether it should unwrap all theway from {:ok, %{"Items" => items}} items is definitely an interesting question, but I think I'll discuss it in a separate issue that talks more about bang functions in general.

I think I'm going to remove decode_collection by the way, as it doesn't really contribute anything.

```
Dynamo.scan!(Table)
|> Decoder.decode_collection(as: Foo)
```
Is actually worse than the Enum.map example prior, in that you lose control about whether you want it lazily or eagerly enumerated.

In any case, I'm gonna move the discussion of ! functions over to a new issue, and treat this one as related to whether or not to keep decode_collection.

Any reason to keep it vs `Enum.map(&Decoder.decode/1)` and `Stream.map(&Decoder.decode/1)` ?

**Comment by benwilson512** [comment]
Decided to remove decodde_collection. It doesn't contribute anything.
