### ISSUE TITLE
Error when using a Multipart Upload

### ISSUE THREAD

**Issue by andrewtimberlake** [CargoSense/ex_aws#276]
** (MatchError) no match of right hand side value: %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<InitiateMultipartUploadResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Bucket>urbrand-test</Bucket><Key>news/18/large.jpg</Key><UploadId>qucCnHtmqAxM35Txs6EVfSMa657qRwQ7q8Up8fj1HlIAa7BHf.wmQetO_yP84xmSi89xONeyel4XWWsvenO6D.yo1dsnAGbtn9M1B9g_e6Ui7mIllOnsNetWgQju4QvL</UploadId></InitiateMultipartUploadResult>", headers: [{"x-amz-id-2", "KgAce9ikPWl6wOZ/IOXzBYzOZkVw7GBbQzws9HOCk/gjVU4yvHuPDF54g5wcBofCw3HmMLUjInY="}, {"x-amz-request-id", "BDB176507E15132D"}, {"Date", "Mon, 31 Oct 2016 12:33:42 GMT"}, {"x-amz-abort-date", "Wed, 02 Nov 2016 00:00:00 GMT"}, {"x-amz-abort-rule-id", "Delete test files 7d"}, {"Transfer-Encoding", "chunked"}, {"Server", "AmazonS3"}], status_code: 200}
        (ex_aws) lib/ex_aws/s3/upload.ex:39: ExAws.S3.Upload.initialize!/2
        (ex_aws) lib/ex_aws/s3/upload.ex:83: ExAws.Operation.ExAws.S3.Upload.perform/2

Using ex_aws 1.0.0-rc.4

**Comment by benwilson512** [comment]
SweetXml is a required dependency when using S3, per the Readme.

**Comment by andrewtimberlake** [comment]
Thanks, I missed that.
