### ISSUE TITLE
Support for dynamodb streams

### ISSUE THREAD

**Issue by kyleaa** [CargoSense/ex_aws#277]
The DynamoDB streams API is very similar to the Kinesis Streams API, so should be fairly simple to implement. 

I can work on a PR, but I wasn't sure what the preferred approach is in the project - to copy the relevant Kinesis code, or attempt to move common logic into another file.

Dynamo Streams uses the dynamodb hosts but requires a different `x-amz-target` namespace than dynamodb. I wrote an incredibly hacky implementation that manipulates the `ExAws.Operation.JSON` request, but that's probably not the best idea here 😛.

**Comment by benwilson512** [comment]
Hey there.

I think the Streams API should be its own API, despite the similarities to Kinesis. AWS is free to have those APIs diverge over time, and as you said they're different target namespaces.

I would absolutely welcome a PR to support this. However I do not have the time to do so myself.

I'm gonna close this issue, but if you want to open a PR to add this feel free.
