### ISSUE TITLE
ExAWs.S3.Upload.initialize!/2 200 response does not match pattern

### ISSUE THREAD

**Issue by KronicDeth** [CargoSense/ex_aws#285]
Version: `1.0.0-rc.4`

`ExAWs.S3.Upload.initialize!/2` match is failing with

```
no match of right hand side value: 
%{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<InitiateMultipartUploadResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Bucket>BUCKET</Bucket><Key>KEY</Key><UploadId>UPLOAD_ID</UploadId></InitiateMultipartUploadResult>", headers: [{"x-amz-id-2", "AMZ_ID2"}, {"x-amz-request-id", "AMZ_REQUEST_ID"}, {"Date", "Thu, 17 Nov 2016 13:16:25 GMT"}, {"x-amz-server-side-encryption", "AES256"}, {"Transfer-Encoding", "chunked"}, {"Server", "AmazonS3"}], status_code: 200}
```

>```
>  %{body: %{upload_id: upload_id}} =
>      ExAws.S3.initiate_multipart_upload(op.bucket, op.path, op.opts)
>     |> ExAws.request!(config)
> ```
>
> -- https://github.com/CargoSense/ex_aws/blob/f52cf1be7b69448ab64019625219e28ae753c220/lib/ex_aws/s3/upload.ex#L39-L41

It's a 200 response, so I assume that means it worked, but `initialize!` is expecting a different format for the result.

**Comment by benwilson512** [comment]
Per the readme, you need to include sweet_xml when using the S3 API to get parsed responses.

**Comment by KronicDeth** [comment]
Great shame has come to my family for I, writer of READMEs and wikis, missed the `sweet_xml` mention.  (How is there not a :facepalm: on Github?!)

**Comment by benwilson512** [comment]
hahaha no problem! :D
