### ISSUE TITLE
Use shared-config-file with the ex_aws

### ISSUE THREAD

**Issue by kanmo** [CargoSense/ex_aws#287]
At first, thank you for providing useful OSS!

I want to switch account with profile parameter.
Can I use aws-shared-config-file(~/.aws/credentials) with the ex_aws?

For example, the content of file is like this.

```
[default]
aws_access_key_id=yourawsaccesskey1
aws_secret_access_key=yourawssecretaccesskey1

[profile2]
aws_access_key_id=yourawsaccesskey2
aws_secret_access_key=yourawssecretaccesskey2
```

For Ruby, like this
```
shared_credentials = Aws::SharedCredentials.new(profile_name: 'profile2')
s3_api_client = Aws::S3::Client.new(region: 'ap-northeast-1', credentials: shared_credentials)
...
```

can ex_aws like this?

**Comment by benwilson512** [comment]
https://github.com/CargoSense/ex_aws/pull/245 was just merged into master, which handles this situation.
