### ISSUE TITLE
trying to redefine client but get can't load module

### ISSUE THREAD

**Issue by mkaravaev** [CargoSense/ex_aws#288]
I've trying as said in documentation:
``` 
defmodule MyApp.S3 do
  use ExAws.S3.Client, otp_app: :my_app
end
```
and get
` module ExAws.S3.Client is not loaded and could not be found `

Trying for all modules but error is still the same.

BTW: as I'm understand right that there is no action for CreatePlatformEndpoint AWS API call in ExAws.SNS module?

**Comment by benwilson512** [comment]
What documentation are you reading? I think you have the 1.0 RC release installed, but are reading documentation from `0.5.X`. The whole `use Client` approach is gone now.

**Comment by mkaravaev** [comment]
@benwilson512 Yes you absolutely right. Thank you! I've just found it by myself too.
