### ISSUE TITLE
[SQS] Support input from GetQueueUrl

### ISSUE THREAD

**Issue by ajvondrak** [CargoSense/ex_aws#295]
I've just discovered that the "queue URL" `ExAws.SQS` functions take as input is actually assumed to be a relative path:
* [`delete_queue`](https://github.com/CargoSense/ex_aws/blob/master/test/lib/ex_aws/sqs_test.exs#L12)
* [`get_queue_attributes`](https://github.com/CargoSense/ex_aws/blob/master/test/lib/ex_aws/sqs_test.exs#L29)
* [`send_message`](https://github.com/CargoSense/ex_aws/blob/master/test/lib/ex_aws/sqs_test.exs#L90)
* etc.

The URL is [constructed by hand](https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/operation/query.ex#L37-L44), where the "queue name" is taken to be the input from the above functions [prefixed by a slash](https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/sqs.ex#L272).

However, at least SQS has the [`GetQueueUrl`](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html) API, which can be used to get the full URL. I _had_ been trying to supply this input to the `ExAws.SQS` functions, but finding that this (of course) didn't work - winds up trying to POST to the path `/https%3A/sqs.[REGION].amazonaws.com/[ACCOUNT_NUMBER]/[QUEUE_NAME]`.

I think it should at least be an option to supply the full URL to these functions. The current way appears to work for now, but I could foresee this becoming a problem: URL format migration, the queue being in a different region than your "main" config (is that possible? I dunno), etc. [Points briefly discussed in at least one StackOverflow question.](http://stackoverflow.com/questions/17537852/when-using-aws-sqs-is-there-any-reason-to-prefer-using-getqueueurl-to-building)

This does mean I have to (/can) gut an entire cache I had written mapping queue names -> URLs, since apparently I could just configure the account number and/or get it from various APIs where I previously thought I _had_ to look up the queue URL. Lots of wasted time, but less code... :rainbow: My point here being that maybe such a cache could be rolled into `ExAws`, much like the `AuthCache`.

Thoughts?

**Comment by benwilson512** [comment]
Hey there. I do see your point. Right now it uses just the normal Query operation. If we go this route SQS will likely need its own operation so that it can pass in the URL manually.

Do you have any interest in writing a PR to this effect?

**Comment by ajvondrak** [comment]
Hey, sorry for the late response, been busy with end-of-year stuff. But I'm on break now, so I'll see what I can put together in the time I have!
