### ISSUE TITLE
ExAws.S3.list_buckets Parser

### ISSUE THREAD

**Issue by mike-kasianov** [CargoSense/ex_aws#301]
`ExAws.S3.list_buckets |> ExAws.request` returns an xml inside the :body. But `ExAws.S3.list_objects("my-bucket") |> ExAws.request` returns a nested map as expected.

I gues this happens because the root element of the `list_buckets` response is `ListAllMyBucketsResult` but for `list_objects` response root is `ListBucketResult`. I see [https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/s3/parsers.ex#L7](https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/s3/parsers.ex#L7) parsing only for the `ListBucketResult` root, so the problem might be there.

**Comment by benwilson512** [comment]
This isn't a bug, there simply isn't a parser written for that operation yet. Writing the XML parsers is an extremely labor intensive process, so I've generally written the ones that I had to use, and others have contributed parsers for operations that they have used.

Do you have any interest in contributing a parser for this operation?

**Comment by mike-kasianov** [comment]
@benwilson512 Just pushed the pull request #302. 
I just started with Elixir so please make sure my changes are safe :)

**Comment by benwilson512** [comment]
Fixed in master.
