### ISSUE TITLE
CloudWatch support

### ISSUE THREAD

**Issue by stocks29** [CargoSense/ex_aws#303]
It would be great to add support for CloudWatch, specifically the ability to send events to CloudWatch.

**Comment by benwilson512** [comment]
I completely agree. At this time however I'm unfortunately not in a position to be taking feature requests for new services. The process for adding APIs these days is wildly streamlined from the past, so if you want to make a PR to that effect I am more than happy to review and merge it in.

In the meantime I'm trying to keep issues directed at things either with a relevant PR or that list bugs.

**Comment by vasumahesh1** [comment]
@benwilson512 @stocks29 I required CloudWatch too, but only the PutMetricData, so I made it on [my fork](https://github.com/vasumahesh1/ex_aws/blob/feature/mon/lib/ex_aws/monitoring.ex)... Its unpolished, but which APIs for CloudWatch would be needed?

Also, a bit new to elixir, I can submit a PR, but it might go under a lot of changes

**Comment by stocks29** [comment]
I also only require PutMetricData. @benwilson512, is that enough to start CloudWatch integration for ExAWS? :)
