### ISSUE TITLE
Dynamodb Streams: InvalidSignatureException: Credential should be scoped to correct service: 'dynamodb'

### ISSUE THREAD

**Issue by nerdyworm** [CargoSense/ex_aws#306]
I ran into this error from AWS when trying to use the DynamoStreams module.

It works locally with the java app, however, it seems to raise the exception when running against a real aws account.

I believe that the issue is that the atom `:dynamodb_streams` is used in the signing instead of `:dynamodb` as the service name.

**Comment by benwilson512** [comment]
Hey, yes unfortunately it seems the PR that added dynamodb_streams was merged prematurely. It has been reverted and its author will hopefully push fixes soon.

**Comment by benwilson512** [comment]
Closing this for now, as the code is no longer in master. There is a new PR for this service that will be reviewed soon.
