### ISSUE TITLE
Can't publish to endpoint ?

### ISSUE THREAD

**Issue by hopewise** [CargoSense/ex_aws#312]
I tried to publish to end point like this:

> p= SNS.publish("Samirrrr", [TargetArn: "arn:aws:sns:eu-central-1:006260994575:endpoint/GCM/my-app/387cb6d7-194f-3b16-9774-8b104e6135a2"]).params

I get this response:

> {"write":{"TargetArn":"arn:aws:sns:eu-central-1:006260994575:endpoint/GCM/my-app/387cb6d7-194f-3b16-9774-8b104e6135a2","Message":"Samirrrr","Action":"Publish"}}

but then, there weren't a push notification received to the phone, although I can successfully publish to the endpoint using the AWS console.

do I miss something?

**Comment by benwilson512** [comment]
What version of ExAws are you on?

If you're on any of the 1.0 releases the functions on a service just return a data structure. This data structure must be passed to `ExAws.request` or `ExAws.request!` in order to be performed.

So in your case that would be:

```
SNS.publish("Samirrrr", [TargetArn: "arn:aws:sns:eu-central-1:006260994575:endpoint/GCM/my-app/387cb6d7-194f-3b16-9774-8b104e6135a2"])
|> ExAws.request
```

**Comment by hopewise** [comment]
I am on ex_aws ~> 1.0.0-beta0 , I tried pass the data structure, I got this error:

`exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: {"$region", "sns.$region.amazonaws.com"}, http_client: ExAws.Request.Hackney, json_codec: Poison, port: 80, region: "us-east-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}, 5000) ** (EXIT) time out `

But, if I passed the `params` to the request as:

```
SNS.publish("Samirrrr", [TargetArn: "arn:aws:sns:eu-central-1:006260994575:endpoint/GCM/my-app/387cb6d7-194f-3b16-9774-8b104e6135a2"]).params
|> ExAws.request
```

I get:

`key :service not found in: %{"Action" => "Publish", "Message" => "Samirrrr", "TargetArn" => "arn:aws:sns:eu-central-1:006260994575:endpoint/GCM/my-app/387cb6d7-194f-3b16-9774-8b104e6135a2"}`

**Comment by benwilson512** [comment]
That is a very old version, please try the recently released `v1.0.0` version.

**Comment by hopewise** [comment]
Ok, I tried v1.0.0:

    {:ex_aws, ">= 1.0.0"},

I installed it and restarted the server, I still get the error time out:

`exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role], host: {"$region", "sns.$region.amazonaws.com"}, http_client: ExAws.Request.Hackney, json_codec: Poison, port: 80, region: "us-east-1", retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000], scheme: "https://", secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]}}, 5000) ** (EXIT) time out`


I've noticed in the error, that `region: "us-east-1"` while the endpoint region should be `eu-central-1` as in the config:

```
config :ex_aws, :myapp,
  access_key_id: [{:system, "XXXXXXXXXXXXXXXX"}, :instance_role],
  secret_access_key: [{:system, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}, :instance_role],
  region: "eu-central-1",
  dynamodb: [
    region: "eu-central-1"
  ],
  sns: [
    region: "eu-central-1"
  ]
```

Please advice

**Comment by benwilson512** [comment]
It's trying to use the `:instance_role` because the `:system` bit is misconfigured. You don't do `{:system, "my-access-key-id}`. Rather, you want an environment variable there. So for example i you have the environment variable for your access key id the normal `"AWS_ACCESS_KEY_ID"` you'd want `{:system, "AWS_ACCESS_KEY_ID"}`.

Why are you scoping the config under your application?

What you have now could be simplified to basically just:
```
config :ex_aws,
  region: "eu-central-1"
```

**Comment by hopewise** [comment]
Thanks,  I have it working as:

config :ex_aws,
  region: "eu-central-1",
  access_key_id: "xxxxxxxx",
  secret_access_key: "xxxxxxxxxxxxxxxxxxxxxxxx"

**Comment by benwilson512** [comment]
That works, but it is not recommended that you hard code the access keys. If you put that code up anywhere it's a major security risk. Are you familiar with what environment variables are?

**Comment by hopewise** [comment]
not really, where should the  environment variables be defined?

**Comment by hopewise** [comment]
Its my first Elixir project, I am using Phoenix Framework, I know that there is a `prod.secret.exs` but I still did not know how to utilize it.

Should the environment variables defined into `prod.secret.exs` ?
