### ISSUE TITLE
How to get the endpoint arn?

### ISSUE THREAD

**Issue by hopewise** [CargoSense/ex_aws#318]
I have successfully created end points using  `SNS.create_platform_endpoint`, however, how would I get the created endpoint arn ?

I have asked Amazon support, they told me that `create_platform_endpoint` api will return back the created endpoint arn. Thus, I tried to trace what I got:

```
%ExAws.Operation.Query{action: :create_platform_endpoint,
 params: %{"Action" => "CreatePlatformEndpoint", "CustomUserData" => nil,
   "PlatformApplicationArn" => "xxxxxxxxxxxx",
   "Token" => "xxxxxxxxxxxxx"},
 parser: &ExAws.SNS.Parsers.parse/2, path: "/", service: :sns}
```

endpoint arn  is not returned back..

Why would I need to have the endpoint arn? Because I need to use it when I publish a message, like this:

```
SNS.publish(params["message"], [TargetArn: "{endpoint arn}"])
    |> ExAws.request
```

Please advice!

**Comment by hopewise** [comment]
Any one?

**Comment by azhi** [comment]
`ExAws.Operation.Query`struct represents request to be made to AWS services, not the actual response.

My bet is that you just forgot `ExAws.request(your_sns_query)` when tracing.

**Comment by benwilson512** [comment]
This sounds correct. The data structure you have there is the request representation, not a result.

**Comment by hopewise** [comment]
@azhi : Thanks, I've the response now, but would I get value of <EndpointArn> tag?

**Comment by azhi** [comment]
(This)[https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/sns/parsers.ex#L84] should've done the actual parsing. This whole section is wrapped around `if Code.ensure_loaded?(SweetXml) do`, so i guess it is unavailable in your project.

**Comment by hopewise** [comment]
Its seems not, but how do I install it? I've checked https://github.com/awetzel/sweet_xml and there is no mentioning to the installation.. ?

**Comment by benwilson512** [comment]
Per the README, you need to add sweet xml to your dependencies list for services that use xml

**Comment by hopewise** [comment]
I have installed it& restarted the server, but I get `argument error` error at line:

    {:ok, %{body: parsed_doc}} = Parsers.parse(rsp, :create_platform_endpoint)


I tried to do as in the sns parser test in the examples, but why I got such error?

**Comment by benwilson512** [comment]
Please show the full error stacktrace, and the full code you are running.

**Comment by hopewise** [comment]
here:
![screen shot 2016-12-29 at 8 52 31 am](https://cloud.githubusercontent.com/assets/1061157/21538323/85892ba2-cda4-11e6-96a7-1ba3728986df.png)
where to_success is:

```
  def to_success(doc) do
	    {:ok, %{body: doc}}
  end
```

**Comment by benwilson512** [comment]
First note, please always copy and paste text. People have different resolutions, DPI settings, and so forth. If I want to show you a small change you could make, you force me to re-type the entire context.

Secondly, this isn't the full text. You omit the code prior to `ExAws.request` which means I have no idea what request you're actually making.

Finally, there's a bunch of unnecessary stuff here. What is `to_success` and why are you doing it? Why are you explicitly calling the parsers?

If you have sweet_xml installed all you should need to do is:
```
{:ok, %{body: parsed_doc}} = operation |> ExAws.request.
```

I'm really trying to help you but you're making this very difficult.
