### ISSUE TITLE
Reuseing TCP connections

### ISSUE THREAD

**Issue by lessless** [CargoSense/ex_aws#321]
Hello,

In heavy-load situations, instead of limiting parallelism,  Amazon recommends reusing TCP connections.
AFAIK hackney 2 is planning to introduce that feature and I want to raise an issue early.

**Comment by ericmj** [comment]
I thought hackney already supported keep-alive http connections? Have you observed that it doesn't?

**Comment by lessless** [comment]
By looking up slides from author talk at EF 2014 - it was planned as part
of v2 release.

**Comment by ericmj** [comment]
It is listed as feature here: https://github.com/benoitc/hackney/tree/1.6.2#main-features

**Comment by lessless** [comment]
Right, there is even an example in the README
https://github.com/benoitc/hackney/blob/1.6.2/README.md#reuse-a-connection
Which is actually great! I will take a look into ExAws request API to see
what it takes to implement that feature and how it may look like.

**Comment by ericmj** [comment]
Take a look at https://github.com/benoitc/hackney/blob/1.6.2/README.md#use-the-default-pool.

**Comment by benwilson512** [comment]
It isn't clear that this requires manual management. Manual management might be a feature that is coming, but it was my impression that keep alive and pool use resulted in re-used connections already.

In any case, I think the manual connection management approach is already handled by existing features. The `http_opts` you can pass like so `operation |> ExAws.request(http_opts: [foo: :bar])` are passed directly to the HTTP adapter module. From there it can be used any way you like.

My recommendation then would be to have a custom HTTP adapter module that expected a conn_ref as part of the http opts. Then you could just:

```
{:ok, conn_ref} = :hackney.connect(:hackney_tcp, host, 443, [])
operation |> ExAws.request(http_client: MyApp.ManualHackney, http_opts: [conn_ref: conn_ref])
```
