### ISSUE TITLE
FunctionClauseError) no function clause matching in Access.fetch/2

### ISSUE THREAD

**Issue by sahina** [CargoSense/ex_aws#323]
There is an issue with xml parser I think. I literally copied and pasted the "parsing a list queue response" test from:

https://github.com/CargoSense/ex_aws/blob/master/test/lib/ex_aws/sqs/parser_test.exs 

It fails...

     ** (FunctionClauseError) no function clause matching in Access.fetch/2
     stacktrace:
       (elixir) lib/access.ex:239: Access.fetch("<ListQueuesResponse>\n  <ListQueuesResult>\n    <QueueUrl>http://sqs.us-east-1.amazonaws.com/xxxx/testQueue</QueueUrl>\n  </ListQueuesResult>\n  <ResponseMetadata>\n    <RequestId>725275ae-0b9b-4762-b238-436d7c65a1ac</RequestId>\n  </ResponseMetadata>\n</ListQueuesResponse>\n", :queues)
       (elixir) lib/access.ex:269: Access.get/3
       test/controllers/page_controller_test.exs:37: (test)

**Comment by benwilson512** [comment]
Did you add sweet_xml to your dependencies list? It is not included by default because I don't want to add a dependency for someone if they are not using a service that is XML based.

**Comment by sahina** [comment]
Yes, that was the problem thanks. I think it may be useful for noob folks like to me to make sure dependencies are added explicitly. I assumed it would work out of the box.

**Comment by benwilson512** [comment]
I'm not sure what you mean by "added explicitly". Optional dependencies are critical for giving users choice, and the need to add additional dependencies is covered in the README. This is also true of the http library and the json codec.

**Comment by sahina** [comment]
So in the Getting Started section of the README says Sweet XML is supported. You show Poison dependency in the mix.exs code there but not sweet xml. Why not add sweet xml in the dependency code snippet there and make a comment like "use sweet xml if you will use SQS or S3.

**Comment by benwilson512** [comment]
>  All APIs require an http client, but only some require a json or xml codec. You only need the codec for the API you intend to use.
...
SQS: xml
S3: xml

I can make it more explicit, but it's definitely there.
