### ISSUE TITLE
Add SQS FIFO queue support

### ISSUE THREAD

**Issue by safwank** [CargoSense/ex_aws#330]
I'm trying to use `ex_aws` to write to a FIFO queue but hit a stumbling block. Apparently in order for SQS to guarantee ordering a new message parameter (Message Group ID) is required. Otherwise, the request will fail with the following message.

```
%{code: \"MissingParameter\", detail: \"\", message: \"The request must contain the parameter MessageGroupId.\"%}
```

I've scoured the code looking for the said parameter and didn't find anything related. Am I correct to assume there's no explicit support for FIFO queues yet? If so, is it possible to add it? I can submit a PR but need some guidance on how I should go about it.

**Comment by benwilson512** [comment]
SQS FIFO queues are indeed not yet supported. It looks like it would be as simple as just adding the fifo queue options enumerated here to the create queue action: http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html

**Comment by safwank** [comment]
No worries. I'll give it a crack.

**Comment by benwilson512** [comment]
In master.

**Comment by brunovsiqueira** [comment]
@benwilson512 how about SNS FIFO? Is it supported?

**Comment by bernardd** [comment]
@brunovsiqueira The service-specific stuff has long-since been broken out into its own repos. Check out https://github.com/ex-aws/ex_aws_sns
