### ISSUE TITLE
Two issues with configuration

### ISSUE THREAD

**Issue by dmilith** [CargoSense/ex_aws#338]
1. Your readme says "mix.exs" but you had "config.exs" in mind.
2. Putting creds as You shown is not working.

I had to manually define:

```elixir
config = ExAws.Config.new(:s3, [access_key_id: ..... 
```
and pass it to 

```elixir
ExAws.request(config)
```

to make it work. Instead with config entry in config.exs its throwing:

```
** (exit) exited in: GenServer.call(ExAws.Config.AuthCache, {:refresh_config, %{access_key_id: [{:system, …
** (EXIT) time out
    (elixir) lib/gen_server.ex:737: GenServer.call/3
    (ex_aws) lib/ex_aws/config.ex:66: ExAws.Config.retrieve_runtime_value/2
    (elixir) lib/stream.ex:495: anonymous fn/4 in Stream.map/2
    (elixir) lib/enum.ex:3080: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:1403: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:868: Enum.find/3
    (ex_aws) lib/ex_aws/config.ex:54: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
    (stdlib) lists.erl:1263: :lists.foldl/3

```

and a couple seconds later this one:

```

13:33:17.163 [error] GenServer ExAws.Config.AuthCache terminating
** (CaseClauseError) no case clause matching: {:error, %{reason: :connect_timeout}}
    (ex_aws) lib/ex_aws/instance_meta.ex:16: ExAws.InstanceMeta.request/2
    (ex_aws) lib/ex_aws/instance_meta.ex:34: ExAws.InstanceMeta.instance_role_credentials/1
    (ex_aws) lib/ex_aws/instance_meta.ex:40: ExAws.InstanceMeta.security_credentials/1
    (ex_aws) lib/ex_aws/config/auth_cache.ex:58: ExAws.Config.AuthCache.refresh_config/2
    (ex_aws) lib/ex_aws/config/auth_cache.ex:33: ExAws.Config.AuthCache.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 …

Last message: {:refresh_config, %{access_key_id: [{:system, …
State: ExAws.Config.AuthCache

```

**Comment by benwilson512** [comment]
If it's trying to use the instance meta it's because other mechanisms of trying to get your keys have failed. What do you have in your `config.exs` file?

**Comment by benwilson512** [comment]
Also I'm not entirely sure what `ExAws.request(config)` is doing because that isn't a valid call. You pass operations to `ExAws.request` with config overrides as an optional second argument.

**Comment by dmilith** [comment]
@benwilson512 I took data from example like this:

```elixir
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
```

Only changed these two to key and secret?

**Comment by dmilith** [comment]
I assume it's just to change env values right?

**Comment by benwilson512** [comment]
> Only changed these two to key and secret?

I'm sorry I don't understand what this means. What have you changed, and what did you change it to?

**Comment by dmilith** [comment]
Yea, I think I just misunderstood the config.exs thing.. It's accepting credentials from environment.. I thought I can put creds temporarely to config.exs - and that's what I was trying to do.

**Comment by benwilson512** [comment]
I see. Yeah I would generally avoid putting actual strings with your keys in config as it's easy to accidentally leak them that way. Using environment variables is generally more secure.

**Comment by dmilith** [comment]
Yes. You're absolutely right :) I was just trying library. Trying to be too fast too furious here :) My bad :) Thanks!

**Comment by ryanwinchester** [comment]
Is there a way to set the config without using system env variables?

something like this:

```
config :ex_aws,
  access_key_id: "my-key-id",
  secret_access_key: "my-key"
```

instead of:

```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]
```
