### ISSUE TITLE
How to read objects only from inside of a bucket path?

### ISSUE THREAD

**Issue by dmilith** [CargoSense/ex_aws#340]
I have a buckets with milions of files inside.
I have SOMEBUCKET with path "backup" there.
Is there a way of reading only objects of that SOMEBUCKET/backup path using ExAws instead of filtering over milions of objects?

**Comment by dmilith** [comment]
So in short.. how to do:

`S3.list_objects("#{bucket}/#{path}")` is my only question.. cause AWS cli can do it in 3seconds.. and ExAws needs 5 minutes to iterate over all objects to get the result..

**Comment by dmilith** [comment]
Isn't that just hardcoded here? https://github.com/CargoSense/ex_aws/blob/b27ad88bed0c6ddca25f6c8b38bdd10ceaa240f3/lib/ex_aws/s3.ex#L163

**Comment by benwilson512** [comment]
It is not hardcoded, that value is about the service path not the object path. What AWS CLI is doing is using the `prefix` option talked about in the API docs. http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

You should be able to do:
```
S3.list_objects(bucket, prefix: path)
```
to get items under a particular prefix.

**Comment by dmilith** [comment]
I'd never think that it could be named prefix.. please add a word what what prefix means.

**Comment by benwilson512** [comment]
Fair, although I suppose as a rule ExAws assumes a familiarity with the AWS API docs since at the end of the day it's really just an elixir wrapper for the AWS API. The AWS CLI is really almost an entirely different interface, particularly when it comes to S3.

**Comment by dmilith** [comment]
Yea, S3 is literally hell for developers, so I'm actually very grateful someone did it already.
Really appreciate Your help! it worked like a charm!

**Comment by benwilson512** [comment]
Glad it worked! If you're inclined to make a PR with some examples for that option I certainly wouldn't say now ;)

**Comment by dmilith** [comment]
There You go - https://github.com/CargoSense/ex_aws/pull/341 :)
