### ISSUE TITLE
ExAws.request! doesn't seem to work in Mix.Tasks (Phoenix).

### ISSUE THREAD

**Issue by stoneth** [CargoSense/ex_aws#342]
Hey, so I try to run a simple task like delete_dynamo_table "table" or list_dynamo_tables and I get an ETS-lookup error (only when actually sending the request with ExAws.request!). Perhaps ETS isn't running yet when running a mix task? Any suggestion (other than just use "iex -S mix" to run directly)?

Example code:
defmodule Mix.Tasks.Aws.Delete do
  use Mix.Task
  def run([table | _]) do
    ...
    ExAws.Dynamo.delete_table(table) |> ExAws.request!
    ...
  end
end

Example input: (bash in project root)
mix aws.delete "table"

Example error:
** (ArgumentError) argument error
    (stdlib) :ets.lookup(ExAws.Config.AuthCache, :awscli)
    lib/ex_aws/config/auth_cache.ex:19: ExAws.Config.AuthCache.get/2
    lib/ex_aws/config.ex:71: ExAws.Config.retrieve_runtime_value/2
    (elixir) lib/stream.ex:490: anonymous fn/4 in Stream.map/2
    (elixir) lib/enum.ex:2843: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:1284: Enumerable.Stream.do_each/4
    (elixir) lib/enum.ex:839: Enum.find/3
    lib/ex_aws/config.ex:54: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
    (stdlib) lists.erl:1263: :lists.foldl/3
    lib/ex_aws/config.ex:30: ExAws.Config.new/2
    lib/ex_aws.ex:29: ExAws.request/2
    lib/ex_aws.ex:41: ExAws.request!/2
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2

**Comment by benwilson512** [comment]
Hey! Custom mix tasks don't start your application by default, which means ExAws has not been started. You either need to explicitly start ExAws specifically via `Application.ensure_all_started(:ex_aws)` along with any related dependencies (like `:hackney`), or start your full application stack by doing `Mix.run("app.start", [])`.

**Comment by stoneth** [comment]
thanks :) worked (...ensure_all_started for :ex_aws and for :hackney)
