### ISSUE TITLE
How to connect ex_aws to fake s3 in dev?

### ISSUE THREAD

**Issue by retrogradeorbit** [CargoSense/ex_aws#348]
I have a fake s3 server setup on localhost on a port.

How do I configure ex_aws to connect to it. The only thing I can set is "region", and the servers are hardcoded into a hashmap for each region.

I want something like:

```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  host: "localhost",
  port: 4568
```

Is this possible? How do I achieve this?

**Comment by benwilson512** [comment]
This should do it:

```
config :ex_aws, :s3
  host: "localhost",
  port: 4568
```

**Comment by retrogradeorbit** [comment]
Awesome thanks! That worked. And very prompt reply, too!
