### ISSUE TITLE
Performing generic requests (for other services)

### ISSUE THREAD

**Issue by TimPelgrim** [CargoSense/ex_aws#349]
Is it currently possible to perform Amazon requests for other services or would this be a worthwhile update to the library?

My use-case for this is signing requests to Amazon Elasticsearch which (as far as I can tell) is not supported by ex_aws. I would prefer to limit the access to the ES domain to a specific IAM Role for security and to do this my requests need to be signed. Signing is a non-trivial process which is obviously allready implemented in the ex_aws library so I would like to make use of this capability. 

I could not find an obvious (documented) way to do this currently. Did I overlook this? Is this something we could/should add?

**Comment by benwilson512** [comment]
Hey!

This is a good question, and you're right that there is not documentation on the subject. The good news is that it is generally quite possible.

Services are categorized by operation type. Service modules (like `Dyanamo` or `S3`) are really just nice functions for building structs of a given operation type. There's really only about a half dozen total operation types.

Provided that we already have the operation type used by the service you're looking for, you're free to just build a struct with whatever parameters sit on it you like, and do `operation |> ExAws.request`.

Elasticsearch is a `RestJSON` type operation, which we do not have at this moment. However we do have a `JSON` type operation and I think I could add `RestJSON` here pretty quickly. I need to do so for one of the PRs that was recently submitted as well.

Let me leave this open for the moment and see if I can get that added here in short order.

**Comment by TimPelgrim** [comment]
Good to hear, if I can help you in any way with implementing this just let me know

**Comment by benwilson512** [comment]
Hey! Per the updates on master it should be quite possible to simply build a particular operation struct manually. Do note that you will need to supply any config necessary for the service to the `ExAws.request` functions.
