### ISSUE TITLE
Start Ex_AWS in seeds.exs

### ISSUE THREAD

**Issue by smithaitufe** [CargoSense/ex_aws#350]
I am using Ex_Aws with Arc for image processing and upload to aws s3.

I am running some seed data. I want to know how I can start ex_aws in seeds.exs so that I can successfully upload the files to my s3 bucket when I run this command mix ecto.reset

**Comment by benwilson512** [comment]
Hey! You can start it like any other application: `Application.ensure_all_started(:ex_aws)`. You'll also need to start whatever HTTP library you use. If that's `:hackney` or `:httpoison` you can just do
```
[:ex_aws, :hackney] |> Enum.map(&Application.ensure_all_started/1)
```

**Comment by smithaitufe** [comment]
Thanks a lot. I will try this out. I keep learning stuff about elixir and phoenix from guys like you.
