### ISSUE TITLE
S3: HTTP error when uploading

### ISSUE THREAD

**Issue by safwank** [CargoSense/ex_aws#353]
I recently upgraded to v1.1 and am running into issues with `S3.upload` in my integration tests. Before the upgrade everything was working, but now I keep getting the following error when uploading/putting objects to S3

`ExAws: HTTP ERROR: :nxdomain`

Also, I use `fake-s3` (https://github.com/jubos/fake-s3) for stubbing purposes. Here's my test config (`test.exs`)

```elixir
config :ex_aws, :s3,
  access_key_id: "some_fake_key",
  secret_access_key: "some_fake_key",
  scheme: "http://",
  host: "localhost:4569",
  region: ""
```

I'm pretty sure `fake-s3` is running and resolvable. Any idea what's going on here?

**Comment by benwilson512** [comment]
If you do `ExAws.Config.new(:s3)` what do you get? This would be in your MIX_ENV=test environment.

**Comment by safwank** [comment]
@benwilson512 

```elixir
iex(1)> ExAws.Config.new(:s3)
%{access_key_id: "some_fake_key", host: "localhost:4569",
  http_client: ExAws.Request.Hackney, json_codec: Poison, region: "",
  retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000],
  scheme: "http://", secret_access_key: "some_fake_key"}
```

Looks legit to me.

**Comment by benwilson512** [comment]
Ok, if you add
```
config :ex_aws, debug_requests: true
```

what output do you get prior to the nxdomain error?

**Comment by benwilson512** [comment]
I should add that you'll need to set your log level to debug as well

**Comment by safwank** [comment]
Ahh I can see something weird with the constructed URL

`11:02:26.660 request_id=7noka0qqlvg9l50iumcdro2gil82kuv0 [debug] Request URL: "http://[localhost:4569]/foo/bar/baz.jpg?uploads=1"`

**Comment by benwilson512** [comment]
aha! You want
```
config :ex_aws, :s3,
  access_key_id: "some_fake_key",
  secret_access_key: "some_fake_key",
  scheme: "http://",
  host: "localhost",
  port: 4569,
  region: ""
```

We could definitely handle that better though.

**Comment by safwank** [comment]
D'oh! Pretty sure `port` wasn't there in 1.0, or am I mistaken?

**Comment by safwank** [comment]
At any rate it works now. Cheers @benwilson512!
