### ISSUE TITLE
`S3.list_objects` output not being parsed

### ISSUE THREAD

**Issue by bernardd** [CargoSense/ex_aws#357]
(Apologies in advance if I'm doing something obviously dense here - Elixir isn't really my strong suit yet).

I'm attempting to run the example for using the output of `list_objects` as a stream, however this is what's happening:

```
iex(myserver@ip-10-0-0-229)3> ExAws.S3.list_objects("my-bucket") |> ExAws.stream! |> Enum.to_list
** (CaseClauseError) no case clause matching: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ListBucketResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Name>my-bucket</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents>

[snip] lots of XML containing the objects I'd expect to see [/snip]

</Contents></ListBucketResult>"
    (ex_aws) lib/ex_aws/s3/lazy.ex:14: anonymous fn/1 in ExAws.S3.Lazy.stream_objects!/3
    (elixir) lib/stream.ex:1255: Stream.do_resource/5
    (elixir) lib/enum.ex:1776: Enum.reverse/2
    (elixir) lib/enum.ex:2528: Enum.to_list/1
```

It looks like the XML being received from S3 isn't being run through the parser (and thereby being turned into a stream) before it gets passed to `Enum.to_list`.

**Comment by benwilson512** [comment]
Did you add sweet xml as a dependency?

**Comment by benwilson512** [comment]
Looking at it while not on my phone, it's definitely that. We don't automatically include `sweet_xml` as a dependency because it would be an inconvenience for those who only use JSON related APIs. `sweet_xml` needs to be specified as a dependency if you want XML parsing.

**Comment by bernardd** [comment]
Yep, I'm almost certain you're right, I just wanted to test it before saying so for sure myself.

Thanks heaps for the quick response :)

**Comment by bernardd** [comment]
Yes, perfect, that was it. I figured I must have been doing something dumb. Thanks again for the help :)
