### ISSUE TITLE
Dynamo decorder decodes value "TRUE" of type string to :true atom

### ISSUE THREAD

**Issue by stocks29** [CargoSense/ex_aws#36]
Currently, the dynamo decoder is setup to decode string data types with a value of `"TRUE"` to the atom `true` upon deserialization. 

That absolutely makes sense when the dynamo type is boolean but I'm not so sure if it makes sense when the dynamo data type is string. In the case of a string data type, it seems like more of a bandaid for those that are not using the proper types when the better solution would be to simply fix their types.

I'm dealing with stock market and `"TRUE"` is a valid ticker symbol.

The leads to strange behavior since, I cannot do this...

```elixir
# Retrieve metadata
{:ok, %{"Item" => item}} = ExAws.Dynamo.get_item(table(), %{"symbol" => symbol})
metadata = ExAws.Dynamo.Decoder.decode(item, as: Metadata)

# Update metadata and save it back
new_metadata = update_metadata(metadata, new_data)
ExAws.Dynamo.put_item table(), new_metadata
```

Because the `decode` transforms the `"TRUE"` string into an atom, the `put_item` blows up with a validation exception since I'm now trying to save a boolean value into a key field which is a string field:

```elixir
{:error, {"ValidationException", "One or more parameter values were invalid: Type mismatch for key symbol expected: S actual: BOOL"}}
```

It seems like it makes sense to remove these two cases from the decode function:

```elixir
  def decode(%{"S" => "TRUE"}),     do: true
  def decode(%{"S" => "FALSE"}),    do: false
```

What do you think?

**Comment by bruce** [comment]
@stocks29 Just an FYI, @benwilson512 went and got himself married, so he'll be out for ~week on his honeymoon. I think your suggestion seems reasonable, but as this is his project, I'm going to leave the call to him -- so there will be a slight delay in this getting handled.

**Comment by benwilson512** [comment]
You're absolutely right, this is a left over thing from before Dynamo had a Boolean type. If I get bored at the airport or something I'll see if I can push a fix.

**Comment by benwilson512** [comment]
I should add that in the mean time that doing a custom implementation of the decoder and encoder protocols for your struct ought to allow you to override this behavior. I believe an example exists in the Dynamo tests.

**Comment by stocks29** [comment]
Oh, nice! Congrats Ben! Enjoy your honeymoon!  :)

**Comment by benwilson512** [comment]
v0.3.0 Fixes this.
