### ISSUE TITLE
Timeout on multipart upload of large files to S3

### ISSUE THREAD

**Issue by cvarona** [CargoSense/ex_aws#362]
Hi,

looks like nobody else is experiencing timeout when uploading "large" (actually 18MB) files to S3 buckets:

`iex(4)> large_file |> S3.Upload.stream_file |> S3.upload("mybucket", "filename.extension")|> ExAws.request!`

> [warn] ExAws: HTTP ERROR: :timeout
> ** (EXIT from #PID<0.687.0>) an exception was raised:
>     ** (ExAws.Error) ExAws Request Error!
> 
> {:error, :timeout}
> 
>         (ex_aws) lib/ex_aws.ex:46: ExAws.request!/2
>         (ex_aws) lib/ex_aws/s3/upload.ex:68: ExAws.S3.Upload.upload_chunk!/3
>         (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
>         (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
>         (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
> 
> [error]
> 
>  Task #PID<0.777.0> started from #PID<0.773.0> terminating
> ** (ExAws.Error) ExAws Request Error!
> 
> {:error, :timeout}
> 
>     (ex_aws) lib/ex_aws.ex:46: ExAws.request!/2
>     (ex_aws) lib/ex_aws/s3/upload.ex:68: ExAws.S3.Upload.upload_chunk!/3
>     (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
>     (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
>     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
> Function: &:erlang.apply/2
> 

This is my aws configuration:

> 
> config :ex_aws,
>   access_key_id: ["myaccesskey", :instance_role],
>   secret_access_key: ["secretaccesskey", :instance_role],
>   s3: [
>   scheme: "https://",
>   host: "s3-eu-west-1.amazonaws.com",
>   region: "eu-west-1"
> ]
> config :ex_aws, :retries,
>   max_attempts: 0,
>   base_backoff_in_ms: 10,
>   max_backoff_in_ms: 10_000

And this is what I get before the timeout if I enable debug_request

> [debug] Request URL: "https://s3-eu-west-1.amazonaws.com/mybucket/filename.extension?uploads=1"
> [debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=**********/20170216/eu-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=87f5ec9e00cfe696d9271ebd1e1a3ec04ed7590fa5596000333d8c02f14c249c"}, {"host", "s3-eu-west-1.amazonaws.com"}, {"x-amz-date", "20170216T142022Z"}, {"content-length", 0}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}]
> [debug] Request BODY: ""
> [debug] Request URL: "https://s3-eu-west-1.amazonaws.com/mybucket/filename.extension?partNumber=4&uploadId=fpv1bcYKrsz7pi.QsGIa50zn3wwT2SaxatMIctNlcYIUBgjUU_dMehN9kVabRVFgFzw6bf4SqFSXlbuOk_2Vb00A1.8zdiy1ML.qfkdiNsCBhBSIzZEzaVw0TAePsmPr"
> [debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=**********/20170216/eu-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=c92f80f9964473cb95e72293be16e1922fcb2ffaa0172542ed4b6d684f7c3986"}, {"host", "s3-eu-west-1.amazonaws.com"}, {"x-amz-date", "20170216T142023Z"}, {"content-length", 2671157}, {"x-amz-content-sha256", "2764478e416dc5d831cc88de39482842654d4c3ca1992c2e0d53a8bad553f5e1"}]
> [debug] Request BODY: <<195, 109, 175, 168, 183, 214, 56, 173, 235, 242, 134, 203, 46, 98, 161, 128, 39, 13, 63, 165, 35, 105, 29, 209, 148, 156, 15, 207, 158, 186, 65, 101, 142, 152, 226, 249, 43, 46, 73, 151, 50, 150, 2, 49, 60, 173, 92, 146, 212, 69, ...>>
> [debug] Request URL: "https://s3-eu-west-1.amazonaws.com/mybucket/filename.extension?partNumber=1&uploadId=fpv1bcYKrsz7pi.QsGIa50zn3wwT2SaxatMIctNlcYIUBgjUU_dMehN9kVabRVFgFzw6bf4SqFSXlbuOk_2Vb00A1.8zdiy1ML.qfkdiNsCBhBSIzZEzaVw0TAePsmPr"
> [debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=**********/20170216/eu-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=e87d77bb4c7ac935c3ff71378cb8c924ebddfbc24b6e85f70d33891b3985b125"}, {"host", "s3-eu-west-1.amazonaws.com"}, {"x-amz-date", "20170216T142023Z"}, {"content-length", 5242880}, {"x-amz-content-sha256", "95e537942faede2d15d2e6604c47ade95f331fe57f2fc075b89d66e6735aaab6"}]
> [debug] Request BODY: <<255, 216, 255, 225, 22, 242, 69, 120, 105, 102, 0, 0, 73, 73, 42, 0, 8, 0, 0, 0, 17, 0, 0, 1, 3, 0, 1, 0, 0, 0, 240, 11, 0, 0, 1, 1, 3, 0, 1, 0, 0, 0, 240, 17, 0, 0, 2, 1, 3, 0, ...>>
> [debug] Request URL: "https://s3-eu-west-1.amazonaws.com/mybucket/filename.extension?partNumber=2&uploadId=fpv1bcYKrsz7pi.QsGIa50zn3wwT2SaxatMIctNlcYIUBgjUU_dMehN9kVabRVFgFzw6bf4SqFSXlbuOk_2Vb00A1.8zdiy1ML.qfkdiNsCBhBSIzZEzaVw0TAePsmPr"
> [debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=**********/20170216/eu-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=4f51cfb6ec479d4227c0c77d0165bdd372d810021595113a92e52195cb88a267"}, {"host", "s3-eu-west-1.amazonaws.com"}, {"x-amz-date", "20170216T142023Z"}, {"content-length", 5242880}, {"x-amz-content-sha256", "2e75369dbaf359baebecb7caeaf91425b6c01f0df0536b33d0c1c2364d0baf5f"}]
> [debug] Request BODY: <<173, 88, 0, 17, 117, 43, 29, 184, 255, 0, 143, 239, 99, 236, 23, 26, 114, 189, 202, 122, 61, 230, 171, 220, 164, 112, 247, 154, 205, 255, 0, 14, 27, 235, 108, 184, 159, 252, 228, 99, 27, 128, 239, 230, 39, 135, 208, 156, 215, 114, ...>>
> [debug] Request URL: "https://s3-eu-west-1.amazonaws.com/mybucket/filename.extension?partNumber=3&uploadId=fpv1bcYKrsz7pi.QsGIa50zn3wwT2SaxatMIctNlcYIUBgjUU_dMehN9kVabRVFgFzw6bf4SqFSXlbuOk_2Vb00A1.8zdiy1ML.qfkdiNsCBhBSIzZEzaVw0TAePsmPr"
> [debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=**********/20170216/eu-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=13dedb2a9b295b1e1148656cbb8bf4ba64de873386c10f2091b1b35dc975410d"}, {"host", "s3-eu-west-1.amazonaws.com"}, {"x-amz-date", "20170216T142023Z"}, {"content-length", 5242880}, {"x-amz-content-sha256", "24789687940993b26699544538044a238752bf8a07b88af6e68a67cdba5b2a96"}]
> [debug] Request BODY: <<19, 21, 27, 5, 92, 19, 26, 255, 0, 125, 217, 51, 12, 121, 222, 66, 119, 92, 13, 182, 0, 141, 183, 102, 240, 185, 231, 162, 4, 82, 2, 152, 217, 72, 236, 91, 46, 99, 152, 94, 35, 35, 84, 81, 152, 188, 147, 239, 35, 236, ...>>

Is it me? Is it ExAws? Is it my bucket? Any idea would be much appreciated.

Regards

**Comment by taorg** [comment]
I have same issue, everything works fine with "small" files (about 5Megas), I can upload as many files as I want to, but when I try "large" files, I got same result.
And really simple code test, as @cvarona 
Are we missing some parameter ?
Thanks

**Comment by benwilson512** [comment]
Weird. when building this I successfully tested 100mb and 1gb files. Will look at this later today.

**Comment by cvarona** [comment]
Yes, weird indeed. I've tried to set a longer recv_timeout, but it failed all the same. I event touched

> def perform(op, config) do
>     with {:ok, op} <- Upload.initialize(op, config) do
>       op.src
>       |> Stream.with_index(1)
>       |> Task.async_stream(&Upload.upload_chunk!(&1, op, config),
>         max_concurrency: Keyword.get(op.opts, :max_concurrency, 4),
>         timeout: Keyword.get(op.opts, :timeout, 30_000),
>         ...

in order to force a fixed, large timeout, but to no avail.

Regards

**Comment by taorg** [comment]
Hi, have you got any chance to test this issue?
Do you need any further information?
Thx

**Comment by cvarona** [comment]
I think something must have changed; this what I get now:
```
** (exit) exited in: Task.Supervised.stream(30000)
    ** (EXIT) time out
    (elixir) lib/task/supervised.ex:209: Task.Supervised.stream_reduce/10
    (elixir) lib/enum.ex:1776: Enum.reverse/2
    (elixir) lib/enum.ex:2528: Enum.to_list/1
    (ex_aws) lib/ex_aws/s3/upload.ex:89: ExAws.Operation.ExAws.S3.Upload.perform/2
    (ex_aws) lib/ex_aws.ex:41: ExAws.request!/2
```

With debug_requests enabled:
```
[debug] Request URL: "https://s3-eu-west-1.amazonaws.com/mybucket/myfile.extension?uploads=1"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=mycredentials/20170322/eu-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=042ff074c1d34f9f6e848710b46156ea718f35460882475eaf92978cc0bc61fe"}, {"host", "s3-eu-west-1.amazonaws.com"}, {"x-amz-date", "20170322T160237Z"}, {"content-length", 0}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}]
[debug] Request BODY: ""
[debug] Request URL: "https://s3-eu-west-1.amazonaws.com/mybucket/myfile.extension?partNumber=3&uploadId=pOZpCOPyBHgVWdSaxeeIGn2Ye0e5ZI46Ts.LkZ9PmmGuDpXF8IMnQjkKa7bgIAcSKvqMUtG3rnnYFcQqq9E3SiHEIUH1GN3s_a9zpqF0gK5HfCsM3h_j7vwk42dqrV_d"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=mycredentials/20170322/eu-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=5bc62095021fa423832316b55899146ee330a5d28080e08d87567f31e3746ea7"}, {"host", "s3-eu-west-1.amazonaws.com"}, {"x-amz-date", "20170322T160237Z"}, {"content-length", 292313}, {"x-amz-content-sha256", "8cfaeb2e68076df633a0410e3b96e8d421129a9086f1f13db095515faa935a12"}]
[debug] Request BODY: <<236, 183, 42, 106, 122, 51, 198, 254, 32, 200, 53, 45, 30, 249, 98, 124, 13, 63, 23, 177, 159, 226, 222, 164, 17, 253, 43, 3, 194, 31, 16, 126, 39, 181, 189, 155, 233, 87, 205, 22, 141, 113, 110, 98, 158, 228, 70, 207, 135, 199, ...>>
[debug] Request URL: "https://s3-eu-west-1.amazonaws.com/mybucket/myfile.extension?partNumber=1&uploadId=pOZpCOPyBHgVWdSaxeeIGn2Ye0e5ZI46Ts.LkZ9PmmGuDpXF8IMnQjkKa7bgIAcSKvqMUtG3rnnYFcQqq9E3SiHEIUH1GN3s_a9zpqF0gK5HfCsM3h_j7vwk42dqrV_d"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=mycredentials/20170322/eu-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=e831cb99c85450e3cf7b65e09abbaf3aebf0466f58edaee09ed378a402345423"}, {"host", "s3-eu-west-1.amazonaws.com"}, {"x-amz-date", "20170322T160237Z"}, {"content-length", 5242880}, {"x-amz-content-sha256", "d012fe6d07268277fa6bf6152fa6309534598fe85bd07260a7adccda19543653"}]
[debug] Request BODY: <<255, 216, 255, 225, 116, 196, 69, 120, 105, 102, 0, 0, 73, 73, 42, 0, 8, 0, 0, 0, 12, 0, 15, 1, 2, 0, 6, 0, 0, 0, 158, 0, 0, 0, 16, 1, 2, 0, 13, 0, 0, 0, 164, 0, 0, 0, 18, 1, 3, 0, ...>>
[debug] Request URL: "https://s3-eu-west-1.amazonaws.com/mybucket/myfile.extension?partNumber=2&uploadId=pOZpCOPyBHgVWdSaxeeIGn2Ye0e5ZI46Ts.LkZ9PmmGuDpXF8IMnQjkKa7bgIAcSKvqMUtG3rnnYFcQqq9E3SiHEIUH1GN3s_a9zpqF0gK5HfCsM3h_j7vwk42dqrV_d"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=mycredentials/20170322/eu-west-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=d1a123a26ce80612ec24ec6c7c1f254238039a2a0a551a6a8679c9e3d3624579"}, {"host", "s3-eu-west-1.amazonaws.com"}, {"x-amz-date", "20170322T160237Z"}, {"content-length", 5242880}, {"x-amz-content-sha256", "ef0f85438c4683d83bc8dfeb13bf980d4ea8d755a25cb38a1dc8e643ac59b8cd"}]
[debug] Request BODY: <<241, 79, 192, 22, 30, 31, 248, 147, 224, 13, 95, 194, 254, 42, 190, 208, 237, 53, 143, 5, 252, 76, 210, 60, 61, 125, 107, 13, 157, 219, 21, 47, 29, 209, 148, 236, 116, 96, 93, 119, 70, 113, 156, 16, 135, 140, 126, 187, 193, 89, ...>>
```

and then the timeout.

**Comment by taorg** [comment]
Hello we found what happens to us.
It does timeout but its because our internet access is really crap.
With 
config :ex_aws, :hackney_opts,
        recv_timeout: 300_000

And timeout: 300_000 everything works fine.
So you can close this issue.
Thx a lot.

**Comment by benwilson512** [comment]
Glad you could get it sorted out!

**Comment by j-san** [comment]
Hello,
I just cross this issue and after some code investigation, I've figured out that there is a timeout option to the S3.upload function. Imo, it deserve to be more prominently in the doc ;)
```
temp_file
|> ExAws.S3.Upload.stream_file()
|> ExAws.S3.upload(bucket_name, path, [timeout: 600_000])
|> ExAws.request!()
```

**Comment by benwilson512** [comment]
PR welcome.

**Comment by spencerdcarlson** [comment]
> Hello,
> I just cross this issue and after some code investigation, I've figured out that there is a timeout option to the S3.upload function. Imo, it deserve to be more prominently in the doc ;)
> 
> ```
> temp_file
> |> ExAws.S3.Upload.stream_file()
> |> ExAws.S3.upload(bucket_name, path, [timeout: 600_000])
> |> ExAws.request!()
> ```

@j-san's answer helped me resolve this issue. 

Here is the ex_aws_s3 [source](https://github.com/ex-aws/ex_aws_s3/blob/fb9bac4c51faedd07bdb795493ddbe65fc2e2e42/lib/ex_aws/s3/upload.ex#L86) if anyone is interested.

The `: timeout` option is forwarded on to the call to [Task.async_stream](https://hexdocs.pm/elixir/Task.html#async_stream/5) and defaults to `30_000`

**Comment by spencerdcarlson** [comment]
> PR welcome.

@benwilson512 - https://github.com/ex-aws/ex_aws_s3/pull/81
