### ISSUE TITLE
Poison.EncodeError unable to encode value: {"Server", "AmazonS3"}

### ISSUE THREAD

**Issue by paxer** [CargoSense/ex_aws#367]
Hi,

I am having this exception reported via `honeybadger` every time my application uploads a file to AWS S3, the problem is  - the upload is actually works, the file is there and the content of it is correct, so I wonder, why I am still getting this strange error? I've tried to use Poison 2.0 and Poison 3.0 - does not help. Has anybody ever seen this issue before?

**Comment by benwilson512** [comment]
What was the issue?

**Comment by paxer** [comment]
nothing wrong with `ex_aws` we've upgraded recently from `1.0.0.rc` to `1.1` and since then looks like the response from `ExAws.request!` has changed from `{:done, etc` to `%{body: etc` and we just did not pattern match correctly the new response format which is actually contains `{"Server", "AmazonS3"}` :)

**Comment by paxer** [comment]
btw while investigating I found that if you have `hackney` package in the app and it is upgraded from v `1.6.5` to `1.6.6` the S3 upload stopped working with some generic unclear message like `10:02:24.485 [debug] Request BODY: ""
** (ExAws.Error) ExAws Request Error!

{:error, {:http_error, 400, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>BadRequest</Code><Message>An error occurred when parsing the HTTP request.</Message>`  maybe it not `hackney` but some of its dependancies, not sure, once rolled back to `1.6.5` - all good. It is unrelated to my original issue, but just saying

**Comment by jayjun** [comment]
@paxer See #366 for hackney 1.6.6 issue.
