### ISSUE TITLE
security header for s3 when using temp credentials

### ISSUE THREAD

**Issue by brennan3** [CargoSense/ex_aws#37]
Hello,

When using temp ec2 credentials based on an IAM role, you must pass a x-amz-security-token header when making requests to S3.

The token value is just the token value from the instance metadata.

More info at: http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html

Currently, all S3 requests using the temp credentials result in: The AWS Access Key Id you provided does not exist in our records.

This should go away once the header is added in.

**Comment by benwilson512** [comment]
Good catch, will fix this week.

**Comment by benwilson512** [comment]
This has been fixed.
