### ISSUE TITLE
Specify region in Lambda request?

### ISSUE THREAD

**Issue by tgeselle** [CargoSense/ex_aws#370]
I have the same lambda function hosted in different region on AWS.

I configured ex_aws like this:

`config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: [{:system, "AWS_REGION"}, :instance_role]
`

Let's say **AWS_REGION** is set to "**us-west-1**".

If I run a Lambda request with ex_aws like that:
`ExAws.Lambda.invoke("function", payload, nil)`
By default, it's gonna use **us-west-1**

Is there a way to directly specify another region in the function invocation?

**Comment by tgeselle** [comment]
I just looked at the other issues and I found a way by specifying the region directly in ExAws.request this way:

`ExAws.Lambda.invoke("function", payload, nil) |> ExAws.request(%{region: "eu-west-1"})`

Is that the best way to do?

**Comment by benwilson512** [comment]
That is correct. You can also just use keyword list syntax: `|> ExAws.request(region: "eu-west-1")`
