### ISSUE TITLE
Getting access keys from instance_role raises an argument error

### ISSUE THREAD

**Issue by ncanning** [CargoSense/ex_aws#371]
I'm trying to use instance roles for authentication, but run into an error when it tries to look up `:aws_instance_auth` in ETS.

My config looks like this:
```
config :ex_aws,
  access_key_id: [:instance_role],
  secret_access_key: [:instance_role]
```

And the error is:
```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.lookup(ExAws.Config.AuthCache, :aws_instance_auth)
        lib/ex_aws/config/auth_cache.ex:13: ExAws.Config.AuthCache.get/1
        lib/ex_aws/config.ex:66: ExAws.Config.retrieve_runtime_value/2
        (elixir) lib/stream.ex:495: anonymous fn/4 in Stream.map/2
        (elixir) lib/enum.ex:3080: Enumerable.List.reduce/3
        (elixir) lib/stream.ex:1405: Enumerable.Stream.do_each/4
        (elixir) lib/enum.ex:868: Enum.find/3
        lib/ex_aws/config.ex:54: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
```
which indicates that it fails to pattern match the result of the ETS lookup.

I checked to make sure there was an IAM role as well:
```
root@ip-172-16-48-177:/var/lib/cloud/instance/scripts# cd ~
root@ip-172-16-48-177:~# docker exec -it batman bash
root@36f256936166:/app# curl http://169.254.169.254/latest/meta-data/iam/security-credentials/BATMAN
{
  "Code" : "Success",
  "LastUpdated" : "2017-03-04T01:22:23Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : ...,
  ...
}
```

Any idea what might cause this?

**Comment by benwilson512** [comment]
Argument error in that situation means that there isn't a table named `ExAws.Config.AuthCache`, and the most likely explanation for that is that `:ex_aws` hasn't been started. Is it on your applications list? What version of elixir are you running?

**Comment by ncanning** [comment]
Ah, you're absolutely right, somehow missed that in the documentation. Thanks for the quick response!

**Comment by SerikDM** [comment]
I probably miss something, but I can't find anything about this in documentation. Having same issue.
I added `:ex_aws` to `:extra_applications` in `mix.exs`. What else should be done?

**Comment by bernardd** [comment]
Are you making an ex_aws call from a runtime.exs or releases.exs dynamic config file? Because in those instances you need to start it explicitly.

**Comment by SerikDM** [comment]
Thank you for your reply, now I was trying to reproduce the issue in a sandbox, but didn't manage to. I removed aws credentials workaround and my application works now. :man_shrugging: 
I think my problem was testing connection manually via `app eval` command(which still fails).
