### ISSUE TITLE
Argument error when uploading file

### ISSUE THREAD

**Issue by gordoneliel** [CargoSense/ex_aws#372]
### When uploading a file with arc and arc_ecto, I get the error below (Similar to issue #311 )
It appears that the arguments to ExAws.request are wrong, I get the same error when running ExAws.S3.list_buckets |> ExAws.request

** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (crypto) :crypto.hmac_nif(:sha256, ["AWS4", nil], "20170304")
        (crypto) crypto.erl:766: :crypto.hmac/6
        (ex_aws) lib/ex_aws/auth/signatures.ex:14: ExAws.Auth.Signatures.signing_key/3
        (ex_aws) lib/ex_aws/auth/signatures.ex:7: ExAws.Auth.Signatures.generate_signature_v4/4
        (ex_aws) lib/ex_aws/auth.ex:55: ExAws.Auth.auth_header/7
        (ex_aws) lib/ex_aws/auth.ex:18: ExAws.Auth.headers/6
        (ex_aws) lib/ex_aws/request.ex:27: ExAws.Request.request_and_retry/7
        (ex_aws) lib/ex_aws/operation/s3.ex:44: ExAws.Operation.ExAws.Operation.S3.perform/2
        (ex_aws) lib/ex_aws.ex:41: ExAws.request!/2
        (ex_aws) lib/ex_aws/s3/upload.ex:41: ExAws.S3.Upload.initialize!/2
        (ex_aws) lib/ex_aws/s3/upload.ex:83: ExAws.Operation.ExAws.S3.Upload.perform/2
        lib/arc/storage/s3.ex:57: Arc.Storage.S3.do_put/3
        (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

**Comment by benwilson512** [comment]
It would appear that your keys are not configured correctly. If you do `ExAws.Config.new(:s3)` do you see your access key and secret key configured?

What does your mix config look like?

**Comment by gordoneliel** [comment]
@benwilson512 You are right! Running ExAws.Config.new(:s3) shows nil access key and secret key. But I'm not sure why. Below is my config for arc and ex_aws

config :arc,
    bucket: "whale-bucket",
    virtual_host: true

config :ex_aws,
    access_key_id: Application.get_env(:whale2, Whale2.Endpoint)[:access_key_id],
    secret_access_key: Application.get_env(:whale2, Whale2.Endpoint)[:secret_access_key],
    host: "s3-us-west-2.amazonaws.com",
    s3: [
        scheme: "https://",
        host: "s3-us-west-2.amazonaws.com",
        region: "us-west-2"

**Comment by benwilson512** [comment]
The application environment does not contain any of those values at the time that mix config is evaluated. Also, I'm not sure why you're placing the AWS keys under your phoenix endpoint.

Where are you ultimately getting the values for the keys? Are they in environment variables or are you hard coding them into your mix config?

**Comment by gordoneliel** [comment]
The keys are stored in one of the secret files (dev.secret.exs) and imported by the env(dev.exs). I'm not sure what the best way to configure this is, but by hard coding the keys  it works!

**Comment by benwilson512** [comment]
Excellent.
