### ISSUE TITLE
DynamoDB HTTP Error 404

### ISSUE THREAD

**Issue by alaister** [CargoSense/ex_aws#374]
Hey,
I am trying to use ExAws to interact with DynamoDB, however whenever I try to do any operation with DynamoDB I get the following http error:

`{:error, {:http_error, 404, %{body: "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n<head>\n  <title>Page Not Found</title>\n</head>\n<body>Page Not Found</body>\n</html>", headers: [{"Server", "Server"}, {"Date", "xxx"}, {"Content-Length", "272"}, {"Connection", "keep-alive"}, {"x-amzn-RequestId", "xxx"}, {"x-amz-crc32", "xxx"}], status_code: 404}}}`

I get this error with or without DynamoDB local running.

Any help is greatly appreciated!

Alaister

**Comment by benwilson512** [comment]
Hey! What operation was run that produced a 404? DyanmoDB isn't super RESTy so 404s weren't a  normal part of a possible response, at least last when I was looking at it (admittedly, a while ago).

**Comment by alaister** [comment]
I tried both creating a table and getting a single item.
Yeah I agree about the not resty side of it, from looking at the docs 404 means a malformed query string?
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/CommonErrors.html

**Comment by benwilson512** [comment]
Oh what version of hackney are you on?

**Comment by kyleaa** [comment]
Hackney 1.6.6 definitely is one cause of this. Could we loosen hackney to "~> 1.7" rather than pinning to the minor version? It's probably overly optimistic of me to hope I could remove my hackney override given the frequent broken releases...

**Comment by benwilson512** [comment]
My plan is to make it more strict rather than more loose. I'm gonna do a release that permits `1.6.5` and `1.7.1`.

**Comment by alaister** [comment]
I am on version 1.6.5

**Comment by benwilson512** [comment]
Ah, downgrade to 1.6.5 and see if the issue goes away. @ericmj remind me why mix will let folks who aren't yet locked on a retired version upgrade to a retired version?

**Comment by alaister** [comment]
Great that fixed it! I had it on "~> 1.6.5" but changing to "== 1.6.5" installed the correct version. It is strange that it automatically grabs the retired release...

**Comment by benwilson512** [comment]
Fair enough!
