### ISSUE TITLE
Config validation broken in 1.1.0

### ISSUE THREAD

**Issue by yagooar** [CargoSense/ex_aws#375]
I have the following config:

```elixir
# config/dev.exs
config :ex_aws,
  access_key_id: "FOO_KEY_ID",
  secret_access_key: "FOO_ACCESS_KEY",
  region: "eu-west-1",
  bucket: "foo-test",
  host: "s3.amazonaws.com",
  scheme: "https://"
```
In `1.0.0`, everything works fine.

In `1.1.0`, when running the application, I get:

```
** (BadMapError) expected a map, got: [access_key_id: "FOO_KEY_ID", host: "s3.amazonaws.com", region: "eu-west-1", bucket: "foo-test", secret_access_key: "FOO_ACCESS_KEY", scheme: "https://"]
     stacktrace:
       (stdlib) :maps.find(:secret_access_key, [access_key_id: "FOO_KEY_ID", host: "s3.amazonaws.com", region: "eu-west-1", bucket: "foo-test", secret_access_key: "FOO_ACCESS_KEY", scheme: "https://"])
       (ex_aws) lib/ex_aws/auth.ex:17: ExAws.Auth.get_key/2
       (ex_aws) lib/ex_aws/auth.ex:10: ExAws.Auth.validate_config/1
       (ex_aws) lib/ex_aws/auth.ex:53: ExAws.Auth.presigned_url/7
       ...
       test/models/upload_test.exs:26: (test)
```

I could trace the issue down to this line: https://github.com/CargoSense/ex_aws/blame/master/lib/ex_aws/auth.ex#L17

It was changed in the following commit:
https://github.com/CargoSense/ex_aws/commit/983f80d6d690aea8faa58dedb887dc31a8b28a8e

I would happily provide a PR to fix this, but I need to get more input. To me, this code can't work as-is, because the config is not a map, but a keyword list.

One way to solve the issue would be to cast the keyword list to a map with https://hexdocs.pm/elixir/Enum.html#into/2 and work from there.

If you think it's the way to go, please let me know. I'm here to help.

**Comment by benwilson512** [comment]
I think the root cause is something else, since I'm running config nearly identical to you with no issues. FYI things like host and bucket are not valid config on `:ex_aws`.

I will investigate.

**Comment by benwilson512** [comment]
Can you provide more information about what you were trying to run? I've been unable to reproduce this issue.

**Comment by yagooar** [comment]
Sorry, I missed your question.

I basically run: 

```elixir
ExAws.S3.presigned_url(@config, http_method, @bucket, object, opts)
```

And then I get the error mentioned initially.

Tried again and with `1.0.0` it works perfectly fine.

**Comment by benwilson512** [comment]
I'm not sure why you're setting these things as module attributes. There also isn't any real need to have a MyApp.S3 module anymore, that all went away with 1.0.

Config has to be set at runtime in order to access stuff like environment variables and instance env. The way to get config for s3 is: `ExAws.Config.new(:s3)`, making usage of the function:
```
ExAws.Config.new(:s3) |> ExAws.S3.presigned_url(:get, "some-bucket", "path/to/object", [])
```

I will make sure to update the docs with an example.

**Comment by yagooar** [comment]
Thanks for the input, it works perfectly now. 👍
