### ISSUE TITLE
S3 List buckets returning: The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by midas** [CargoSense/ex_aws#377]
Using the correct S3 credentials I cannot list my buckets:

    ExAws.S3.list_buckets |> ExAws.request

Is returning the error "The request signature we calculated does not match the signature you provided ..."

Using the same debugging method I saw in another resolved issue, here is the request generated by ExAws compared to the canonical request returned in the error response:

GET\n/\n\ncontent-length:0\nhost:s3.amazonaws.com\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20170308T220014Z\n\ncontent-length;host;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

GET\n/\n\ncontent-length:0\nhost:s3.amazonaws.com, s3.amazonaws.com\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20170308T220014Z\n\ncontent-length;host;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

You will notice that the canonical request's host is `s3.amazonaws.com, s3.amazonaws.com` and the ExAws submitted request host is `s3.amazonaws.com`.  

I am not sure if this is the issue or if I am causing it somehow.  Please advise

**Comment by benwilson512** [comment]
Hackney released a broken version of its library, 1.6.6. I have updated ExAws to not permit that version. Downgrade hackney to 1.6.5

**Comment by midas** [comment]
That worked.  Thanks for the quick response!
