### ISSUE TITLE
XML response parsed for S3.list_objects, but not S3.upload

### ISSUE THREAD

**Issue by Bipsy** [CargoSense/ex_aws#389]
When I run the following: 

```
    %{ body: body } = "bucket-name"
      |> S3.list_objects
      |> ExAws.request!([region: "us-west-2"])
    IO.inspect body
```

I get the parsed xml result, but when I do:

```
    %{ body: body1 } = "path/to/file"
    |> S3.Upload.stream_file
    |> S3.upload("bucket-name", "#{UUID.uuid4()}.ged")
    |> ExAws.request!([region: "us-west-2"])
    IO.inspect body1
```

I get an unparsed xml string. Is this expected?

**Comment by benwilson512** [comment]
Yes, parsing requires manually writing out XML parsing due to the varied shapes of the XML returned. Some functions have an XML parser written, some do not. You can find the available parsers in https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/s3/parsers.ex

**Comment by Bipsy** [comment]
@benwilson512 So, is the idea that if I want the parser I add it myself? I'm happy to do so if I can figure it out.

**Comment by Bipsy** [comment]
@benwilson512 I think I've written a parser for the method I'd like to use modeling after the pattern in all of the other parsers. I've also added a test case, but I'm getting errors from running the tests because I don't have a valid secret key and id for AWS. What do you suggest I do for testing?
