### ISSUE TITLE
Rename file on presigned_url call

### ISSUE THREAD

**Issue by eduardonunesp** [CargoSense/ex_aws#393]
I use unique ids for my key names for my object, also keeps the original name in the database, when my user download the file it gets the unique (GUID), is it possible to force the presigned_url function to rename the object to the original name ? is there any option for that? 

Something like the headers `Content-Disposition: attachment; filename=Some Cool File.txt`

Thanks

**Comment by benwilson512** [comment]
I believe all you need to do is use the `query_params` option to set the content disposition option. I do agree an example could be useful.

**Comment by eduardonunesp** [comment]
Yeah, I just need some example indeed :)

**Comment by eduardonunesp** [comment]
I'm trying to tackle this issue again, found something:

```Elixir
ExAws.S3.presigned_url(:get, Application.get_env(:myapp, :bucket), "/uploads", response_content_disposition: "renameit.png")
```

But no success too

**Comment by eduardonunesp** [comment]
Found right way to do it

```Elixir
ExAws.S3.presigned_url(:get, Application.get_env(:myapp, :bucket), "/uploads", query_params: ["response-content-disposition": "attachment; filename=\"#{originalfilename}\"", "response-content-type": "application/octet-stream"])
```

Thanks !

**Comment by cschilbe** [comment]
This appears to not work since this change: https://github.com/ex-aws/ex_aws/commit/aa02213b39cf14559c37090b0fb1a55c77a8fa2a#diff-eafe6fd43d0b53d25332654962f10b61
