### ISSUE TITLE
[unsubstantiated] Left your keys in tests

### ISSUE THREAD

**Issue by wess** [CargoSense/ex_aws#394]
Just a heads up, you left your AWS keys in your tests

**Comment by benwilson512** [comment]
Hey! Can you point out where exactly they are?

**Comment by benwilson512** [comment]
If you're referring to this https://github.com/CargoSense/ex_aws/blob/master/test/lib/ex_aws/auth/credentials_test.exs#L9 they have the word `EXAMPLE` in them, they aren't real keys
