### ISSUE TITLE
Signature issue if object name contains space

### ISSUE THREAD

**Issue by krishnasrinivas** [CargoSense/ex_aws#396]
The problem is seen with Minio S3 server.

If the object name contains space and we do:

```
ExAws.S3.get_object("my-bucket", "a b") |> ExAws.request
```

The canonical request for calculating the signature is:
```
GET
/my-bucket/a%20b

content-length:0
host:localhost:9000
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20170421T215701Z

content-length;host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

But ex_aws sends the request with `+` instead of `%20` for space, i.e the GET request looks like this:
```
krishna@escape:~$ nc -l 9000
GET /my-bucket/a+b HTTP/1.1
Authorization: AWS4-HMAC-SHA256 Credential=SXO8VW2OFKKP2OG7AC85/20170421/us-east-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=2d24345b35050779f014ace98031e449eda6470069e2997ca4f1a464984aad9a
host: localhost:9000
x-amz-date: 20170421T215626Z
content-length: 0
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
User-Agent: hackney/1.7.1
```

Here `GET /my-bucket/a+b HTTP/1.1` should have been `GET /my-bucket/a%20b HTTP/1.1`

i.e the request should contain `%20` instead of `+`

This is causing signature error with Minio. Because minio calculates signature for `+` instead of `%20`

It works fine AWS-S3 because AWS-S3 is all forgiving :-)

Can this behavior be fixed in ex_aws?

**Comment by benwilson512** [comment]
Fixed in master.

**Comment by krishnasrinivas** [comment]
Thanks @benwilson512
