### ISSUE TITLE
ExAws.S3.Parsers.parse_list_multipart_uploads/1  undefined or private

### ISSUE THREAD

**Issue by Ajwah** [CargoSense/ex_aws#410]
When compiling,  with 

* IEx 1.4.2
* {:ex_aws, "~> 1.0"}
* ```"ex_aws": {:hex, :ex_aws, "1.1.2", "b78416d0a84efe92c22e5df8ba7ca028d63b2b4228f95871a1ecf10324b6493b", [:mix], [{:configparser_ex, "~> 0.2.1", [hex: :configparser_ex, optional: true]}, {:hackney, "1.6.3 or 1.6.5 or 1.7.1", [hex: :hackney, optional: true]}, {:jsx, "~> 2.8", [hex: :jsx, optional: true]}, {:poison, ">= 1.2.0", [hex: :poison, optional: true]}, {:sweet_xml, "~> 0.6", [hex: :sweet_xml, optional: true]}, {:xml_builder, "~> 0.0.6", [hex: :xml_builder, optional: true]}]},```

I see following warning:
```
warning: function ExAws.S3.Parsers.parse_list_multipart_uploads/1 is undefined or private. Did you mean one of:

      * parse_complete_multipart_upload/1
      * parse_initiate_multipart_upload/1
      * parse_list_parts/1

  lib/ex_aws/s3.ex:271

Generated ex_aws app
```

**Comment by benwilson512** [comment]
This is fixed in master.
