### ISSUE TITLE
EC2.describe_snapshots doesn't support more than one snapshot 

### ISSUE THREAD

**Issue by occurr** [CargoSense/ex_aws#411]
While using the ES2 function `EC2.describe_snapshots` I noticed the type spec suggests using `[snapshot_id_1: "id", .... ]`. 

Based on the documentation, I would expect the syntax to be something like: 
```
EC2.describe_snapshots([snapshot_id_1: "snap-123", snapshot_id_2: "snap-456"])
|> ExAws.request!
```

Unforchenetly this doesn't work, as `SnapshotId_1:` is an invalid Aws request. _(It expects a list of snapshot `SnapshotId: []`)_. Because of this you can only request one snapshot at a time via `EC2.describe_snapshots` with the syntax `EC2.describe_snapshots([snapshot_id: "snap-123"])`.

I also looked into the test folder and found that no tests for this case. Is this not currently supported, or am I missing something?

**Comment by benwilson512** [comment]
@sashaafm contributed the EC2 module, let's see if we can get him to chime in.

**Comment by bearleethere** [comment]
I saw on the Amazon EC2's documentation if you want to specify more than one snapshot, the naming convention seems to be SnapshotId.N: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSnapshots.html

I was able to query for more than one snapshots with the EC2.describe_snapshots, but I needed to use a quoted atom. The underscore doesn't work. It needed to be a "." followed by a number. Not only that, the atom also had to be quoted. This didn't match the documentation where it looks like this: `{:snapshot_id_1, [binary]}`. 

This is the way where I was able to get more than one specific snapshot: 
```
EC2.describe_snapshots([
  {:"snapshot_id.1", "snap-123"}, 
  {:"snapshot_id.2", "snap-456"}
]) 
|> ExAws.request(region: "earth")
```

**Comment by bearleethere** [comment]
Seems like it was a similar issue as this: https://github.com/CargoSense/ex_aws/pull/369
where the `_1` typespec'd parameters needs to switch to the `.N` counts

**Comment by occurr** [comment]
It doesn't look like this issue is isolated to describe_snapshots. Using the `describe_tags` function with filters doesn't work as expected. Currently the function returns: 
```
iex> EC2.describe_tags filters: [{:key, ["a-key", "b-key"]}, {:resource_id, "id"}]
%ExAws.Operation.RestQuery{
 action: nil, body: "", http_method: :get,
 params: %{"Action" => "DescribeTags",
   "Filters" => [key: ["a-key", "b-key"], resource_id: "id"],
   "Version" => "2015-10-01"}, parser: &ExAws.Utils.identity/2, path: "/",
 service: :ec2}
```
This is not the expected behavior based on the test `"descrive_tags with filters"`  at `/ec2_test.exs`. 
https://github.com/CargoSense/ex_aws/blob/master/test/lib/ex_aws/ec2_test.exs

**Comment by kyleaa** [comment]
@bearleethere @occurr are you using the Hex version or did you pull it from github? The latest changes in master have not been released to Hex.

There is an issue with that typespec, I'll put up a PR to fix that.

**Comment by kyleaa** [comment]
Looks like I missed some of the `.N` parameters when I made these fixes (sorry, this API is massive). They'll work for a single ID, but not multiple. I'll make another pass through and see if I can fix all of those (they should correlate to the incorrect typespecs)

ex 
```
EC2.describe_snapshots(snapshot_id: "snap-a") # Works
EC2.describe_snapshots(snapshot_id: "snap-a", snapshot_id: "snap-b") # Doesn't Work
```

**Comment by occurr** [comment]
Has this issue been fixed in any current branches?

**Comment by kyleaa** [comment]
No, the PR is pending guidance at the moment.

**Comment by benwilson512** [comment]
The PR has been merged, I believe this is fixed in master.
