### ISSUE TITLE
Encoding a value of empty list in Dynamo.

### ISSUE THREAD

**Issue by alhambra1** [CargoSense/ex_aws#415]
Hi,

We are using this wonderful library in our application, communicating with DynamoDB. Since we have our own schemas/structs, we call ExAws.Dynamo put_item and update with just a map, for example:

Dynamo.put_item("table_name", %{field: value, field2: value2})

I just noticed that attempting to insert or update a value of an empty list fails. It works if I change line 101 in the file, "lib/ex_aws/dynamo/encodable.ex", from this:

def encode([], _), do: []

to this:

def encode([], _), do: %{"L" => []}

Might this be an appropriate fix for you to apply?

Thank you,
Gilad

**Comment by benwilson512** [comment]
Fixed in master, thanks!

**Comment by alhambra1** [comment]
That's awesome, thank you very much!
