### ISSUE TITLE
Can't install alongside HTTPoison because of Hackney versions

### ISSUE THREAD

**Issue by ramonsnir** [CargoSense/ex_aws#419]
```
Failed to use "hackney" because
  ex_aws (version 1.1.0) requires ~> 1.6.5
  httpoison (version 0.11.2) requires ~> 1.8.0
  mix.lock specifies 1.8.5


Failed to use "hackney" because
  ex_aws (versions 1.1.1 and 1.1.2) requires 1.6.3 or 1.6.5 or 1.7.1
  httpoison (version 0.11.2) requires ~> 1.8.0
  mix.lock specifies 1.8.5
```

Is there a reason why `ex_aws` can't use hackney 1.8.x?

**Comment by benwilson512** [comment]
Hackney had a string of releases that had backward incompatible changes that broke its ability to be used with AWS. I have locked ExAws to the versions I know work for the time being.

You can always `override: true` on whatever dependency version you want to override this.

**Comment by ramonsnir** [comment]
To which upstream issue are you referring?

**Comment by benwilson512** [comment]
You can do
```
{:hackney, "~> 1.8.0", override: true}
```

**Comment by ramonsnir** [comment]
Thanks, but I wanted to know what open issue in hackney you're referring to so I can watch. Didn't see an issue open here, so I'm guessing it's tracked over there as a regression?

**Comment by benwilson512** [comment]
The specific issues that caused me to lock hackney to these specific versions I believe are fixed. The issue is that hackney has released too many breaking changes as patch releases, and I don't trust the project to not do so again. Thus, I have locked hackney to versions I personally have confirmed work.

**Comment by ramonsnir** [comment]
Fair enough.

We work with a vendor that decided to rename their product, so changed their top-level namespace as of  version 4.3.4...

**Comment by benwilson512** [comment]
Ouch.
