### ISSUE TITLE
Empty list inserts in DynamoDB

### ISSUE THREAD

**Issue by alhambra1** [CargoSense/ex_aws#426]
Hi again,

Thank you very much for your response last time. We are about to release an Ecto adapter for DynamoDB, which utilizes ExAw's Dynamo module for direct requests to DynamoDB (https://github.com/circles-learning-labs/ecto_adapters_dynamodb). We noticed that the module dynamo/encodable.ex removes empty lists and strings on inserts. In the case of the empty strings, we understand that this may prevent a DynamoDB error on empty string insert. But DynamoDB does seem to allow for empty list inserts. Is this an amendment you would consider? From my testing, removing line 81 in file, "lib/ex_aws/dynamo/encodable.ex" would address this:

`({_, []}, map) -> map`

(This also seems to correspond with our recent communication regarding allowing empty lists in updates: https://github.com/CargoSense/ex_aws/issues/415)

Thank you for your work!
Sincerely,

Gilad

**Comment by benwilson512** [comment]
That seems like a fine thing to change. I think when I first wrote this empty lists were not permitted. If that has changed please feel free to PR an edit.

**Comment by alhambra1** [comment]
kk, thanks!

**Comment by benwilson512** [comment]
Thanks!
