### ISSUE TITLE
How to set the expire timeout of a presigned url

### ISSUE THREAD

**Issue by eduardonunesp** [CargoSense/ex_aws#429]
What is the right way to set the expire time for a presigned URL, I tried this:

```
    {:ok, url} = ExAws.Config.new(:s3)
    |> ExAws.S3.presigned_url(:get, @bucket, s3_object,
      query_params: ["X-Amz-Expires": "86400"])
```
But the expire time is always the `X-Amz-Expires=3600` in the generated url

**Comment by benwilson512** [comment]
This is documented: https://hexdocs.pm/ex_aws/ExAws.S3.html#t:presigned_url_opts/0 IE `expires_in: 86400`. Do note that you can't specify a time longer than 1 week.
