### ISSUE TITLE
Refactor camelize_keys correctly camelize non-standard keys

### ISSUE THREAD

**Issue by occurr** [CargoSense/ex_aws#432]
Refactor camelize_keys correctly camelize non-standard keys, such as acronyms `"RoleARN"`.  

A posable solution would be to initialize a map of all the non-standard keys and their camelized forms in a separate process, or use an ETS cache.

**Comment by benwilson512** [comment]
Is this a general issue or related to a specific service you're working on? In general services with unusual camelization rules have manage the mapping for that service.

**Comment by occurr** [comment]
In EC2 there are quite a few explicit casts of `"RoleARN`, and in cloudformation there are explicit casts of `"TemplateURL"` and `"RoleARN`. I am guessing there are quite a few of these I haven't run into and in most modules.

While the current implementation works, it's not necessary the most elegant solution. It would clean up a lot of the existing code, and make changes a bit easier if normalize_params caught almost everything. A good step in that direction would be fixing `camelize_keys` to catch non-standard camelizations.

**Comment by benwilson512** [comment]
The EC2 module is indeed in a rough spot at the moment. It seems that the initial author of that service module but off a bit more than he could chew and missed some details. I'm happy to see refactors for that module, that we can then look at refactoring into the camelize_keys function itself, but given the pecularities of the EC2 API (it's one of the oldest) I'd prefer if we left camelize_keys alone for now.

**Comment by benwilson512** [comment]
As a minor note, I'm perfectly happy to have issues like https://github.com/CargoSense/ex_aws/issues/431 which are focused on public API concerns. I'm also happy to discuss changes to internal functions as part of fixing those public API issues.

In general though I don't see a lot of value in issues created that are purely with respect to the function of undocumented functions.

**Comment by occurr** [comment]
Totally a fair assessment, in future I will have discussions directly with the people it concerns when it comes to unexposed functions :)

**Comment by benwilson512** [comment]
Well or doing the discussion as part of a PR to fix API issues with EC2 module would also be totally fine.
