### ISSUE TITLE
Invalid typespec for `S3.presigned_url`

### ISSUE THREAD

**Issue by hworld** [CargoSense/ex_aws#433]
Hey there, I'm calling the S3.presigned_url func but it's messing up in dyalizer. It seems like your specced it out to take as input for the `config` variable a n empty map `%{}`. I think instead had wanted to simply specify a map type? I think in that case you would specify `map` instead. I think it's requiring an empty map but I'm passing in a config with values.

Here's my full dialyzer error in all its glory:
```
The call 'Elixir.ExAws.S3':presigned_url(config@1::#{'access_key_id':=_, 'host':=_, 'region':=_, 'scheme':=<<_:64>>, 'secret_acces
s_key':=_},'get',bucket@1::any(),path@1::any(),opts@1::[{'expires_in',86400},...]) breaks the contract (config::#{},http_method::atom(),bucket::binary(),object::binar
y(),opts::presigned_url_opts()) -> {'ok',binary()} | {'error',binary()}
```

When I change to pass in just an empty map `%{}` as config dyalizer is cool with it.

**Comment by benwilson512** [comment]
Ah yeah, it's because the meaning of `%{}` changed with the later OTP releases. Originally it meant any map. Please feel free to PR a fix.

**Comment by hworld** [comment]
fixed in https://github.com/CargoSense/ex_aws/pull/434
