### ISSUE TITLE
How to insert a set to DynamoDB?

### ISSUE THREAD

**Issue by alhambra1** [CargoSense/ex_aws#439]
When updating an item, I can set a value to, `%{"NS" => [1,2]}`, since `ExAws.Dynamo.Encoder.encode(%{"NS" => [1,2]})` yields, `%{"NS" => [1, 2]}`

But when inserting, `ExAws.Dynamo.Encodable.encode(%{"NS" => [1,2]},[])`, yields 
`%{"M" => %{"NS" => %{"L" => [%{"N" => "1"}, %{"N" => "2"}]}}}`

Is there a way to insert a set with ExAws.Dynamo.put_item ?

**Comment by benwilson512** [comment]
https://github.com/CargoSense/ex_aws/pull/424 handles automatically turning MapSets into the correct dynamo set type.

We used to do it automatically for lists but this lead to issues if the list contained duplicates. For the moment use master, I'm gonna release 1.1.3 here shortly

**Comment by alhambra1** [comment]
Thanks! (I guess I hadn't updated in a while.)
