### ISSUE TITLE
ExAws.request! method does not raise some errors

### ISSUE THREAD

**Issue by peillis** [CargoSense/ex_aws#447]
in my app I've recently discovered line logs like this:
```
2017-07-04 13:19:01.141 [warn] ExAws: HTTP ERROR: :timeout
...
2017-07-04 16:39:12.268 [warn] ExAws: HTTP ERROR: :closed
```
which I have no notice, because no error is raised. Also I'm not sure if the retries are executed, I guess not.

**Comment by ericmj** [comment]
The retries should be executed, otherwise you would get a proper error and not a warning. Do you have anything indicating that retries are not executed?

**Comment by benwilson512** [comment]
These logs do not mean that retries did not happen. https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/request.ex#L51-L52

Errors will only be raised if the request fails after all retries.
