### ISSUE TITLE
Handshake failure with S3: Unable to match altnames

### ISSUE THREAD

**Issue by evuez** [CargoSense/ex_aws#460]
I'm getting the following errors while trying to put an object on AWS S3:

```
[warn] ExAws: HTTP ERROR: {:tls_alert, 'handshake failure'}
[error] SSL: :certify: ssl_handshake.erl:1627:Fatal error: handshake failure - {bad_cert,unable_to_match_altnames}

[warn] ExAws: HTTP ERROR: {:tls_alert, 'handshake failure'}
** (ExAws.Error) ExAws Request Error!

{:error, {:tls_alert, 'handshake failure'}}
```

With `:hackney.trace(:max, :io)` I get the following trace:

```
[error] SSL: :certify: ssl_handshake.erl:1627:Fatal error: handshake failure - {bad_cert,unable_to_match_altnames}

[hackney trace 80 <0.329.0> 2017:07:27 08:19:04 4800] connect error
Content: [{module,hackney_connect},{line,262}]
[warn] ExAws: HTTP ERROR: {:tls_alert, 'handshake failure'}
[hackney trace 80 <0.329.0> 2017:07:27 08:19:06 4889] request
Content: [{module,hackney},
{line,308},
{method,put},
{url,{hackney_url,hackney_ssl,https,
  <<"BUCKET.s3.amazonaws.com">>,
  <<"/BUCKET/saT71WxdTHizUjSp7k2QvU7TGtXVUMgfRV2KrnFEjlULAEVngFqKGHcQKVuVAzj7.jpg">>,
  <<"/BUCKET/saT71WxdTHizUjSp7k2QvU7TGtXVUMgfRV2KrnFEjlULAEVngFqKGHcQKVuVAzj7.jpg">>,
  <<>>,<<>>,
  "BUCKET.s3.amazonaws.com",443,
  <<>>,<<>>}},
{headers,[{<<"Authorization">>,
  <<"...">>},
{<<"host">>,
  <<"BUCKET.s3.amazonaws.com">>},
{<<"x-amz-date">>,<<"20170727T081906Z">>},
{<<"content-length">>,14875},
{<<"x-amz-content-sha256">>,
  <<"...">>}]},
{body,<<...>>},
{options,[with_body,{recv_timeout,30000}]}]
[hackney trace 60 <0.329.0> 2017:07:27 08:19:06 4889] request without proxy
Content: [{module,hackney},{line,680}]
[hackney trace 60 <0.329.0> 2017:07:27 08:19:06 4889] connect
Content: [{module,hackney_connect},
{line,33},
{transport,hackney_ssl},
{host,"BUCKET.s3.amazonaws.com"},
{port,443},
{dynamic,true}]
[hackney trace 80 <0.329.0> 2017:07:27 08:19:06 4890] no socket in the pool
Content: [{module,hackney_connect},{line,200},{pool,default}]
```

I don't know if this is an issue with hackney, ex_aws or my network, and I have no idea how to find out the cause of this...

**Comment by ericmj** [comment]
Can you show the code? I didn't think ex_aws would connect to "BUCKET.s3.amazonaws.com" by default, instead I think it would use "s3.amazonaws.com".

**Comment by evuez** [comment]
Ok in fact it was a configuration error: I followed [this tutorial](https://medium.com/@jackacarlisle/image-uploads-with-aws-s3-elixir-phoenix-ex-aws-step-3-568ca6360c63) where it says the host should be configured to `BUCKET.s3.amazonaws.com`. 
Without this it works just fine. Sorry, I should've tested this before.

**Comment by mikepc** [comment]
As an aside, using the https:// scheme, TLS negotiation does not work on all regions s3 buckets, AND when I don't use the bucket name, the server returns a warning telling me that I SHOULD go to the bucket name, so I ended up switching to an http:// scheme and pointing at bucket.s3.amazonaws.com, now it's writing to the bucket and naming the subfolder the same as the bucket, which I'm trying to work through

**Comment by benwilson512** [comment]
Can you show your configuration? You shouldn't need to be changing the host or the scheme for ordinary usage.

**Comment by mikepc** [comment]
config :ex_aws, 
               access_key_id: System.get_env("AWS_ACCESS_KEY"),
               secret_access_key: System.get_env("AWS_SECRET_KEY"),
               s3: [ 
                  scheme: "http://", 
                  host: "assets.frobl.com.s3.amazonaws.com", 
                  region: "us-west-2" 
               ]

  alias ExAws.S3

  def save(file_name, file) do
    bucket_name = Application.get_env(:padimport, :bucket_name)
    response = S3.put_object(bucket_name, file_name, file)          
    |> ExAws.request!
  end

If I change the host to s3.amazonaws.com, the put_object responds 200, HOWEVER there is a warning in the header saying that it was redirected and I should go to the actual bucket.

If I use the https:// scheme TLS fails to negotiate :( 

In this instances I'm uploading public images, so the lack of SSL doesn't bug me, but it is really disconcerting because there *will* be data I want encrypted.
