### ISSUE TITLE
AWS Athena support?

### ISSUE THREAD

**Issue by bbassett** [CargoSense/ex_aws#472]
I'm currently working on a project in elixir and i'm trying to use AWS Athena, i've been going round and round for a few days trying to get a signed request to go through. I'm just wondering if there is any possibility of having athena support added to ex_aws?

I'd love to implement it myself and open a PR, but based on the last few days of failure, i don't think I'm technically capable enough at this point.

**Comment by benwilson512** [comment]
Hey! Can you elaborate on the issues you had with signed requests? I'm more than happy to provide some help to folks who want to help expand the library, because unfortunately at this point I really don't have the bandwidth to be able to add additional services myself.

**Comment by bbassett** [comment]
Sure thing!

Here's the code i'm working with:
```
defmodule Maat.Api.Util.Athena do
  @config %{
    secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY"),
    access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
    region: "us-east-1",
    http_client: HTTPoison,
    json_codec: Poison
  }

  def query() do
    body = %{
      NamedQueryIds: ["test_test"]
    } |> Poison.encode!()

    headers = [
      {"Host", "athena.us-east-1.amazonaws.com"},
      {"X-Amz-Target", "AmazonAthena.BatchGetNamedQuery"},
    ]
    ExAws.Request.request(:post, "https://athena.us-east-1.amazonaws.com/", body, headers, @config, :athena)
  end
```

It seems like the `ExAws.Request.requst/6` call should be signing that request properly, but i get this as a response: 
```
{:error,
 {:http_error, 403,
  %HTTPoison.Response{body: "<InvalidSignatureException>\n  <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>\n</InvalidSignatureException>\n",
   headers: [{"Date", "Wed, 23 Aug 2017 18:58:59 GMT"},
    {"x-amzn-RequestId", "#{request_id}"},
    {"Content-Length", "257"}, {"Connection", "keep-alive"}],
   request_url: "https://athena.us-east-1.amazonaws.com/", status_code: 403}}}

```

**Comment by bbassett** [comment]
My whole issue was with the headers. i changed them to 
```
    headers = [
      {"X-Amz-Target", "AmazonAthena.#{action}"},
      {"Content-Type", "application/x-amz-json-1.1"}
    ]
```
and the `ExAws.Request.request(...)` call works great. 

thanks for your work! feel free to close this issue

**Comment by benwilson512** [comment]
Cool, do note that setting the config as a module attribute is probably not what you want, you should consider just using mix config. Consult some of the other example service and operation modules.
