### ISSUE TITLE
How to publish json message?

### ISSUE THREAD

**Issue by hopewise** [CargoSense/ex_aws#473]
To publish to iOS, here is an example that works on Amazon SNS console:

```
{
"APNS_SANDBOX":"{\"aps\":{\"alert\":\"test\"}}"
}
```

the key APNS_SANDBOX must be surrounded with double quotations, and this is the problem, as the above is JSON message, and I don't know how to send a JSON message.

Anyone can help?

**Comment by benwilson512** [comment]
What have you tried so far?

**Comment by hopewise** [comment]
I can only send string message, but I need to send JSON message, if I try to pass a hash map `%{"APNS_SANDBOX"` I get error:

> protocol String.Chars not implemented for %{"APNS_SANDBOX" => "{\"aps\":{\"mutable-content\":1,\"alert\":{\"title\":\"Only if ios\",\"body\":\"Only if ios\"}},\"Avatar\":\"https://www.google.jo/search?q=missi&safe=active&tbm=isch&imgil=zYm5ERTXs2rSJM%253A%253BLZDfJY1ikUPvlM%253Bhttps%25253A%25252F%25252Fbssoomaaliya.wordpress.com%25252F2016%25252F06%25252F27%25252Fciyaaryahanka-missi-oo-sheegay-in-uu-ka-fadhiisanayo-cayaaraha%25252F&source=iu&pf=m&fir=zYm5ERTXs2rSJM%253A%252CLZDfJY1ikUPvlM%252C_&usg=__jXiWR4xe2W192wtA3ifZkHEpVYY%3D\"}"}

**Comment by benwilson512** [comment]
Can you please paste the actual code you are running.

**Comment by hopewise** [comment]
```
def push_notification(conn, params) do
    
    message= case params["platform"] do
      "ios" ->
        Poison.encode!(%{"aps" => %{"alert" => %{"body" => params["body"], "title" => params["title"]}, "mutable-content" => 1 }, "Avatar" => params["avatar"] })

        
      _ -> params["message"]
    end
    
    
    request_result= SNS.publish(%{"APNS_SANDBOX" => message}, [message_structure: :json, TargetArn: params["endpoint_arn"]])
        |> ExAws.request
    
```

**Comment by benwilson512** [comment]
Right so if you check the docs on https://hexdocs.pm/ex_aws/ExAws.SNS.html#publish/2 you'll see that the message must always be a string. You'll also see a note
> Do NOT assume that because your message is a JSON blob that you should set message_structure: to :json. This has a very specific meaning, please see http://docs.aws.amazon.com/sns/latest/api/API_Publish.html for details.

You either should be encoding the entire thing, or double encoding.

**Comment by hopewise** [comment]
Yes, I saw that, but I didn't know what to do next, as at AWS SNS console, there is an option where to send Raw or JSON message as in the attachment:
![screen shot 2017-08-24 at 3 23 20 pm](https://user-images.githubusercontent.com/1061157/29666264-3c51855e-88e0-11e7-9c5a-b3490b56aea7.png)


As raw message would not parsed when sent to iOS as:
![screen shot 2017-08-24 at 3 19 59 pm](https://user-images.githubusercontent.com/1061157/29666150-c72da032-88df-11e7-9a99-c12cbfec65be.png)

the only way has worked, is when message format is json

**Comment by benwilson512** [comment]
Try:
```
def push_notification(conn, params) do
    
    message= case params["platform"] do
      "ios" ->
        Poison.encode!(%{"aps" => %{"alert" => %{"body" => params["body"], "title" => params["title"]}, "mutable-content" => 1 }, "Avatar" => params["avatar"] })

        
      _ -> params["message"]
    end

    payload = Poison.encode!(%{"APNS_SANDBOX" => message})
    
    request_result= SNS.publish(payload, [message_structure: :json, TargetArn: params["endpoint_arn"]])
        |> ExAws.request
    
```

**Comment by hopewise** [comment]
Worked! but the avatar was not shown... thank you.
