### ISSUE TITLE
SQS retrieve_message inconsistency

### ISSUE THREAD

**Issue by ksheurs** [CargoSense/ex_aws#486]
Hi we are using `ExAws.SQS.receive_message` and `ExAws.SQS.delete_message` to process messages from our SQS queue. We're finding that `receive_message` is often returning no messages while there actually are available messages in the queue. Using `aws sqs` CLI properly retrieves them, as well as, the AWS admin.

If we restart our Elixir process the messages usually come right in too. Is it possible there is some caching happening within `ExAws.request`? We're having trouble understanding why these sometimes come in / sometimes not. Thank you!

**Comment by benwilson512** [comment]
Hey! ExAws does not do any caching. What you're seeing is pretty normal for SQS, and it's actually mentioned in the SQS docs. 

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html

> Short poll is the default behavior where a weighted random set of machines is sampled on a ReceiveMessage call. Thus, only the messages on the sampled machines are returned. If the number of messages in the queue is small (fewer than 1,000), you most likely get fewer messages than you requested per ReceiveMessage call. If the number of messages in the queue is extremely small, you might not receive any messages in a particular ReceiveMessage response. If this happens, repeat the request.

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html

> Long polling helps reduce your cost of using Amazon SQS by reducing the number of empty responses (when there are no messages available to return in reply to a ReceiveMessage request sent to an Amazon SQS queue) and eliminating false empty responses (when messages are available in the queue but aren't included in the response):

You can use the `wait_time_seconds` option to configure longpolling. https://hexdocs.pm/ex_aws/ExAws.SQS.html#t:receive_message_opts/0

**Comment by ksheurs** [comment]
Great, thanks for sharing @benwilson512 !
