### ISSUE TITLE
Upload folder on S3

### ISSUE THREAD

**Issue by Barno** [CargoSense/ex_aws#494]
Can I upload the entire folder ( with my files ) on S3?

If I use [this](https://hexdocs.pm/ex_aws/ExAws.S3.html#upload/4), I have to cycle on each file

**Comment by benwilson512** [comment]
ExAws does not provide any built in ability to do this, but it's easy to do so efficiently by combining it with normal standard library functions:

```
"path/to/folder/*"
|> Path.wildcard
|> Task.async_stream(fn path ->
  s3_path = s3_path(path) # figure out what you want to call it on s3 here
  contents = File.read!(path)
  ExAws.S3.put_object("my-bucket", s3_path, contents) |> ExAws.request!
end, max_concurrency: 20)
```

This code will upload all the files in your folder, 20 files at a time. If there are sub folders you'll need to change the path wildcard a bit, and figure out how you want to handle the pathing.
