### ISSUE TITLE
How to get list of folders only within a bucket?

### ISSUE THREAD

**Issue by azharmalik3** [CargoSense/ex_aws#495]

**Comment by benwilson512** [comment]
AWS S3 does not really have folders, but you can simulate them by combining the `prefix` and `delimiter` options as described here http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

In elixir that will look basically like: 
```
ExAws.S3.list_objects("my-bucket", delimiter: "/") |> ExAws.request!
```

Under the `:body` key there will be a `:common_prefixes` key, it contains what basically look like folders.
