### ISSUE TITLE
How to pass object expire in request?

### ISSUE THREAD

**Issue by azharmalik3** [CargoSense/ex_aws#498]
I tried to pass expires in request but it not affect
```
ExAws.S3.put_object("camera-assets", "test/test4.jpg", img, [expires_in: 1728000]) |> ExAws.request!

ExAws.S3.put_object("camera-assets", "test/test4.jpg", img, [expires: 1728000]) |> ExAws.request!
```

It alwasy set expire 1 day.

**Comment by azharmalik3** [comment]
@cargosensedev Could you please tell how to set `No expire` for S3 files while uploading?

**Comment by benwilson512** [comment]
Per the ExAws docs, the option is `expires` https://hexdocs.pm/ex_aws/ExAws.S3.html#t:put_object_opts/0

For details on each option we always direct people to the AWS docs themselves, as duplicating all of that in ExAws is neither desirable nor feasible. http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html

The docs there indicate that the Expires option is a string, following the format of https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21

**Comment by azharmalik3** [comment]
@benwilson512 I tried everything but it always set default 1-day expiry.

**Comment by benwilson512** [comment]
Please show what else you tried. Per the last link there, you need to be specifying an absolute date IE:

```
ExAws.S3.put_object("camera-assets", "test/test4.jpg", img, [expires: "Thu, 01 Dec 2020 16:00:00 GMT"]) |> ExAws.request!
```

**Comment by azharmalik3** [comment]
I tried following:
```
ExAws.S3.put_object("camera-assets", "test/test4.jpg", img, [{:expires, "Thu, 01 Dec 2020 16:00:00 GMT"}]) |> ExAws.request!
ExAws.S3.put_object("camera-assets", "test/test4.jpg", img, [expires: "Thu, 01 Dec 2020 16:00:00 GMT"]) |> ExAws.request!
```

It works without any error but same default expires date time.

**Comment by benwilson512** [comment]
I don't know what to say, perhaps you don't have permission? I just did

```
iex(3)> ExAws.S3.put_object("cargosense-test", "foo", "foo",[expires: "Thu, 01 Dec 2020 16:00:00 GMT"])  |> ExAws.request!
iex(4)> ExAws.S3.get_object("cargosense-received-files-staging", "foo") |> ExAws.request
{:ok,
 %{body: "foo",
   headers: [{"x-amz-id-2",
     "MdPGxuC6yb2dK1jKGkXWxjXaai5xSFt709vREKGL12Giw9av0GFCRuNc2nl06lQde2hoqO7dyfk="},
    {"x-amz-request-id", "88E72B5DC6744320"},
    {"Date", "Tue, 17 Oct 2017 11:51:20 GMT"},
    {"Last-Modified", "Tue, 17 Oct 2017 11:49:41 GMT"},
    {"ETag", "\"acbd18db4cc2f85cedef654fccc4a4d8\""},
    {"Expires", "Thu, 01 Dec 2020 16:00:00 GMT"}, {"Accept-Ranges", "bytes"},
    {"Content-Type", "application/octet-stream"}, {"Content-Length", "3"},
    {"Server", "AmazonS3"}], status_code: 200}}
```

Note that in the response has `{"Expires", "Thu, 01 Dec 2020 16:00:00 GMT"}`.

**Comment by azharmalik3** [comment]
@benwilson512 thanks. I will try with full permission.
