### ISSUE TITLE
Presence of `:` in S3 key causes 403 `SignatureDoesNotMatch` error

### ISSUE THREAD

**Issue by myronmarston** [CargoSense/ex_aws#52]
When using `S3.get_object!` with a key that contains a `:` character, I get a 403 `SignatureDoesNotMatch` error from AWS.  Keys that do not contain this character do not have this problem.

I'm guessing there's some bug in the way the signing logic encodes `:`.

**Comment by benwilson512** [comment]
Aight I have a fix started for this in https://github.com/CargoSense/ex_aws/pull/53

Gonna make sure tomorrow that I find all characters that need escaped then will merge in.

**Comment by myronmarston** [comment]
I confirmed your fix works.  Thanks!
