### ISSUE TITLE
client bang function fail on error with no clear exception

### ISSUE THREAD

**Issue by vadim-moz** [CargoSense/ex_aws#61]
The S3.Client `list_objects!`, `get_object!` functions do not throw meaningful exception (as expected) on error, generating `MatchError` instead.

```ex
defmodule ExAwsTest do
  use ExUnit.Case
  use ExAws.S3.Client, otp_app: Delorean.RankingsBuilder

  test "abc" do
    __MODULE__.list_objects!("foo", prefix: "bar/baz")
    assert false
  end
end
```

generates something like:
```
  1) test abc (ExAwsTest)
     test/unit/ex_aws_test.exs:5
     ** (MatchError) no match of right hand side value: {:error, {:http_error, 400, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-west-2' is wrong; expecting 'us-east-1'</Message><Region>us-east-1</Region><RequestId>C7DE1C18F8D90136</RequestId><HostId>x5m/0zmS4VlrUAzM/igI5iWwddeUYq7vozXq/x2+bmWDW6804WzntLsZ5e8m/Mqz</HostId></Error>"}}
     stacktrace:
       (ex_aws) lib/ex_aws/s3/impl.ex:57: ExAws.S3.Impl.list_objects!/3
       test/unit/ex_aws_test.exs:6
```

Quoting Dave Thomas,  _Programming Elixir_, p. 129: """The trailing exclamation point in the method name is an Elixir convention—if you see it, you know the function will raise an exception on error, and that exception will be meaningful.""" Sorry, It is not LRM, but I do not think Elixir has LRM.

**Comment by benwilson512** [comment]
Yup, I agree, this could be better.

**Comment by benwilson512** [comment]
Update: I'm actively working on a branch that generates the functions on the basis of JSON documents distributed by AWS. Those will have better error message support. For now, just consult the string returned by AWS.

**Comment by vadim-moz** [comment]
To clarify: my main concern was not the message per se. It was type of exception -- I would expect AWS / ex_aws specific one.

**Comment by benwilson512** [comment]
This has been fixed in the new approach taken by master.
