### ISSUE TITLE
Usage with OTP releases

### ISSUE THREAD

**Issue by mosic** [CargoSense/ex_aws#65]
Hi, thanks for making this library!

I'm looking into using it in our [evercam-media](https://github.com/evercam/evercam-media) application and everything worked nicely in development but I'm having problems making it run in production environment. We use OTP releases generated with [exrm](https://github.com/bitwalker/exrm) and that seems to conflict with assumptions that `ex_aws` makes. I first thought that the problem was just that `mix` wasn't included in the release, but adding it uncovered another issue.

This is the error I'm getting:

```
[error] %ArgumentError{message: "argument error"}
[error]     (stdlib) :ets.lookup(Mix.State, :env)
    (mix) lib/mix/state.ex:33: Mix.State.fetch/1
    (mix) lib/mix/state.ex:42: Mix.State.get/2
    (ex_aws) lib/ex_aws/config/defaults.ex:3: ExAws.Config.Defaults.defaults/0
    (ex_aws) lib/ex_aws/config.ex:26: ExAws.Config.get/1
    (ex_aws) lib/ex_aws/config.ex:14: ExAws.Config.build/2
    (ex_aws) lib/ex_aws/s3.ex:2: ExAws.S3.put_object!/3
    (evercam_media) lib/snapshots/snapshot_fetch.ex:69: EvercamMedia.Snapshot.store/4
```

You can see the code I'm using at: https://github.com/evercam/evercam-media/pull/42/files

Any suggestions, am I doing something wrong?

**Comment by benwilson512** [comment]
This is indeed a very weird error. The line that has the error in the stack trace is simply this: https://github.com/CargoSense/ex_aws/blob/master/lib/ex_aws/config/defaults.ex#L3 where I call `Mix.env`. Maybe that doesn't work within releases? I'll try to find out, I haven't really used them that much.

As an aside, I see you're using `System.get_env/1` in your config. This is totally fine, but be sure to know that this will pull the values from your system at the time the release is BUILT not deployed. You should use `{:system, "ENV_VARIABLE_NAME"}` if you want it to pull values at runtime.

**Comment by benwilson512** [comment]
Having talked to folks, apparently Mix.env will not work in releases unless :mix is included on your applications list. However, this isn't really a desirable state of affairs. In general, I ought not to be relying on Mix.env to set defaults.

I'm gonna mark this as a bug and push a fix that no longer relies on Mix.env. Do note however that if you rely on Dynamodb local in test or dev you will need to manually put that in your mix config now.

**Comment by mosic** [comment]
Thanks for the advice, I knowingly used `System.get_env/1` as the release is built on a local machine and the variables are passed in the `mix release` command. But now that I think about it, it may be slightly simpler to rely on the variables only being set on the production server though.

Regarding the `Mix.env`, I actually added it to the `included_applications` in `mix.exs`, before that I was getting this error:

```
** (UndefinedFunctionError) undefined function: Mix.env/0 (module Mix is not available)
    Mix.env()
```

That's how I got to the error I posted in the issue description.

Let me know when you push a fix and I'll give it a try.

**Comment by benwilson512** [comment]
Hey so can you alter your mix.exs deps entry for ExAws to look like `{:ex_aws, github: "cargosense/ex_aws", branch: "release_fixes"}` and let me know if that works for you?

**Comment by benwilson512** [comment]
I'm gonna merge this into master as all tests pass. Let me know if the issue persists.

**Comment by mosic** [comment]
Hey sorry for the late response, I was on the road. I'll try it tomorrow and let you know how it goes.
