### ISSUE TITLE
Trouble with expressions

### ISSUE THREAD

**Issue by mmcc** [CargoSense/ex_aws#73]
This is most likely a mistake on my part, so on that note, is there an easy way to see the generated Dynamo request for debugging purposes?

Let's say I have an Item in a table called Notifications:

```
{:ok, n} = Dynamo.get_item("Notifications", %{ id: "1234" });                                                                                                                                    
=> {:ok,
 %{"Item" => %{"attempts" => %{"N" => "0"}, "id" => %{"S" => "1234"},
     "max_attempts" => %{"N" => "20"}, "mock" => %{"BOOL" => false},
     "request" => %{"M" => %{}}, "response" => %{"M" => %{}},
     "state" => %{"S" => "pending"}}}}
```

I then want to update that item, and since I'm updating an older application to use expressions, I'll also need to use expression attribute names for some of these keys with reserved names.

```
Dynamo.update_item("Notifications", %{id: n.id}, %{ return_values: "ALL_NEW", expression_attribute_names: %{ "#s" => "state" }, update_expression: "SET #s = foobar" })
=> {:error,
 {"ValidationException",
  "The provided expression refers to an attribute that does not exist in the item"}}
```

Again, I'm sure this is something wrong on my end. I could always stub out the Dynamo methods and see what's being passed in, but a baked in way to get the generated request body would be really helpful in situations like this.

Edit: To make things more frustrating, things seem to be working fine with good ol' `AttributeUpdates`.

```
Dynamo.update_item(table, %{id: "1234"}, %{return_values: "ALL_NEW", attribute_updates: %{ state: %{Action: "PUT", Value: %{S: "queued"}}})
=> {:ok,
 %{"Attributes" => %{"attempts" => %{"N" => "0"}, "id" => %{"S" => "1234"},
     "max_attempts" => %{"N" => "20"}, "mock" => %{"BOOL" => false},
     "request" => %{"M" => %{}}, "response" => %{"M" => %{}},
     "state" => %{"S" => "queued"}}}}
```

**Comment by mmcc** [comment]
As expected, this was mostly me misunderstanding the new UpdateExpression syntax. I'm going to go ahead and close this.

**Comment by bruce** [comment]
@mmcc For future reference--if you didn't find this in your debugging--you can configure ex_aws to log requests with, eg:

```elixir
config :ex_aws,
  debug_requests: true
```

**Comment by benwilson512** [comment]
Thanks @bruce for mentioning this, I should feature it more prominently in the docs.

**Comment by mmcc** [comment]
*facepalm* No, I didn't find it in my debugging, but looking at the README again it's right there along with the other top level configuration options. Thanks for pointing it out, @bruce!
