### ISSUE TITLE
S3 Signed Object Urls

### ISSUE THREAD

**Issue by stavro** [CargoSense/ex_aws#78]
I may be wrong, but I don't seem to see this.

Does `ExAws` currently provide any helper functions to build and/or sign expiring urls for access to private objects on S3?

References:
  * [Ruby SDK Client Documentation](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#presigned_url-instance_method)
  * [Official Java Client Documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURLJavaSDK.html)
  * [Ericmj's Implementation](https://gist.github.com/ericmj/aa01edec5297b105b180)

**Comment by benwilson512** [comment]
It does not, although that's likely doable without too much fuss. Will look into it. PRs welcome ;)

**Comment by jordi-chacon** [comment]
Yes, I also need this.

@stavro are you working on this? Otherwise I might try to implement it myself.

**Comment by stavro** [comment]
@jordi-chacon I have not started.. so please, have at it!

**Comment by ericmj** [comment]
This is our implementation of S3 signing: https://gist.github.com/ericmj/aa01edec5297b105b180. It may be of help

**Comment by benwilson512** [comment]
Fixed by #87
