### ISSUE TITLE
Poison version in conflict with Phoenix

### ISSUE THREAD

**Issue by darkofabijan** [CargoSense/ex_aws#79]
Hello,

What would be the best way to fix this conflicting version issue?

```
Looking up alternatives for conflicting requirements on poison
  From ex_aws v0.4.9: ~> 1.2.0
  From phoenix v1.0.2: ~> 1.3
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies
```

Thanks!

**Comment by ericmj** [comment]
ex_aws should relax its requirement to `~> 1.2`.

In the mean time you can override poison with: `{:poison, "~> 1.3", override: true}`.

**Comment by benwilson512** [comment]
Thanks @ericmj that is indeed the work around. I'll relax the requirements on the next release. Given that the work around is pretty easy, I'm not gonna do a special release for just this.

**Comment by darkofabijan** [comment]
Thanks you both! :)
