### ISSUE TITLE
Support HTTPoison/hackney pools

### ISSUE THREAD

**Issue by mr-bt** [CargoSense/ex_aws#84]
At the moment hackney pools are disabled which means:
- no control on the maximum number of requests in-flight (max_connections)
- connections are not reuse

Golden plating would be to be able to have a pool per service.

https://github.com/benoitc/hackney/tree/b29a643c572bb83f8089bd57c373e7aaf1e86608#use-the-default-pool

**Comment by benwilson512** [comment]
So, this is something I'm not going to change for two reasons.
1) Pools have exhibited broken behavior in high load situations (hex.pm specifically) and are thus not a safe default.
2) It's trivially easy to set them yourself, on a per service or arbitrary basis.

Example:
```
```

**Comment by benwilson512** [comment]
Updated with example.

**Comment by mr-bt** [comment]
I don't know the details of hex.pm issues with hackney pools but hopefully the configurations used was not the one that you sugested as they would cause serious issues.

IMO right set up should be:
1. Before sending requests start the pool and set the max connections and the connections TTL
```
pool_name = :s3
options = [{:timeout, 120_000}, {:max_connections, 100}]
:ok = :hackney_pool.start_pool(pool_name, options)
```
Notes:
* The timeout IMO should be chosen on per service basis. A simple test is doing a telnet HTTP requests and check the avg disconnect time done by the service and subtract ~20%. This way hackney will disconnect proactively and connect again while if the service (S3) disconnects there's a latency to hackney acknowledge the disconnect and it can try to use a disconnected connections. Natural overhead here, so just trying reduce it. One can argue that if the timeout if bigger than the service disconnect would take full advantage of the connection TTL given by the service. However, that's not deterministic and I favour deterministic approaches. 
* Max connections should be per usage basis. Meaning it depends on: OS, hardware and service usage. By default hackney will set the pool max_connections to 50 which might not be enough depending on the service. S3 is a candidate to not use the default pool value as requests can take a long time (seconds) which will jam the pool. Load tests are required to tune the max connections (same as official SDKs - not sure if all of them).

2. Use your example

I won't discuss the why pools/queue are extensively used on IO, specially on high load situations. That's a long thread by itself! But if there isn't a known bug/issue on the hackney pools in my case I'll use them.

Down the line you're right. I can easily use hackney pools without a library change. I was missing what you reply as an example. Thank you :)

**Comment by ericmj** [comment]
Hex.pm disables the hackney pool: https://github.com/hexpm/hex_web/blob/master/config/config.exs#L39-L41 because we had issues where connections were not returned to the pool. This would cause all requests to eventually stop without any errors because their is no timeout on checking out from the pool.

**Comment by benwilson512** [comment]
I'm perfectly aware of how pools are used with IO. I've disabled pools in hackney not on the basis of some general stance towards pooling and IO but, as I said, because the particular pool implementation hackney uses has exhibited crippling behavior in production.

However, feel free to configure hackney however you like. The whole point of the adapter pattern I've taken with the request module is that ExAws doesn't need to take an opinionated stance here. I've chosen what are known safe defaults for httpoison. When their pool situation improves, I'll consider enabling it again by default.

"hopefully the configurations used was not the one that you sugested as they would cause serious issues." care to elaborate? My example simply indicates how one might use a particular pool name in an adapter, I wasn't advocating any particular recv_timeout value or pool size.

**Comment by mr-bt** [comment]
Hi @ericmj

That's a serious issue! Going without some application throttling is something I can't consider...

So, I've tried to replicate the issue by having a simple node.js server that never responses and making hackney (version 1.3.2) requests using a pool. I wasn't able to replicate the exact behaviour that you've described but I've got some unexpected weirdness.

So, I think I'm going to ditch hackney for the time being, at least until the pool issues are solved. It sounds I'll be researching for a new HTTP lib to use...

Thank you for sharing the hex.pm issue. It was very helpful.

**Comment by mr-bt** [comment]
Hi @benwilson512

Sorry if I sounded harsh. It wasn't my intention at all. I'm not native in English and sometimes I write things sounding wrong. My apologize.

> "hopefully the configurations used was not the one that you sugested as they would cause serious issues." care to elaborate?

I'll speak on my experience of releasing a game where the player assets are stored on S3 and have in average 400KB. In peak time we had ~55000 CCUs which means that we were doing around 400 req/sec to S3 (List/Put/Get/Copy) per Ec2 instance. We build the game server in .net 4.5 and the library was the official one. By default max connections were 50 as hackney. On the load tests I've bump the number of connections to 150 base on load tests results. It wasn't a complete disaster by luck... The requests started to queue up in such a way that we almost ran out-of-memory and naturally a high performance hit on the receive timeout exceptions. This had even more impact because S3 latency is not predictable as in Dynamo (latency is 1 digit figure) so in the load tests we had an average of 200ms of latency and on production we had times of 900ms with spikes up to >2s (Nothing wrong how the assets were stores as we follow S3 best practices extensively).

Lessons learned:
- The ones that I've wrote above
- Load test are not good enough (this one I knew but you know...)
- S3 is a b****
- Pools must be in place
- Pool sizing is a science when you can't predict latency

So my statement can be miss leading as I don't know what's "high load" on hex.pm means. But I've assume, wrongly, that the 50 max conns weren't enough by linking to my experience on S3.

Once again, I apologize if I sounded harsh on you. It wasn't my intention.

**Comment by lessless** [comment]
Hello @mr-bt, 

Did you get to production with the app you were working at? AWS really encourage reusing connections and I would like to know your experience on tweaking HTTP clients in that respect.

Thanks.
