### ISSUE TITLE
DynamoDB: Float encoding

### ISSUE THREAD

**Issue by mr-bt** [CargoSense/ex_aws#85]
The float encoding is using Float.to_string/1 which means that the results stored in Dynamo can be different of the ones in the source map. IMO, the encoding shouldn't implicitly transform the values to encode.

e.g. 
1.67 will be stored as "1.66999999999999992895e+00" instead of 1.67

A simple solution would be using to_string/1 instead of Float.to_string/1. However the to_string/1 is much slower that the Float.to_string/1.

Another solution is to be able to set the Float.to_string/1 options.

**Comment by benwilson512** [comment]
If we use the explicit protocol module `String.Chars.Float.to_string(0.0)` it shouldn't be much slower. Let me benchmark.

**Comment by mr-bt** [comment]
Is way more slower and it depends on the length of the float

**Comment by mr-bt** [comment]
Ohh I was speaking of the to_string/2. The String.Chars.Float.to_string/1 performs much better than the to_string/1.

**Comment by benwilson512** [comment]
yeah keep in mind if you're benchmarking though that to_string that it's based on the String.Chars protocol and will have atrocious performance characteristics in `dev` (as with all protocols) but will be much faster when `MIX_ENV=prod`. Either way, String.Chars.Float.to_string is what to_string(0.0) ends up resolving to anyway so we may as well just jump to that step
